import Lake
open Lake DSL System

package algebraicGoldbach where
  leanOptions := #[⟨`autoImplicit, false⟩]

require mathlib from git
  "https://github.com/leanprover-community/mathlib4" @ "9837ca9d65d9de6fad1ef4381750ca688774e608"

@[default_target]
lean_lib AlgebraicGoldbach

lean_lib Calibration

@[default_target]
target axiomManifest pkg : FilePath := do
  let some rootMod := pkg.findModule? `AlgebraicGoldbach
    | error "AlgebraicGoldbach root module is missing"
  let rootJob ← rootMod.olean.fetch
  let source := pkg.dir / "audit" / "Axioms.lean"
  let sourceJob ← inputTextFile source
  let leanExe ← getLean
  let leanPath ← getLeanPath
  buildFileAfterDep (pkg.dir / "AXIOMS.md") (rootJob.mix sourceJob) (text := true) fun _ => do
    let output ← IO.Process.output {
      cmd := leanExe.toString
      args := #[source.toString]
      env := #[⟨"LEAN_PATH", some leanPath.toString⟩]
    }
    if output.exitCode != 0 then
      error s!"Axiom audit failed:\n{output.stdout}\n{output.stderr}"
    IO.FS.writeFile (pkg.dir / "AXIOMS.md")
      ("# Lean axiom manifest\n\nGenerated by the default lake build. The open target is unproved.\n\n```text\n" ++
        output.stdout ++ "```\n")
