import HorizonMT.MT1
import Mathlib.Analysis.SpecialFunctions.Sqrt

noncomputable section

open scoped BigOperators
open Real

namespace HorizonMT

/-!
# MT2 — v4 final (0 sorry)

`theorem_B` proof generated by Self-Improving Engine (April 6, 2026).
`cauchy_schwarz_transfer` uses Bridge 8 directly.
-/

theorem theorem_A
  (p : MT1Params) (N : ℝ)
  (hN : N ≥ Real.exp (Real.exp (Real.exp 1))) :
  ∃ C : ℝ, 0 < C ∧
    |R_smooth_le_y p N| ≤ C * smoothMainTerm p N := by
  exact smooth_control p N hN

theorem rough_variance
  (p : MT1Params) (N A0 : ℝ)
  (hN : N ≥ 4) (hA0 : 0 < A0) :
  ∃ C : ℝ, 0 < C ∧
    meanPairVariance_rough p N ≤
      C * N ^ 2 / (Real.log N) ^ (4 + A0) := by
  exact meanPairVariance_rough_bound p N A0 hN hA0

theorem smooth_variance
  (p : MT1Params) (N : ℝ)
  (hN : N ≥ 4) :
  ∃ C : ℝ, 0 < C ∧
    meanPairVariance_smooth p N ≤
      C * (1 + |R_smooth p N|) * N ^ 2 / (Real.log N) ^ 4 := by
  exact meanPairVariance_smooth_bound p N hN

/-- Theorem B: global mean pair variance bound.
    Proof uses Bridge 6b (ℕ exponent) to avoid rpow fragility. -/
theorem theorem_B
  (p : MT1Params) (N : ℝ)
  (hN : N ≥ Real.exp (Real.exp (Real.exp 1))) :
  ∃ C : ℝ, 0 < C ∧
    meanPairVariance p N ≤
      C * (1 + |R_smooth p N|) * N ^ 2 / (Real.log N) ^ (4 : ℕ) := by
  -- N ≥ 4 from hN via explicit monotone chain
  have hN4 : N ≥ 4 := by
    have he1 : Real.exp 1 ≥ 2 := by linarith [Real.add_one_le_exp 1]
    have he2 : Real.exp 2 ≥ 4 := by
      have : Real.exp 2 = Real.exp 1 * Real.exp 1 := by
        rw [← Real.exp_add]; ring_nf
      nlinarith
    have h1e : (1 : ℝ) ≤ Real.exp 1 := by linarith
    have he3 : Real.exp 1 ≤ Real.exp (Real.exp 1) :=
      Real.exp_le_exp.mpr h1e
    have he4 : Real.exp (Real.exp 1) ≤ Real.exp (Real.exp (Real.exp 1)) :=
      Real.exp_le_exp.mpr he3
    linarith
  -- Get bounds from bridges (both use ℕ exponent 4, no rpow)
  obtain ⟨C₁, hC₁, h₁⟩ := meanPairVariance_rough_bound_base p N hN4
  obtain ⟨C₂, hC₂, h₂⟩ := meanPairVariance_smooth_bound p N hN4
  -- Witness: C = C₁ + C₂
  refine ⟨C₁ + C₂, by linarith, ?_⟩
  -- Split and combine
  rw [meanPairVariance_split p N]
  have h1R : 1 ≤ 1 + |R_smooth p N| := by linarith [abs_nonneg (R_smooth p N)]
  -- Weaken rough: C₁ * N²/log⁴ ≤ C₁ * (1+|R|) * N²/log⁴ since 1+|R| ≥ 1
  have h₁' : C₁ * N ^ 2 / (Real.log N) ^ (4 : ℕ) ≤
      C₁ * (1 + |R_smooth p N|) * N ^ 2 / (Real.log N) ^ (4 : ℕ) := by
    apply div_le_div_of_nonneg_right _ (by positivity)
    nlinarith
  -- Combine: smooth ≤ C₂(1+|R|)N²/log⁴ and rough ≤ C₁(1+|R|)N²/log⁴
  calc meanPairVariance_smooth p N + meanPairVariance_rough p N
      ≤ C₂ * (1 + |R_smooth p N|) * N ^ 2 / (Real.log N) ^ (4 : ℕ) +
        C₁ * (1 + |R_smooth p N|) * N ^ 2 / (Real.log N) ^ (4 : ℕ) :=
        add_le_add h₂ (le_trans h₁ h₁')
    _ = (C₁ + C₂) * (1 + |R_smooth p N|) * N ^ 2 / (Real.log N) ^ (4 : ℕ) := by ring

/-- Cauchy–Schwarz transfer: direct from Bridge 8. -/
theorem cauchy_schwarz_transfer
  (p : MT1Params) (N : ℝ)
  (hN : N ≥ 4) :
  ∃ C : ℝ, 0 < C ∧
    clusterCount p N ≤
      C * (
        N ^ 2 / (Q_of p N * (Real.log N) ^ 2) +
        X_of p N * Real.sqrt (meanPairVariance p N)
      ) := by
  exact clusterCount_variance_transfer p N hN

-- ============================================================
-- Epistemic Ledger
-- ============================================================

inductive EpistemicStatus
  | ProofClosed    -- fully proved from bridges
  | BridgeDirect   -- 1-line exact from bridge
  | Open           -- not yet established
  deriving Repr

structure LedgerEntry where
  name   : String
  status : EpistemicStatus
  file   : String

def ledger : List LedgerEntry := [
  ⟨"smooth_control",           .BridgeDirect, "MT1"⟩,
  ⟨"rough_control",            .BridgeDirect, "MT1"⟩,
  ⟨"main_theorem",             .ProofClosed,  "MT1"⟩,
  ⟨"below_safety_threshold",   .BridgeDirect, "MT1"⟩,
  ⟨"pcb_with_smooth_control",  .BridgeDirect, "MT1"⟩,
  ⟨"theorem_A",                .BridgeDirect, "MT2"⟩,
  ⟨"rough_variance",           .BridgeDirect, "MT2"⟩,
  ⟨"smooth_variance",          .BridgeDirect, "MT2"⟩,
  ⟨"theorem_B",                .ProofClosed,  "MT2"⟩,
  ⟨"cauchy_schwarz_transfer",  .BridgeDirect, "MT2"⟩,
  ⟨"Q¹ → Q²",                 .Open,         "MT3"⟩,
]

end HorizonMT
