import Mathlib.Tactic
import TS.Goldbach.Strong.TS181.ExplicitFormulaTraceBlueprint
import TS.Goldbach.Strong.TS184.TriangleSplineVonMangoldtAPIProbe
import TS.Goldbach.Strong.TS204.FinalAnalyticInputsSpecification

namespace TS206
namespace Goldbach

/-!
# TS206 - Explicit Formula Effective Statement

TS204 named the final effective explicit-formula input contract for the
triangle-spline weight.  TS206 makes that Wall 2 target concrete by specifying
the objects and propositions that the future proof must satisfy.

The left-hand side is the already-stabilized TS184 smoothed von Mangoldt sum
with the discrete triangle-spline weight.  The right-hand side is packaged as a
main term, a nontrivial-zero contribution, and a residual term, together with
effective bounds controlled by an explicit constants package.

This sprint defines statements only.  It does not prove the explicit formula,
the main term, zero bounds, residual bounds, compatibility with TS181, any OTSA
input slot, or Goldbach.
-/

/--
Right-hand data for a triangle-spline explicit formula at scale `X`.

The actual zero sum and residual terms remain future analytic objects.  TS206
only fixes the shape they must have in the final statement.
-/
structure TriangleSplineExplicitFormulaData
    (X : Nat) where
  mainTerm :
    Real

  zeroContribution :
    Real

  residualTerm :
    Real

/--
Effective constants for the triangle-spline explicit formula target.

`mainTermModel` is deliberately a field rather than being hard-coded as
`X / 2` or `X`.  The exact normalization belongs to the future effective
explicit-formula proof.
-/
structure TriangleSplineExplicitFormulaConstants where
  mainTermModel :
    Nat -> Real

  zeroConstant :
    Real

  zeroScalePower :
    Nat

  zeroLogPower :
    Nat

  residualConstant :
    Real

  residualScalePower :
    Nat

  residualLogPower :
    Nat

  lowerScale :
    Nat

/-- The smoothed von Mangoldt sum that appears on the explicit-formula left side. -/
noncomputable def triangleSplineExplicitFormulaLeftSide
    (X : Nat) :
    Real :=
  TS184.Goldbach.triangleSplineMathlibVonMangoldtWeightedSum X

/-- Formal identity statement for the effective explicit formula. -/
def triangleSplineExplicitFormulaIdentity
    (X : Nat)
    (D : TriangleSplineExplicitFormulaData X) :
    Prop :=
  triangleSplineExplicitFormulaLeftSide X =
    D.mainTerm - D.zeroContribution + D.residualTerm

/-- Main-term identification against the normalization model carried by `K`. -/
def triangleSplineExplicitFormulaMainTermIdentification
    (K : TriangleSplineExplicitFormulaConstants)
    (X : Nat)
    (D : TriangleSplineExplicitFormulaData X) :
    Prop :=
  D.mainTerm = K.mainTermModel X

/-- Effective zero-contribution bound for the explicit-formula target. -/
def triangleSplineExplicitFormulaZeroContributionBound
    (K : TriangleSplineExplicitFormulaConstants)
    (X : Nat)
    (D : TriangleSplineExplicitFormulaData X) :
    Prop :=
  |D.zeroContribution| <=
    K.zeroConstant *
      ((X : Real) ^ K.zeroScalePower) *
        ((Real.log (X : Real)) ^ K.zeroLogPower)

/-- Effective residual bound for the explicit-formula target. -/
def triangleSplineExplicitFormulaResidualBound
    (K : TriangleSplineExplicitFormulaConstants)
    (X : Nat)
    (D : TriangleSplineExplicitFormulaData X) :
    Prop :=
  |D.residualTerm| <=
    K.residualConstant *
      ((X : Real) ^ K.residualScalePower) *
        ((Real.log (X : Real)) ^ K.residualLogPower)

/-- Basic admissibility conditions for an effective constants package. -/
def triangleSplineExplicitFormulaConstantsAdmissible
    (K : TriangleSplineExplicitFormulaConstants) :
    Prop :=
  0 <= K.zeroConstant /\
    0 <= K.residualConstant /\
      0 < K.lowerScale

/--
Compatibility target with the TS181 explicit-formula blueprint.

This is intentionally an unproved proposition, not `True`: future evidence must
connect the concrete TS206 statements back to the TS181/TS95 trace blueprint.
-/
def TriangleSplineExplicitFormulaTS181CompatibilityStatement : Prop :=
  Nonempty TS181.Goldbach.TriangleSplineExplicitFormulaContracts

/-- Existence of right-hand explicit-formula data at a given scale. -/
def triangleSplineExplicitFormulaDataExists
    (X : Nat) :
    Prop :=
  Nonempty (TriangleSplineExplicitFormulaData X)

/--
Concrete TS204 effective explicit-formula contract generated by constants `K`.

This is a contract instance only.  It does not provide evidence for any field.
-/
noncomputable def triangleSplineExplicitFormulaEffectiveContract
    (K : TriangleSplineExplicitFormulaConstants) :
    TS204.Goldbach.TriangleSplineExplicitFormulaEffectiveInputContract where
  explicit_formula_identity_statement :=
    forall X : Nat,
      0 < X ->
        K.lowerScale <= X ->
          exists D : TriangleSplineExplicitFormulaData X,
            triangleSplineExplicitFormulaIdentity X D

  main_term_identification_statement :=
    forall X : Nat,
      0 < X ->
        K.lowerScale <= X ->
          forall D : TriangleSplineExplicitFormulaData X,
            triangleSplineExplicitFormulaIdentity X D ->
              triangleSplineExplicitFormulaMainTermIdentification K X D

  zero_contribution_bound_statement :=
    forall X : Nat,
      0 < X ->
        K.lowerScale <= X ->
          forall D : TriangleSplineExplicitFormulaData X,
            triangleSplineExplicitFormulaIdentity X D ->
              triangleSplineExplicitFormulaMainTermIdentification K X D ->
                triangleSplineExplicitFormulaZeroContributionBound K X D

  residual_bound_statement :=
    forall X : Nat,
      0 < X ->
        K.lowerScale <= X ->
          forall D : TriangleSplineExplicitFormulaData X,
            triangleSplineExplicitFormulaIdentity X D ->
              triangleSplineExplicitFormulaMainTermIdentification K X D ->
                triangleSplineExplicitFormulaResidualBound K X D

  effective_constants_statement :=
    triangleSplineExplicitFormulaConstantsAdmissible K

  compatibility_with_ts181_blueprint_statement :=
    TriangleSplineExplicitFormulaTS181CompatibilityStatement

/-- Ledger recording the concrete TS206 effective explicit-formula statement. -/
structure ExplicitFormulaEffectiveStatementLedger where
  ts204_specification :
    TS204.Goldbach.FinalAnalyticInputsSpecificationLedger

  left_side :
    Nat -> Real

  left_side_eq :
    left_side = triangleSplineExplicitFormulaLeftSide

  data_type_defined :
    True

  constants_type_defined :
    True

  identity_statement_defined :
    True

  main_term_statement_defined :
    True

  zero_bound_statement_defined :
    True

  residual_bound_statement_defined :
    True

  compatibility_statement_defined :
    True

  contract_family :
    TriangleSplineExplicitFormulaConstants ->
      TS204.Goldbach.TriangleSplineExplicitFormulaEffectiveInputContract

  contract_family_eq :
    contract_family = triangleSplineExplicitFormulaEffectiveContract

  explicit_formula_not_proved :
    True

  main_term_not_proved :
    True

  zero_bound_not_proved :
    True

  residual_bound_not_proved :
    True

  ts204_evidence_not_populated :
    True

  otsa_inputs_not_proved :
    True

  goldbach_not_claimed :
    True

/-- Concrete TS206 explicit-formula statement ledger. -/
noncomputable def explicitFormulaEffectiveStatementLedger :
    ExplicitFormulaEffectiveStatementLedger where
  ts204_specification :=
    TS204.Goldbach.finalAnalyticInputsSpecificationLedger
  left_side :=
    triangleSplineExplicitFormulaLeftSide
  left_side_eq :=
    rfl
  data_type_defined := True.intro
  constants_type_defined := True.intro
  identity_statement_defined := True.intro
  main_term_statement_defined := True.intro
  zero_bound_statement_defined := True.intro
  residual_bound_statement_defined := True.intro
  compatibility_statement_defined := True.intro
  contract_family :=
    triangleSplineExplicitFormulaEffectiveContract
  contract_family_eq :=
    rfl
  explicit_formula_not_proved := True.intro
  main_term_not_proved := True.intro
  zero_bound_not_proved := True.intro
  residual_bound_not_proved := True.intro
  ts204_evidence_not_populated := True.intro
  otsa_inputs_not_proved := True.intro
  goldbach_not_claimed := True.intro

/-- Target proposition for TS206. -/
def ExplicitFormulaEffectiveStatementTarget : Prop :=
  Nonempty ExplicitFormulaEffectiveStatementLedger

/-- The TS206 effective explicit-formula statement target is populated. -/
theorem explicitFormulaEffectiveStatementTarget :
    ExplicitFormulaEffectiveStatementTarget :=
  Nonempty.intro explicitFormulaEffectiveStatementLedger

end Goldbach
end TS206
