/-
  Goldbach/PrimeLogEnclosures.lean
  1229 theorems proving log(p) enclosures for all primes p ≤ 9973.

  For each prime p, we prove:
    ⌊log(p)·10⁹⌋/10⁹ < log(p) < (⌊log(p)·10⁹⌋+1)/10⁹

  Strategy:
  - Hi-side (p < exp(hi)): via S_n(hi) ≤ exp(hi) [Mathlib: sum_le_exp_of_nonneg]
    then p < S_n(hi) [by norm_num after Finset.sum unfolding].
  - Lo-side (exp(lo) < p): via exp(lo) ≤ S_n(lo) + tail [ExpBounds]
    then S_n(lo) + tail < p [by norm_num].

  Sorry count: 0

  Generated by generate_prime_enclosures_v4.py
-/
import Goldbach.ExpBounds
import Goldbach.A2CertificateData
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Analysis.SpecialFunctions.Exp
import Mathlib.Data.Real.Basic
import Mathlib.Tactic

namespace Goldbach

open Finset Real BigOperators

/-! ## Individual prime log enclosures

Each theorem has the form:
  `lo/10^9 < log(p) < hi/10^9`
proved via the master combinator `log_enclosure_of_exp_bounds`.
-/

/-- log(9059) ∈ (9111514017/10⁹, 9111514018/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9059 :
    (9111514017 : ℝ) / 10^9 < Real.log 9059 ∧
    Real.log 9059 < (9111514018 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9059) ?_ ?_
  · -- exp(9111514017/10^9) < 9059: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9059 < exp(9111514018/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9067) ∈ (9112396727/10⁹, 9112396728/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9067 :
    (9112396727 : ℝ) / 10^9 < Real.log 9067 ∧
    Real.log 9067 < (9112396728 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9067) ?_ ?_
  · -- exp(9112396727/10^9) < 9067: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9067 < exp(9112396728/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9091) ∈ (9115040192/10⁹, 9115040193/10⁹). n_hi=33, n_lo=31 -/
theorem log_enc_9091 :
    (9115040192 : ℝ) / 10^9 < Real.log 9091 ∧
    Real.log 9091 < (9115040193 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9091) ?_ ?_
  · -- exp(9115040192/10^9) < 9091: use 31 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 31) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9091 < exp(9115040193/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9103) ∈ (9116359308/10⁹, 9116359309/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9103 :
    (9116359308 : ℝ) / 10^9 < Real.log 9103 ∧
    Real.log 9103 < (9116359309 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9103) ?_ ?_
  · -- exp(9116359308/10^9) < 9103: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9103 < exp(9116359309/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9109) ∈ (9117018214/10⁹, 9117018215/10⁹). n_hi=34, n_lo=29 -/
theorem log_enc_9109 :
    (9117018214 : ℝ) / 10^9 < Real.log 9109 ∧
    Real.log 9109 < (9117018215 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9109) ?_ ?_
  · -- exp(9117018214/10^9) < 9109: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9109 < exp(9117018215/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9127) ∈ (9118992332/10⁹, 9118992333/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9127 :
    (9118992332 : ℝ) / 10^9 < Real.log 9127 ∧
    Real.log 9127 < (9118992333 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9127) ?_ ?_
  · -- exp(9118992332/10^9) < 9127: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9127 < exp(9118992333/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9133) ∈ (9119649506/10⁹, 9119649507/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9133 :
    (9119649506 : ℝ) / 10^9 < Real.log 9133 ∧
    Real.log 9133 < (9119649507 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9133) ?_ ?_
  · -- exp(9119649506/10^9) < 9133: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9133 < exp(9119649507/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9137) ∈ (9120087382/10⁹, 9120087383/10⁹). n_hi=38, n_lo=29 -/
theorem log_enc_9137 :
    (9120087382 : ℝ) / 10^9 < Real.log 9137 ∧
    Real.log 9137 < (9120087383 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9137) ?_ ?_
  · -- exp(9120087382/10^9) < 9137: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9137 < exp(9120087383/10^9): use 38 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 38) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9151) ∈ (9121618441/10⁹, 9121618442/10⁹). n_hi=35, n_lo=29 -/
theorem log_enc_9151 :
    (9121618441 : ℝ) / 10^9 < Real.log 9151 ∧
    Real.log 9151 < (9121618442 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9151) ?_ ?_
  · -- exp(9121618441/10^9) < 9151: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9151 < exp(9121618442/10^9): use 35 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 35) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9157) ∈ (9122273893/10⁹, 9122273894/10⁹). n_hi=33, n_lo=31 -/
theorem log_enc_9157 :
    (9122273893 : ℝ) / 10^9 < Real.log 9157 ∧
    Real.log 9157 < (9122273894 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9157) ?_ ?_
  · -- exp(9122273893/10^9) < 9157: use 31 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 31) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9157 < exp(9122273894/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9161) ∈ (9122710622/10⁹, 9122710623/10⁹). n_hi=33, n_lo=32 -/
theorem log_enc_9161 :
    (9122710622 : ℝ) / 10^9 < Real.log 9161 ∧
    Real.log 9161 < (9122710623 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9161) ?_ ?_
  · -- exp(9122710622/10^9) < 9161: use 32 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 32) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9161 < exp(9122710623/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9173) ∈ (9124019665/10⁹, 9124019666/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9173 :
    (9124019665 : ℝ) / 10^9 < Real.log 9173 ∧
    Real.log 9173 < (9124019666 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9173) ?_ ?_
  · -- exp(9124019665/10^9) < 9173: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9173 < exp(9124019666/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9181) ∈ (9124891410/10⁹, 9124891411/10⁹). n_hi=33, n_lo=31 -/
theorem log_enc_9181 :
    (9124891410 : ℝ) / 10^9 < Real.log 9181 ∧
    Real.log 9181 < (9124891411 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9181) ?_ ?_
  · -- exp(9124891410/10^9) < 9181: use 31 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 31) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9181 < exp(9124891411/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9187) ∈ (9125544720/10⁹, 9125544721/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9187 :
    (9125544720 : ℝ) / 10^9 < Real.log 9187 ∧
    Real.log 9187 < (9125544721 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9187) ?_ ?_
  · -- exp(9125544720/10^9) < 9187: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9187 < exp(9125544721/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9199) ∈ (9126850061/10⁹, 9126850062/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9199 :
    (9126850061 : ℝ) / 10^9 < Real.log 9199 ∧
    Real.log 9199 < (9126850062 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9199) ?_ ?_
  · -- exp(9126850061/10^9) < 9199: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9199 < exp(9126850062/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9203) ∈ (9127284796/10⁹, 9127284797/10⁹). n_hi=35, n_lo=29 -/
theorem log_enc_9203 :
    (9127284796 : ℝ) / 10^9 < Real.log 9203 ∧
    Real.log 9203 < (9127284797 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9203) ?_ ?_
  · -- exp(9127284796/10^9) < 9203: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9203 < exp(9127284797/10^9): use 35 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 35) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9209) ∈ (9127936545/10⁹, 9127936546/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9209 :
    (9127936545 : ℝ) / 10^9 < Real.log 9209 ∧
    Real.log 9209 < (9127936546 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9209) ?_ ?_
  · -- exp(9127936545/10^9) < 9209: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9209 < exp(9127936546/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9221) ∈ (9129238770/10⁹, 9129238771/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9221 :
    (9129238770 : ℝ) / 10^9 < Real.log 9221 ∧
    Real.log 9221 < (9129238771 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9221) ?_ ?_
  · -- exp(9129238770/10^9) < 9221: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9221 < exp(9129238771/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9227) ∈ (9129889247/10⁹, 9129889248/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9227 :
    (9129889247 : ℝ) / 10^9 < Real.log 9227 ∧
    Real.log 9227 < (9129889248 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9227) ?_ ?_
  · -- exp(9129889247/10^9) < 9227: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9227 < exp(9129889248/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9239) ∈ (9131188933/10⁹, 9131188934/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9239 :
    (9131188933 : ℝ) / 10^9 < Real.log 9239 ∧
    Real.log 9239 < (9131188934 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9239) ?_ ?_
  · -- exp(9131188933/10^9) < 9239: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9239 < exp(9131188934/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9241) ∈ (9131405383/10⁹, 9131405384/10⁹). n_hi=35, n_lo=29 -/
theorem log_enc_9241 :
    (9131405383 : ℝ) / 10^9 < Real.log 9241 ∧
    Real.log 9241 < (9131405384 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9241) ?_ ?_
  · -- exp(9131405383/10^9) < 9241: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9241 < exp(9131405384/10^9): use 35 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 35) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9257) ∈ (9133135301/10⁹, 9133135302/10⁹). n_hi=33, n_lo=31 -/
theorem log_enc_9257 :
    (9133135301 : ℝ) / 10^9 < Real.log 9257 ∧
    Real.log 9257 < (9133135302 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9257) ?_ ?_
  · -- exp(9133135301/10^9) < 9257: use 31 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 31) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9257 < exp(9133135302/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9277) ∈ (9135293497/10⁹, 9135293498/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9277 :
    (9135293497 : ℝ) / 10^9 < Real.log 9277 ∧
    Real.log 9277 < (9135293498 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9277) ?_ ?_
  · -- exp(9135293497/10^9) < 9277: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9277 < exp(9135293498/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9281) ∈ (9135724578/10⁹, 9135724579/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9281 :
    (9135724578 : ℝ) / 10^9 < Real.log 9281 ∧
    Real.log 9281 < (9135724579 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9281) ?_ ?_
  · -- exp(9135724578/10^9) < 9281: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9281 < exp(9135724579/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9283) ∈ (9135940049/10⁹, 9135940050/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9283 :
    (9135940049 : ℝ) / 10^9 < Real.log 9283 ∧
    Real.log 9283 < (9135940050 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9283) ?_ ?_
  · -- exp(9135940049/10^9) < 9283: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9283 < exp(9135940050/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9293) ∈ (9137016707/10⁹, 9137016708/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9293 :
    (9137016707 : ℝ) / 10^9 < Real.log 9293 ∧
    Real.log 9293 < (9137016708 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9293) ?_ ?_
  · -- exp(9137016707/10^9) < 9293: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9293 < exp(9137016708/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9311) ∈ (9138951775/10⁹, 9138951776/10⁹). n_hi=35, n_lo=29 -/
theorem log_enc_9311 :
    (9138951775 : ℝ) / 10^9 < Real.log 9311 ∧
    Real.log 9311 < (9138951776 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9311) ?_ ?_
  · -- exp(9138951775/10^9) < 9311: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9311 < exp(9138951776/10^9): use 35 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 35) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9319) ∈ (9139810605/10⁹, 9139810606/10⁹). n_hi=35, n_lo=29 -/
theorem log_enc_9319 :
    (9139810605 : ℝ) / 10^9 < Real.log 9319 ∧
    Real.log 9319 < (9139810606 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9319) ?_ ?_
  · -- exp(9139810605/10^9) < 9319: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9319 < exp(9139810606/10^9): use 35 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 35) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9323) ∈ (9140239744/10⁹, 9140239745/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9323 :
    (9140239744 : ℝ) / 10^9 < Real.log 9323 ∧
    Real.log 9323 < (9140239745 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9323) ?_ ?_
  · -- exp(9140239744/10^9) < 9323: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9323 < exp(9140239745/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9337) ∈ (9141740280/10⁹, 9141740281/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9337 :
    (9141740280 : ℝ) / 10^9 < Real.log 9337 ∧
    Real.log 9337 < (9141740281 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9337) ?_ ?_
  · -- exp(9141740280/10^9) < 9337: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9337 < exp(9141740281/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9341) ∈ (9142168591/10⁹, 9142168592/10⁹). n_hi=35, n_lo=29 -/
theorem log_enc_9341 :
    (9142168591 : ℝ) / 10^9 < Real.log 9341 ∧
    Real.log 9341 < (9142168592 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9341) ?_ ?_
  · -- exp(9142168591/10^9) < 9341: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9341 < exp(9142168592/10^9): use 35 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 35) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9343) ∈ (9142382678/10⁹, 9142382679/10⁹). n_hi=35, n_lo=29 -/
theorem log_enc_9343 :
    (9142382678 : ℝ) / 10^9 < Real.log 9343 ∧
    Real.log 9343 < (9142382679 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9343) ?_ ?_
  · -- exp(9142382678/10^9) < 9343: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9343 < exp(9142382679/10^9): use 35 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 35) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9349) ∈ (9143024664/10⁹, 9143024665/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9349 :
    (9143024664 : ℝ) / 10^9 < Real.log 9349 ∧
    Real.log 9349 < (9143024665 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9349) ?_ ?_
  · -- exp(9143024664/10^9) < 9349: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9349 < exp(9143024665/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9371) ∈ (9145375093/10⁹, 9145375094/10⁹). n_hi=34, n_lo=31 -/
theorem log_enc_9371 :
    (9145375093 : ℝ) / 10^9 < Real.log 9371 ∧
    Real.log 9371 < (9145375094 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9371) ?_ ?_
  · -- exp(9145375093/10^9) < 9371: use 31 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 31) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9371 < exp(9145375094/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

end Goldbach
