/-
  Goldbach/PrimeLogEnclosures.lean
  1229 theorems proving log(p) enclosures for all primes p ≤ 9973.

  For each prime p, we prove:
    ⌊log(p)·10⁹⌋/10⁹ < log(p) < (⌊log(p)·10⁹⌋+1)/10⁹

  Strategy:
  - Hi-side (p < exp(hi)): via S_n(hi) ≤ exp(hi) [Mathlib: sum_le_exp_of_nonneg]
    then p < S_n(hi) [by norm_num after Finset.sum unfolding].
  - Lo-side (exp(lo) < p): via exp(lo) ≤ S_n(lo) + tail [ExpBounds]
    then S_n(lo) + tail < p [by norm_num].

  Sorry count: 0

  Generated by generate_prime_enclosures_v4.py
-/
import Goldbach.ExpBounds
import Goldbach.A2CertificateData
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Analysis.SpecialFunctions.Exp
import Mathlib.Data.Real.Basic
import Mathlib.Tactic

namespace Goldbach

open Finset Real BigOperators

/-! ## Individual prime log enclosures

Each theorem has the form:
  `lo/10^9 < log(p) < hi/10^9`
proved via the master combinator `log_enclosure_of_exp_bounds`.
-/

/-- log(3581) ∈ (8183397369/10⁹, 8183397370/10⁹). n_hi=36, n_lo=27 -/
theorem log_enc_3581 :
    (8183397369 : ℝ) / 10^9 < Real.log 3581 ∧
    Real.log 3581 < (8183397370 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3581) ?_ ?_
  · -- exp(8183397369/10^9) < 3581: use 27 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 27) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3581 < exp(8183397370/10^9): use 36 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 36) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3583) ∈ (8183955717/10⁹, 8183955718/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_3583 :
    (8183955717 : ℝ) / 10^9 < Real.log 3583 ∧
    Real.log 3583 < (8183955718 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3583) ?_ ?_
  · -- exp(8183955717/10^9) < 3583: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3583 < exp(8183955718/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3593) ∈ (8186742787/10⁹, 8186742788/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_3593 :
    (8186742787 : ℝ) / 10^9 < Real.log 3593 ∧
    Real.log 3593 < (8186742788 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3593) ?_ ?_
  · -- exp(8186742787/10^9) < 3593: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3593 < exp(8186742788/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3607) ∈ (8190631680/10⁹, 8190631681/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_3607 :
    (8190631680 : ℝ) / 10^9 < Real.log 3607 ∧
    Real.log 3607 < (8190631681 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3607) ?_ ?_
  · -- exp(8190631680/10^9) < 3607: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3607 < exp(8190631681/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3613) ∈ (8192293731/10⁹, 8192293732/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_3613 :
    (8192293731 : ℝ) / 10^9 < Real.log 3613 ∧
    Real.log 3613 < (8192293732 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3613) ?_ ?_
  · -- exp(8192293731/10^9) < 3613: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3613 < exp(8192293732/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3617) ∈ (8193400231/10⁹, 8193400232/10⁹). n_hi=34, n_lo=27 -/
theorem log_enc_3617 :
    (8193400231 : ℝ) / 10^9 < Real.log 3617 ∧
    Real.log 3617 < (8193400232 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3617) ?_ ?_
  · -- exp(8193400231/10^9) < 3617: use 27 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 27) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3617 < exp(8193400232/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3623) ∈ (8195057690/10⁹, 8195057691/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_3623 :
    (8195057690 : ℝ) / 10^9 < Real.log 3623 ∧
    Real.log 3623 < (8195057691 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3623) ?_ ?_
  · -- exp(8195057690/10^9) < 3623: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3623 < exp(8195057691/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3631) ∈ (8197263371/10⁹, 8197263372/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_3631 :
    (8197263371 : ℝ) / 10^9 < Real.log 3631 ∧
    Real.log 3631 < (8197263372 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3631) ?_ ?_
  · -- exp(8197263371/10^9) < 3631: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3631 < exp(8197263372/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3637) ∈ (8198914444/10⁹, 8198914445/10⁹). n_hi=35, n_lo=27 -/
theorem log_enc_3637 :
    (8198914444 : ℝ) / 10^9 < Real.log 3637 ∧
    Real.log 3637 < (8198914445 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3637) ?_ ?_
  · -- exp(8198914444/10^9) < 3637: use 27 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 27) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3637 < exp(8198914445/10^9): use 35 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 35) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3643) ∈ (8200562797/10⁹, 8200562798/10⁹). n_hi=31, n_lo=31 -/
theorem log_enc_3643 :
    (8200562797 : ℝ) / 10^9 < Real.log 3643 ∧
    Real.log 3643 < (8200562798 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3643) ?_ ?_
  · -- exp(8200562797/10^9) < 3643: use 31 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 31) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3643 < exp(8200562798/10^9): use 31 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 31) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3659) ∈ (8204945165/10⁹, 8204945166/10⁹). n_hi=31, n_lo=30 -/
theorem log_enc_3659 :
    (8204945165 : ℝ) / 10^9 < Real.log 3659 ∧
    Real.log 3659 < (8204945166 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3659) ?_ ?_
  · -- exp(8204945165/10^9) < 3659: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3659 < exp(8204945166/10^9): use 31 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 31) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3671) ∈ (8208219383/10⁹, 8208219384/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_3671 :
    (8208219383 : ℝ) / 10^9 < Real.log 3671 ∧
    Real.log 3671 < (8208219384 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3671) ?_ ?_
  · -- exp(8208219383/10^9) < 3671: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3671 < exp(8208219384/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3673) ∈ (8208764045/10⁹, 8208764046/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_3673 :
    (8208764045 : ℝ) / 10^9 < Real.log 3673 ∧
    Real.log 3673 < (8208764046 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3673) ?_ ?_
  · -- exp(8208764045/10^9) < 3673: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3673 < exp(8208764046/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3677) ∈ (8209852481/10⁹, 8209852482/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_3677 :
    (8209852481 : ℝ) / 10^9 < Real.log 3677 ∧
    Real.log 3677 < (8209852482 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3677) ?_ ?_
  · -- exp(8209852481/10^9) < 3677: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3677 < exp(8209852482/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3691) ∈ (8213652703/10⁹, 8213652704/10⁹). n_hi=32, n_lo=30 -/
theorem log_enc_3691 :
    (8213652703 : ℝ) / 10^9 < Real.log 3691 ∧
    Real.log 3691 < (8213652704 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3691) ?_ ?_
  · -- exp(8213652703/10^9) < 3691: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3691 < exp(8213652704/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3697) ∈ (8215276958/10⁹, 8215276959/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_3697 :
    (8215276958 : ℝ) / 10^9 < Real.log 3697 ∧
    Real.log 3697 < (8215276959 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3697) ?_ ?_
  · -- exp(8215276958/10^9) < 3697: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3697 < exp(8215276959/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3701) ∈ (8216358332/10⁹, 8216358333/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_3701 :
    (8216358332 : ℝ) / 10^9 < Real.log 3701 ∧
    Real.log 3701 < (8216358333 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3701) ?_ ?_
  · -- exp(8216358332/10^9) < 3701: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3701 < exp(8216358333/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3709) ∈ (8218517577/10⁹, 8218517578/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_3709 :
    (8218517577 : ℝ) / 10^9 < Real.log 3709 ∧
    Real.log 3709 < (8218517578 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3709) ?_ ?_
  · -- exp(8218517577/10^9) < 3709: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3709 < exp(8218517578/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3719) ∈ (8221210093/10⁹, 8221210094/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_3719 :
    (8221210093 : ℝ) / 10^9 < Real.log 3719 ∧
    Real.log 3719 < (8221210094 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3719) ?_ ?_
  · -- exp(8221210093/10^9) < 3719: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3719 < exp(8221210094/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3727) ∈ (8223358899/10⁹, 8223358900/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_3727 :
    (8223358899 : ℝ) / 10^9 < Real.log 3727 ∧
    Real.log 3727 < (8223358900 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3727) ?_ ?_
  · -- exp(8223358899/10^9) < 3727: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3727 < exp(8223358900/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3733) ∈ (8224967478/10⁹, 8224967479/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_3733 :
    (8224967478 : ℝ) / 10^9 < Real.log 3733 ∧
    Real.log 3733 < (8224967479 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3733) ?_ ?_
  · -- exp(8224967478/10^9) < 3733: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3733 < exp(8224967479/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3739) ∈ (8226573474/10⁹, 8226573475/10⁹). n_hi=34, n_lo=28 -/
theorem log_enc_3739 :
    (8226573474 : ℝ) / 10^9 < Real.log 3739 ∧
    Real.log 3739 < (8226573475 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3739) ?_ ?_
  · -- exp(8226573474/10^9) < 3739: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3739 < exp(8226573475/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3761) ∈ (8232440158/10⁹, 8232440159/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_3761 :
    (8232440158 : ℝ) / 10^9 < Real.log 3761 ∧
    Real.log 3761 < (8232440159 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3761) ?_ ?_
  · -- exp(8232440158/10^9) < 3761: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3761 < exp(8232440159/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3767) ∈ (8234034207/10⁹, 8234034208/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_3767 :
    (8234034207 : ℝ) / 10^9 < Real.log 3767 ∧
    Real.log 3767 < (8234034208 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3767) ?_ ?_
  · -- exp(8234034207/10^9) < 3767: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3767 < exp(8234034208/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3769) ∈ (8234564993/10⁹, 8234564994/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_3769 :
    (8234564993 : ℝ) / 10^9 < Real.log 3769 ∧
    Real.log 3769 < (8234564994 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3769) ?_ ?_
  · -- exp(8234564993/10^9) < 3769: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3769 < exp(8234564994/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3779) ∈ (8237214703/10⁹, 8237214704/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_3779 :
    (8237214703 : ℝ) / 10^9 < Real.log 3779 ∧
    Real.log 3779 < (8237214704 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3779) ?_ ?_
  · -- exp(8237214703/10^9) < 3779: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3779 < exp(8237214704/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3793) ∈ (8240912541/10⁹, 8240912542/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_3793 :
    (8240912541 : ℝ) / 10^9 < Real.log 3793 ∧
    Real.log 3793 < (8240912542 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3793) ?_ ?_
  · -- exp(8240912541/10^9) < 3793: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3793 < exp(8240912542/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3797) ∈ (8241966560/10⁹, 8241966561/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_3797 :
    (8241966560 : ℝ) / 10^9 < Real.log 3797 ∧
    Real.log 3797 < (8241966561 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3797) ?_ ?_
  · -- exp(8241966560/10^9) < 3797: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3797 < exp(8241966561/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3803) ∈ (8243545507/10⁹, 8243545508/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_3803 :
    (8243545507 : ℝ) / 10^9 < Real.log 3803 ∧
    Real.log 3803 < (8243545508 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3803) ?_ ?_
  · -- exp(8243545507/10^9) < 3803: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3803 < exp(8243545508/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3821) ∈ (8248267447/10⁹, 8248267448/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_3821 :
    (8248267447 : ℝ) / 10^9 < Real.log 3821 ∧
    Real.log 3821 < (8248267448 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3821) ?_ ?_
  · -- exp(8248267447/10^9) < 3821: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3821 < exp(8248267448/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3823) ∈ (8248790733/10⁹, 8248790734/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_3823 :
    (8248790733 : ℝ) / 10^9 < Real.log 3823 ∧
    Real.log 3823 < (8248790734 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3823) ?_ ?_
  · -- exp(8248790733/10^9) < 3823: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3823 < exp(8248790734/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3833) ∈ (8251403065/10⁹, 8251403066/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_3833 :
    (8251403065 : ℝ) / 10^9 < Real.log 3833 ∧
    Real.log 3833 < (8251403066 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3833) ?_ ?_
  · -- exp(8251403065/10^9) < 3833: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3833 < exp(8251403066/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3847) ∈ (8255048902/10⁹, 8255048903/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_3847 :
    (8255048902 : ℝ) / 10^9 < Real.log 3847 ∧
    Real.log 3847 < (8255048903 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3847) ?_ ?_
  · -- exp(8255048902/10^9) < 3847: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3847 < exp(8255048903/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3851) ∈ (8256088133/10⁹, 8256088134/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_3851 :
    (8256088133 : ℝ) / 10^9 < Real.log 3851 ∧
    Real.log 3851 < (8256088134 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3851) ?_ ?_
  · -- exp(8256088133/10^9) < 3851: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3851 < exp(8256088134/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3853) ∈ (8256607344/10⁹, 8256607345/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_3853 :
    (8256607344 : ℝ) / 10^9 < Real.log 3853 ∧
    Real.log 3853 < (8256607345 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3853) ?_ ?_
  · -- exp(8256607344/10^9) < 3853: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3853 < exp(8256607345/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3863) ∈ (8259199362/10⁹, 8259199363/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_3863 :
    (8259199362 : ℝ) / 10^9 < Real.log 3863 ∧
    Real.log 3863 < (8259199363 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3863) ?_ ?_
  · -- exp(8259199362/10^9) < 3863: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3863 < exp(8259199363/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3877) ∈ (8262816937/10⁹, 8262816938/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_3877 :
    (8262816937 : ℝ) / 10^9 < Real.log 3877 ∧
    Real.log 3877 < (8262816938 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3877) ?_ ?_
  · -- exp(8262816937/10^9) < 3877: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3877 < exp(8262816938/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3881) ∈ (8263848131/10⁹, 8263848132/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_3881 :
    (8263848131 : ℝ) / 10^9 < Real.log 3881 ∧
    Real.log 3881 < (8263848132 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3881) ?_ ?_
  · -- exp(8263848131/10^9) < 3881: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3881 < exp(8263848132/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3889) ∈ (8265907334/10⁹, 8265907335/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_3889 :
    (8265907334 : ℝ) / 10^9 < Real.log 3889 ∧
    Real.log 3889 < (8265907335 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3889) ?_ ?_
  · -- exp(8265907334/10^9) < 3889: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3889 < exp(8265907335/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3907) ∈ (8270525095/10⁹, 8270525096/10⁹). n_hi=32, n_lo=30 -/
theorem log_enc_3907 :
    (8270525095 : ℝ) / 10^9 < Real.log 3907 ∧
    Real.log 3907 < (8270525096 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3907) ?_ ?_
  · -- exp(8270525095/10^9) < 3907: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3907 < exp(8270525096/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3911) ∈ (8271548374/10⁹, 8271548375/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_3911 :
    (8271548374 : ℝ) / 10^9 < Real.log 3911 ∧
    Real.log 3911 < (8271548375 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3911) ?_ ?_
  · -- exp(8271548374/10^9) < 3911: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3911 < exp(8271548375/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3917) ∈ (8273081333/10⁹, 8273081334/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_3917 :
    (8273081333 : ℝ) / 10^9 < Real.log 3917 ∧
    Real.log 3917 < (8273081334 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3917) ?_ ?_
  · -- exp(8273081333/10^9) < 3917: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3917 < exp(8273081334/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3919) ∈ (8273591798/10⁹, 8273591799/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_3919 :
    (8273591798 : ℝ) / 10^9 < Real.log 3919 ∧
    Real.log 3919 < (8273591799 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3919) ?_ ?_
  · -- exp(8273591798/10^9) < 3919: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3919 < exp(8273591799/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3923) ∈ (8274611946/10⁹, 8274611947/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_3923 :
    (8274611946 : ℝ) / 10^9 < Real.log 3923 ∧
    Real.log 3923 < (8274611947 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3923) ?_ ?_
  · -- exp(8274611946/10^9) < 3923: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3923 < exp(8274611947/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3929) ∈ (8276140219/10⁹, 8276140220/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_3929 :
    (8276140219 : ℝ) / 10^9 < Real.log 3929 ∧
    Real.log 3929 < (8276140220 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3929) ?_ ?_
  · -- exp(8276140219/10^9) < 3929: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3929 < exp(8276140220/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3931) ∈ (8276649125/10⁹, 8276649126/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_3931 :
    (8276649125 : ℝ) / 10^9 < Real.log 3931 ∧
    Real.log 3931 < (8276649126 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3931) ?_ ?_
  · -- exp(8276649125/10^9) < 3931: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3931 < exp(8276649126/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3943) ∈ (8279697133/10⁹, 8279697134/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_3943 :
    (8279697133 : ℝ) / 10^9 < Real.log 3943 ∧
    Real.log 3943 < (8279697134 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3943) ?_ ?_
  · -- exp(8279697133/10^9) < 3943: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3943 < exp(8279697134/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3947) ∈ (8280711075/10⁹, 8280711076/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_3947 :
    (8280711075 : ℝ) / 10^9 < Real.log 3947 ∧
    Real.log 3947 < (8280711076 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3947) ?_ ?_
  · -- exp(8280711075/10^9) < 3947: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3947 < exp(8280711076/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3967) ∈ (8285765420/10⁹, 8285765421/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_3967 :
    (8285765420 : ℝ) / 10^9 < Real.log 3967 ∧
    Real.log 3967 < (8285765421 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3967) ?_ ?_
  · -- exp(8285765420/10^9) < 3967: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3967 < exp(8285765421/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3989) ∈ (8291295851/10⁹, 8291295852/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_3989 :
    (8291295851 : ℝ) / 10^9 < Real.log 3989 ∧
    Real.log 3989 < (8291295852 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3989) ?_ ?_
  · -- exp(8291295851/10^9) < 3989: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3989 < exp(8291295852/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4001) ∈ (8294299608/10⁹, 8294299609/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4001 :
    (8294299608 : ℝ) / 10^9 < Real.log 4001 ∧
    Real.log 4001 < (8294299609 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4001) ?_ ?_
  · -- exp(8294299608/10^9) < 4001: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4001 < exp(8294299609/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4003) ∈ (8294799358/10⁹, 8294799359/10⁹). n_hi=35, n_lo=28 -/
theorem log_enc_4003 :
    (8294799358 : ℝ) / 10^9 < Real.log 4003 ∧
    Real.log 4003 < (8294799359 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4003) ?_ ?_
  · -- exp(8294799358/10^9) < 4003: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4003 < exp(8294799359/10^9): use 35 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 35) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4007) ∈ (8295798110/10⁹, 8295798111/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_4007 :
    (8295798110 : ℝ) / 10^9 < Real.log 4007 ∧
    Real.log 4007 < (8295798111 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4007) ?_ ?_
  · -- exp(8295798110/10^9) < 4007: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4007 < exp(8295798111/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4013) ∈ (8297294370/10⁹, 8297294371/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4013 :
    (8297294370 : ℝ) / 10^9 < Real.log 4013 ∧
    Real.log 4013 < (8297294371 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4013) ?_ ?_
  · -- exp(8297294370/10^9) < 4013: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4013 < exp(8297294371/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4019) ∈ (8298788394/10⁹, 8298788395/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_4019 :
    (8298788394 : ℝ) / 10^9 < Real.log 4019 ∧
    Real.log 4019 < (8298788395 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4019) ?_ ?_
  · -- exp(8298788394/10^9) < 4019: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4019 < exp(8298788395/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4021) ∈ (8299285906/10⁹, 8299285907/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4021 :
    (8299285906 : ℝ) / 10^9 < Real.log 4021 ∧
    Real.log 4021 < (8299285907 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4021) ?_ ?_
  · -- exp(8299285906/10^9) < 4021: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4021 < exp(8299285907/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4027) ∈ (8300776960/10⁹, 8300776961/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4027 :
    (8300776960 : ℝ) / 10^9 < Real.log 4027 ∧
    Real.log 4027 < (8300776961 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4027) ?_ ?_
  · -- exp(8300776960/10^9) < 4027: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4027 < exp(8300776961/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4049) ∈ (8306225216/10⁹, 8306225217/10⁹). n_hi=32, n_lo=30 -/
theorem log_enc_4049 :
    (8306225216 : ℝ) / 10^9 < Real.log 4049 ∧
    Real.log 4049 < (8306225217 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4049) ?_ ?_
  · -- exp(8306225216/10^9) < 4049: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4049 < exp(8306225217/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4051) ∈ (8306719043/10⁹, 8306719044/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4051 :
    (8306719043 : ℝ) / 10^9 < Real.log 4051 ∧
    Real.log 4051 < (8306719044 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4051) ?_ ?_
  · -- exp(8306719043/10^9) < 4051: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4051 < exp(8306719044/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4057) ∈ (8308199063/10⁹, 8308199064/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4057 :
    (8308199063 : ℝ) / 10^9 < Real.log 4057 ∧
    Real.log 4057 < (8308199064 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4057) ?_ ?_
  · -- exp(8308199063/10^9) < 4057: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4057 < exp(8308199064/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4073) ∈ (8312135107/10⁹, 8312135108/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_4073 :
    (8312135107 : ℝ) / 10^9 < Real.log 4073 ∧
    Real.log 4073 < (8312135108 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4073) ?_ ?_
  · -- exp(8312135107/10^9) < 4073: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4073 < exp(8312135108/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4079) ∈ (8313607139/10⁹, 8313607140/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4079 :
    (8313607139 : ℝ) / 10^9 < Real.log 4079 ∧
    Real.log 4079 < (8313607140 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4079) ?_ ?_
  · -- exp(8313607139/10^9) < 4079: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4079 < exp(8313607140/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4091) ∈ (8316544717/10⁹, 8316544718/10⁹). n_hi=34, n_lo=28 -/
theorem log_enc_4091 :
    (8316544717 : ℝ) / 10^9 < Real.log 4091 ∧
    Real.log 4091 < (8316544718 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4091) ?_ ?_
  · -- exp(8316544717/10^9) < 4091: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4091 < exp(8316544718/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4093) ∈ (8317033476/10⁹, 8317033477/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_4093 :
    (8317033476 : ℝ) / 10^9 < Real.log 4093 ∧
    Real.log 4093 < (8317033477 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4093) ?_ ?_
  · -- exp(8317033476/10^9) < 4093: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4093 < exp(8317033477/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4099) ∈ (8318498320/10⁹, 8318498321/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_4099 :
    (8318498320 : ℝ) / 10^9 < Real.log 4099 ∧
    Real.log 4099 < (8318498321 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4099) ?_ ?_
  · -- exp(8318498320/10^9) < 4099: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4099 < exp(8318498321/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4111) ∈ (8321421586/10⁹, 8321421587/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4111 :
    (8321421586 : ℝ) / 10^9 < Real.log 4111 ∧
    Real.log 4111 < (8321421587 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4111) ?_ ?_
  · -- exp(8321421586/10^9) < 4111: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4111 < exp(8321421587/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4127) ∈ (8325306029/10⁹, 8325306030/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4127 :
    (8325306029 : ℝ) / 10^9 < Real.log 4127 ∧
    Real.log 4127 < (8325306030 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4127) ?_ ?_
  · -- exp(8325306029/10^9) < 4127: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4127 < exp(8325306030/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4129) ∈ (8325790525/10⁹, 8325790526/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4129 :
    (8325790525 : ℝ) / 10^9 < Real.log 4129 ∧
    Real.log 4129 < (8325790526 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4129) ?_ ?_
  · -- exp(8325790525/10^9) < 4129: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4129 < exp(8325790526/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4133) ∈ (8326758814/10⁹, 8326758815/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_4133 :
    (8326758814 : ℝ) / 10^9 < Real.log 4133 ∧
    Real.log 4133 < (8326758815 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4133) ?_ ?_
  · -- exp(8326758814/10^9) < 4133: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4133 < exp(8326758815/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4139) ∈ (8328209491/10⁹, 8328209492/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4139 :
    (8328209491 : ℝ) / 10^9 < Real.log 4139 ∧
    Real.log 4139 < (8328209492 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4139) ?_ ?_
  · -- exp(8328209491/10^9) < 4139: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4139 < exp(8328209492/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4153) ∈ (8331586243/10⁹, 8331586244/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_4153 :
    (8331586243 : ℝ) / 10^9 < Real.log 4153 ∧
    Real.log 4153 < (8331586244 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4153) ?_ ?_
  · -- exp(8331586243/10^9) < 4153: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4153 < exp(8331586244/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4157) ∈ (8332548939/10⁹, 8332548940/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4157 :
    (8332548939 : ℝ) / 10^9 < Real.log 4157 ∧
    Real.log 4157 < (8332548940 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4157) ?_ ?_
  · -- exp(8332548939/10^9) < 4157: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4157 < exp(8332548940/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4159) ∈ (8333029939/10⁹, 8333029940/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4159 :
    (8333029939 : ℝ) / 10^9 < Real.log 4159 ∧
    Real.log 4159 < (8333029940 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4159) ?_ ?_
  · -- exp(8333029939/10^9) < 4159: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4159 < exp(8333029940/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4177) ∈ (8337348564/10⁹, 8337348565/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_4177 :
    (8337348564 : ℝ) / 10^9 < Real.log 4177 ∧
    Real.log 4177 < (8337348565 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4177) ?_ ?_
  · -- exp(8337348564/10^9) < 4177: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4177 < exp(8337348565/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4201) ∈ (8343077871/10⁹, 8343077872/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4201 :
    (8343077871 : ℝ) / 10^9 < Real.log 4201 ∧
    Real.log 4201 < (8343077872 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4201) ?_ ?_
  · -- exp(8343077871/10^9) < 4201: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4201 < exp(8343077872/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4211) ∈ (8345455428/10⁹, 8345455429/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4211 :
    (8345455428 : ℝ) / 10^9 < Real.log 4211 ∧
    Real.log 4211 < (8345455429 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4211) ?_ ?_
  · -- exp(8345455428/10^9) < 4211: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4211 < exp(8345455429/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4217) ∈ (8346879253/10⁹, 8346879254/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4217 :
    (8346879253 : ℝ) / 10^9 < Real.log 4217 ∧
    Real.log 4217 < (8346879254 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4217) ?_ ?_
  · -- exp(8346879253/10^9) < 4217: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4217 < exp(8346879254/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4219) ∈ (8347353412/10⁹, 8347353413/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4219 :
    (8347353412 : ℝ) / 10^9 < Real.log 4219 ∧
    Real.log 4219 < (8347353413 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4219) ?_ ?_
  · -- exp(8347353412/10^9) < 4219: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4219 < exp(8347353413/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4229) ∈ (8349720837/10⁹, 8349720838/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_4229 :
    (8349720837 : ℝ) / 10^9 < Real.log 4229 ∧
    Real.log 4229 < (8349720838 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4229) ?_ ?_
  · -- exp(8349720837/10^9) < 4229: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4229 < exp(8349720838/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4231) ∈ (8350193650/10⁹, 8350193651/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4231 :
    (8350193650 : ℝ) / 10^9 < Real.log 4231 ∧
    Real.log 4231 < (8350193651 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4231) ?_ ?_
  · -- exp(8350193650/10^9) < 4231: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4231 < exp(8350193651/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4241) ∈ (8352554369/10⁹, 8352554370/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_4241 :
    (8352554369 : ℝ) / 10^9 < Real.log 4241 ∧
    Real.log 4241 < (8352554370 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4241) ?_ ?_
  · -- exp(8352554369/10^9) < 4241: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4241 < exp(8352554370/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4243) ∈ (8353025845/10⁹, 8353025846/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4243 :
    (8353025845 : ℝ) / 10^9 < Real.log 4243 ∧
    Real.log 4243 < (8353025846 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4243) ?_ ?_
  · -- exp(8353025845/10^9) < 4243: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4243 < exp(8353025846/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4253) ∈ (8355379895/10⁹, 8355379896/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4253 :
    (8355379895 : ℝ) / 10^9 < Real.log 4253 ∧
    Real.log 4253 < (8355379896 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4253) ?_ ?_
  · -- exp(8355379895/10^9) < 4253: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4253 < exp(8355379896/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4259) ∈ (8356789669/10⁹, 8356789670/10⁹). n_hi=34, n_lo=28 -/
theorem log_enc_4259 :
    (8356789669 : ℝ) / 10^9 < Real.log 4259 ∧
    Real.log 4259 < (8356789670 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4259) ?_ ?_
  · -- exp(8356789669/10^9) < 4259: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4259 < exp(8356789670/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4261) ∈ (8357259153/10⁹, 8357259154/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_4261 :
    (8357259153 : ℝ) / 10^9 < Real.log 4261 ∧
    Real.log 4261 < (8357259154 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4261) ?_ ?_
  · -- exp(8357259153/10^9) < 4261: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4261 < exp(8357259154/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4271) ∈ (8359603270/10⁹, 8359603271/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4271 :
    (8359603270 : ℝ) / 10^9 < Real.log 4271 ∧
    Real.log 4271 < (8359603271 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4271) ?_ ?_
  · -- exp(8359603270/10^9) < 4271: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4271 < exp(8359603271/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4273) ∈ (8360071435/10⁹, 8360071436/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4273 :
    (8360071435 : ℝ) / 10^9 < Real.log 4273 ∧
    Real.log 4273 < (8360071436 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4273) ?_ ?_
  · -- exp(8360071435/10^9) < 4273: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4273 < exp(8360071436/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4283) ∈ (8362408977/10⁹, 8362408978/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4283 :
    (8362408977 : ℝ) / 10^9 < Real.log 4283 ∧
    Real.log 4283 < (8362408978 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4283) ?_ ?_
  · -- exp(8362408977/10^9) < 4283: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4283 < exp(8362408978/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4289) ∈ (8363808884/10⁹, 8363808885/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_4289 :
    (8363808884 : ℝ) / 10^9 < Real.log 4289 ∧
    Real.log 4289 < (8363808885 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4289) ?_ ?_
  · -- exp(8363808884/10^9) < 4289: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4289 < exp(8363808885/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4297) ∈ (8365672383/10⁹, 8365672384/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4297 :
    (8365672383 : ℝ) / 10^9 < Real.log 4297 ∧
    Real.log 4297 < (8365672384 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4297) ?_ ?_
  · -- exp(8365672383/10^9) < 4297: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4297 < exp(8365672384/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4327) ∈ (8372629740/10⁹, 8372629741/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4327 :
    (8372629740 : ℝ) / 10^9 < Real.log 4327 ∧
    Real.log 4327 < (8372629741 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4327) ?_ ?_
  · -- exp(8372629740/10^9) < 4327: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4327 < exp(8372629741/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4337) ∈ (8374938143/10⁹, 8374938144/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4337 :
    (8374938143 : ℝ) / 10^9 < Real.log 4337 ∧
    Real.log 4337 < (8374938144 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4337) ?_ ?_
  · -- exp(8374938143/10^9) < 4337: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4337 < exp(8374938144/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4339) ∈ (8375399185/10⁹, 8375399186/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4339 :
    (8375399185 : ℝ) / 10^9 < Real.log 4339 ∧
    Real.log 4339 < (8375399186 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4339) ?_ ?_
  · -- exp(8375399185/10^9) < 4339: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4339 < exp(8375399186/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4349) ∈ (8377701212/10⁹, 8377701213/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4349 :
    (8377701212 : ℝ) / 10^9 < Real.log 4349 ∧
    Real.log 4349 < (8377701213 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4349) ?_ ?_
  · -- exp(8377701212/10^9) < 4349: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4349 < exp(8377701213/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4357) ∈ (8379539026/10⁹, 8379539027/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4357 :
    (8379539026 : ℝ) / 10^9 < Real.log 4357 ∧
    Real.log 4357 < (8379539027 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4357) ?_ ?_
  · -- exp(8379539026/10^9) < 4357: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4357 < exp(8379539027/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4363) ∈ (8380915173/10⁹, 8380915174/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4363 :
    (8380915173 : ℝ) / 10^9 < Real.log 4363 ∧
    Real.log 4363 < (8380915174 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4363) ?_ ?_
  · -- exp(8380915173/10^9) < 4363: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4363 < exp(8380915174/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4373) ∈ (8383204551/10⁹, 8383204552/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_4373 :
    (8383204551 : ℝ) / 10^9 < Real.log 4373 ∧
    Real.log 4373 < (8383204552 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4373) ?_ ?_
  · -- exp(8383204551/10^9) < 4373: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4373 < exp(8383204552/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4391) ∈ (8387312270/10⁹, 8387312271/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_4391 :
    (8387312270 : ℝ) / 10^9 < Real.log 4391 ∧
    Real.log 4391 < (8387312271 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4391) ?_ ?_
  · -- exp(8387312270/10^9) < 4391: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4391 < exp(8387312271/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4397) ∈ (8388677769/10⁹, 8388677770/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4397 :
    (8388677769 : ℝ) / 10^9 < Real.log 4397 ∧
    Real.log 4397 < (8388677770 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4397) ?_ ?_
  · -- exp(8388677769/10^9) < 4397: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4397 < exp(8388677770/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4409) ∈ (8391403185/10⁹, 8391403186/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4409 :
    (8391403185 : ℝ) / 10^9 < Real.log 4409 ∧
    Real.log 4409 < (8391403186 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4409) ?_ ?_
  · -- exp(8391403185/10^9) < 4409: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4409 < exp(8391403186/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4421) ∈ (8394121193/10⁹, 8394121194/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4421 :
    (8394121193 : ℝ) / 10^9 < Real.log 4421 ∧
    Real.log 4421 < (8394121194 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4421) ?_ ?_
  · -- exp(8394121193/10^9) < 4421: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4421 < exp(8394121194/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4423) ∈ (8394573477/10⁹, 8394573478/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4423 :
    (8394573477 : ℝ) / 10^9 < Real.log 4423 ∧
    Real.log 4423 < (8394573478 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4423) ?_ ?_
  · -- exp(8394573477/10^9) < 4423: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4423 < exp(8394573478/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4441) ∈ (8398634855/10⁹, 8398634856/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4441 :
    (8398634855 : ℝ) / 10^9 < Real.log 4441 ∧
    Real.log 4441 < (8398634856 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4441) ?_ ?_
  · -- exp(8398634855/10^9) < 4441: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4441 < exp(8398634856/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4447) ∈ (8399984990/10⁹, 8399984991/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_4447 :
    (8399984990 : ℝ) / 10^9 < Real.log 4447 ∧
    Real.log 4447 < (8399984991 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4447) ?_ ?_
  · -- exp(8399984990/10^9) < 4447: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4447 < exp(8399984991/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4451) ∈ (8400884069/10⁹, 8400884070/10⁹). n_hi=32, n_lo=31 -/
theorem log_enc_4451 :
    (8400884069 : ℝ) / 10^9 < Real.log 4451 ∧
    Real.log 4451 < (8400884070 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4451) ?_ ?_
  · -- exp(8400884069/10^9) < 4451: use 31 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 31) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4451 < exp(8400884070/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4457) ∈ (8402231172/10⁹, 8402231173/10⁹). n_hi=34, n_lo=28 -/
theorem log_enc_4457 :
    (8402231172 : ℝ) / 10^9 < Real.log 4457 ∧
    Real.log 4457 < (8402231173 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4457) ?_ ?_
  · -- exp(8402231172/10^9) < 4457: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4457 < exp(8402231173/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4463) ∈ (8403576464/10⁹, 8403576465/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4463 :
    (8403576464 : ℝ) / 10^9 < Real.log 4463 ∧
    Real.log 4463 < (8403576465 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4463) ?_ ?_
  · -- exp(8403576464/10^9) < 4463: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4463 < exp(8403576465/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4481) ∈ (8407601514/10⁹, 8407601515/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4481 :
    (8407601514 : ℝ) / 10^9 < Real.log 4481 ∧
    Real.log 4481 < (8407601515 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4481) ?_ ?_
  · -- exp(8407601514/10^9) < 4481: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4481 < exp(8407601515/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4483) ∈ (8408047744/10⁹, 8408047745/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4483 :
    (8408047744 : ℝ) / 10^9 < Real.log 4483 ∧
    Real.log 4483 < (8408047745 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4483) ?_ ?_
  · -- exp(8408047744/10^9) < 4483: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4483 < exp(8408047745/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4493) ∈ (8410275909/10⁹, 8410275910/10⁹). n_hi=32, n_lo=30 -/
theorem log_enc_4493 :
    (8410275909 : ℝ) / 10^9 < Real.log 4493 ∧
    Real.log 4493 < (8410275910 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4493) ?_ ?_
  · -- exp(8410275909/10^9) < 4493: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4493 < exp(8410275910/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4507) ∈ (8413387022/10⁹, 8413387023/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4507 :
    (8413387022 : ℝ) / 10^9 < Real.log 4507 ∧
    Real.log 4507 < (8413387023 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4507) ?_ ?_
  · -- exp(8413387022/10^9) < 4507: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4507 < exp(8413387023/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4513) ∈ (8414717399/10⁹, 8414717400/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4513 :
    (8414717399 : ℝ) / 10^9 < Real.log 4513 ∧
    Real.log 4513 < (8414717400 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4513) ?_ ?_
  · -- exp(8414717399/10^9) < 4513: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4513 < exp(8414717400/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4517) ∈ (8415603335/10⁹, 8415603336/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4517 :
    (8415603335 : ℝ) / 10^9 < Real.log 4517 ∧
    Real.log 4517 < (8415603336 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4517) ?_ ?_
  · -- exp(8415603335/10^9) < 4517: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4517 < exp(8415603336/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4519) ∈ (8416046009/10⁹, 8416046010/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4519 :
    (8416046009 : ℝ) / 10^9 < Real.log 4519 ∧
    Real.log 4519 < (8416046010 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4519) ?_ ?_
  · -- exp(8416046009/10^9) < 4519: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4519 < exp(8416046010/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4523) ∈ (8416930769/10⁹, 8416930770/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_4523 :
    (8416930769 : ℝ) / 10^9 < Real.log 4523 ∧
    Real.log 4523 < (8416930770 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4523) ?_ ?_
  · -- exp(8416930769/10^9) < 4523: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4523 < exp(8416930770/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4547) ∈ (8422222953/10⁹, 8422222954/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4547 :
    (8422222953 : ℝ) / 10^9 < Real.log 4547 ∧
    Real.log 4547 < (8422222954 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4547) ?_ ?_
  · -- exp(8422222953/10^9) < 4547: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4547 < exp(8422222954/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4549) ∈ (8422662707/10⁹, 8422662708/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4549 :
    (8422662707 : ℝ) / 10^9 < Real.log 4549 ∧
    Real.log 4549 < (8422662708 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4549) ?_ ?_
  · -- exp(8422662707/10^9) < 4549: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4549 < exp(8422662708/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4561) ∈ (8425297176/10⁹, 8425297177/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4561 :
    (8425297176 : ℝ) / 10^9 < Real.log 4561 ∧
    Real.log 4561 < (8425297177 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4561) ?_ ?_
  · -- exp(8425297176/10^9) < 4561: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4561 < exp(8425297177/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4567) ∈ (8426611813/10⁹, 8426611814/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4567 :
    (8426611813 : ℝ) / 10^9 < Real.log 4567 ∧
    Real.log 4567 < (8426611814 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4567) ?_ ?_
  · -- exp(8426611813/10^9) < 4567: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4567 < exp(8426611814/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4583) ∈ (8430109084/10⁹, 8430109085/10⁹). n_hi=32, n_lo=28 -/
theorem log_enc_4583 :
    (8430109084 : ℝ) / 10^9 < Real.log 4583 ∧
    Real.log 4583 < (8430109085 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4583) ?_ ?_
  · -- exp(8430109084/10^9) < 4583: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4583 < exp(8430109085/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4591) ∈ (8431853144/10⁹, 8431853145/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4591 :
    (8431853144 : ℝ) / 10^9 < Real.log 4591 ∧
    Real.log 4591 < (8431853145 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4591) ?_ ?_
  · -- exp(8431853144/10^9) < 4591: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4591 < exp(8431853145/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4597) ∈ (8433159195/10⁹, 8433159196/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4597 :
    (8433159195 : ℝ) / 10^9 < Real.log 4597 ∧
    Real.log 4597 < (8433159196 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4597) ?_ ?_
  · -- exp(8433159195/10^9) < 4597: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4597 < exp(8433159196/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4603) ∈ (8434463543/10⁹, 8434463544/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4603 :
    (8434463543 : ℝ) / 10^9 < Real.log 4603 ∧
    Real.log 4603 < (8434463544 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4603) ?_ ?_
  · -- exp(8434463543/10^9) < 4603: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4603 < exp(8434463544/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4621) ∈ (8438366410/10⁹, 8438366411/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4621 :
    (8438366410 : ℝ) / 10^9 < Real.log 4621 ∧
    Real.log 4621 < (8438366411 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4621) ?_ ?_
  · -- exp(8438366410/10^9) < 4621: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4621 < exp(8438366411/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4637) ∈ (8441822884/10⁹, 8441822885/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4637 :
    (8441822884 : ℝ) / 10^9 < Real.log 4637 ∧
    Real.log 4637 < (8441822885 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4637) ?_ ?_
  · -- exp(8441822884/10^9) < 4637: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4637 < exp(8441822885/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

end Goldbach
