/-
  Goldbach/PrimeLogEnclosures.lean
  1229 theorems proving log(p) enclosures for all primes p ≤ 9973.

  For each prime p, we prove:
    ⌊log(p)·10⁹⌋/10⁹ < log(p) < (⌊log(p)·10⁹⌋+1)/10⁹

  Strategy:
  - Hi-side (p < exp(hi)): via S_n(hi) ≤ exp(hi) [Mathlib: sum_le_exp_of_nonneg]
    then p < S_n(hi) [by norm_num after Finset.sum unfolding].
  - Lo-side (exp(lo) < p): via exp(lo) ≤ S_n(lo) + tail [ExpBounds]
    then S_n(lo) + tail < p [by norm_num].

  Sorry count: 0

  Generated by generate_prime_enclosures_v4.py
-/
import Goldbach.ExpBounds
import Goldbach.A2CertificateData
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Analysis.SpecialFunctions.Exp
import Mathlib.Data.Real.Basic
import Mathlib.Tactic

namespace Goldbach

open Finset Real BigOperators

/-! ## Individual prime log enclosures

Each theorem has the form:
  `lo/10^9 < log(p) < hi/10^9`
proved via the master combinator `log_enclosure_of_exp_bounds`.
-/

/-- log(2) ∈ (693147180/10⁹, 693147181/10⁹). n_hi=11, n_lo=8 -/
theorem log_enc_2 :
    (693147180 : ℝ) / 10^9 < Real.log 2 ∧
    Real.log 2 < (693147181 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 2) ?_ ?_
  · -- exp(693147180/10^9) < 2: use 8 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 8) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 2 < exp(693147181/10^9): use 11 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 11) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(3) ∈ (1098612288/10⁹, 1098612289/10⁹). n_hi=13, n_lo=10 -/
theorem log_enc_3 :
    (1098612288 : ℝ) / 10^9 < Real.log 3 ∧
    Real.log 3 < (1098612289 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 3) ?_ ?_
  · -- exp(1098612288/10^9) < 3: use 10 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 10) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 3 < exp(1098612289/10^9): use 13 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 13) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5) ∈ (1609437912/10⁹, 1609437913/10⁹). n_hi=15, n_lo=12 -/
theorem log_enc_5 :
    (1609437912 : ℝ) / 10^9 < Real.log 5 ∧
    Real.log 5 < (1609437913 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5) ?_ ?_
  · -- exp(1609437912/10^9) < 5: use 12 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 12) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5 < exp(1609437913/10^9): use 15 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 15) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(7) ∈ (1945910149/10⁹, 1945910150/10⁹). n_hi=16, n_lo=14 -/
theorem log_enc_7 :
    (1945910149 : ℝ) / 10^9 < Real.log 7 ∧
    Real.log 7 < (1945910150 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 7) ?_ ?_
  · -- exp(1945910149/10^9) < 7: use 14 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 14) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 7 < exp(1945910150/10^9): use 16 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 16) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(11) ∈ (2397895272/10⁹, 2397895273/10⁹). n_hi=18, n_lo=14 -/
theorem log_enc_11 :
    (2397895272 : ℝ) / 10^9 < Real.log 11 ∧
    Real.log 11 < (2397895273 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 11) ?_ ?_
  · -- exp(2397895272/10^9) < 11: use 14 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 14) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 11 < exp(2397895273/10^9): use 18 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 18) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(13) ∈ (2564949357/10⁹, 2564949358/10⁹). n_hi=18, n_lo=15 -/
theorem log_enc_13 :
    (2564949357 : ℝ) / 10^9 < Real.log 13 ∧
    Real.log 13 < (2564949358 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 13) ?_ ?_
  · -- exp(2564949357/10^9) < 13: use 15 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 15) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 13 < exp(2564949358/10^9): use 18 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 18) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(17) ∈ (2833213344/10⁹, 2833213345/10⁹). n_hi=19, n_lo=17 -/
theorem log_enc_17 :
    (2833213344 : ℝ) / 10^9 < Real.log 17 ∧
    Real.log 17 < (2833213345 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 17) ?_ ?_
  · -- exp(2833213344/10^9) < 17: use 17 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 17) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 17 < exp(2833213345/10^9): use 19 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 19) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(19) ∈ (2944438979/10⁹, 2944438980/10⁹). n_hi=19, n_lo=17 -/
theorem log_enc_19 :
    (2944438979 : ℝ) / 10^9 < Real.log 19 ∧
    Real.log 19 < (2944438980 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 19) ?_ ?_
  · -- exp(2944438979/10^9) < 19: use 17 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 17) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 19 < exp(2944438980/10^9): use 19 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 19) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(23) ∈ (3135494215/10⁹, 3135494216/10⁹). n_hi=21, n_lo=16 -/
theorem log_enc_23 :
    (3135494215 : ℝ) / 10^9 < Real.log 23 ∧
    Real.log 23 < (3135494216 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 23) ?_ ?_
  · -- exp(3135494215/10^9) < 23: use 16 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 16) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 23 < exp(3135494216/10^9): use 21 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 21) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(29) ∈ (3367295829/10⁹, 3367295830/10⁹). n_hi=23, n_lo=17 -/
theorem log_enc_29 :
    (3367295829 : ℝ) / 10^9 < Real.log 29 ∧
    Real.log 29 < (3367295830 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 29) ?_ ?_
  · -- exp(3367295829/10^9) < 29: use 17 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 17) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 29 < exp(3367295830/10^9): use 23 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 23) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(31) ∈ (3433987204/10⁹, 3433987205/10⁹). n_hi=21, n_lo=17 -/
theorem log_enc_31 :
    (3433987204 : ℝ) / 10^9 < Real.log 31 ∧
    Real.log 31 < (3433987205 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 31) ?_ ?_
  · -- exp(3433987204/10^9) < 31: use 17 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 17) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 31 < exp(3433987205/10^9): use 21 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 21) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(37) ∈ (3610917912/10⁹, 3610917913/10⁹). n_hi=21, n_lo=18 -/
theorem log_enc_37 :
    (3610917912 : ℝ) / 10^9 < Real.log 37 ∧
    Real.log 37 < (3610917913 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 37) ?_ ?_
  · -- exp(3610917912/10^9) < 37: use 18 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 18) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 37 < exp(3610917913/10^9): use 21 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 21) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(41) ∈ (3713572066/10⁹, 3713572067/10⁹). n_hi=22, n_lo=18 -/
theorem log_enc_41 :
    (3713572066 : ℝ) / 10^9 < Real.log 41 ∧
    Real.log 41 < (3713572067 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 41) ?_ ?_
  · -- exp(3713572066/10^9) < 41: use 18 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 18) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 41 < exp(3713572067/10^9): use 22 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 22) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(43) ∈ (3761200115/10⁹, 3761200116/10⁹). n_hi=22, n_lo=18 -/
theorem log_enc_43 :
    (3761200115 : ℝ) / 10^9 < Real.log 43 ∧
    Real.log 43 < (3761200116 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 43) ?_ ?_
  · -- exp(3761200115/10^9) < 43: use 18 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 18) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 43 < exp(3761200116/10^9): use 22 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 22) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(47) ∈ (3850147601/10⁹, 3850147602/10⁹). n_hi=22, n_lo=18 -/
theorem log_enc_47 :
    (3850147601 : ℝ) / 10^9 < Real.log 47 ∧
    Real.log 47 < (3850147602 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 47) ?_ ?_
  · -- exp(3850147601/10^9) < 47: use 18 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 18) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 47 < exp(3850147602/10^9): use 22 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 22) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(53) ∈ (3970291913/10⁹, 3970291914/10⁹). n_hi=22, n_lo=19 -/
theorem log_enc_53 :
    (3970291913 : ℝ) / 10^9 < Real.log 53 ∧
    Real.log 53 < (3970291914 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 53) ?_ ?_
  · -- exp(3970291913/10^9) < 53: use 19 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 19) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 53 < exp(3970291914/10^9): use 22 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 22) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(59) ∈ (4077537443/10⁹, 4077537444/10⁹). n_hi=23, n_lo=19 -/
theorem log_enc_59 :
    (4077537443 : ℝ) / 10^9 < Real.log 59 ∧
    Real.log 59 < (4077537444 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 59) ?_ ?_
  · -- exp(4077537443/10^9) < 59: use 19 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 19) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 59 < exp(4077537444/10^9): use 23 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 23) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(61) ∈ (4110873864/10⁹, 4110873865/10⁹). n_hi=22, n_lo=20 -/
theorem log_enc_61 :
    (4110873864 : ℝ) / 10^9 < Real.log 61 ∧
    Real.log 61 < (4110873865 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 61) ?_ ?_
  · -- exp(4110873864/10^9) < 61: use 20 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 20) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 61 < exp(4110873865/10^9): use 22 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 22) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(67) ∈ (4204692619/10⁹, 4204692620/10⁹). n_hi=23, n_lo=19 -/
theorem log_enc_67 :
    (4204692619 : ℝ) / 10^9 < Real.log 67 ∧
    Real.log 67 < (4204692620 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 67) ?_ ?_
  · -- exp(4204692619/10^9) < 67: use 19 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 19) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 67 < exp(4204692620/10^9): use 23 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 23) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(71) ∈ (4262679877/10⁹, 4262679878/10⁹). n_hi=23, n_lo=21 -/
theorem log_enc_71 :
    (4262679877 : ℝ) / 10^9 < Real.log 71 ∧
    Real.log 71 < (4262679878 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 71) ?_ ?_
  · -- exp(4262679877/10^9) < 71: use 21 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 21) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 71 < exp(4262679878/10^9): use 23 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 23) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(73) ∈ (4290459441/10⁹, 4290459442/10⁹). n_hi=23, n_lo=20 -/
theorem log_enc_73 :
    (4290459441 : ℝ) / 10^9 < Real.log 73 ∧
    Real.log 73 < (4290459442 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 73) ?_ ?_
  · -- exp(4290459441/10^9) < 73: use 20 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 20) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 73 < exp(4290459442/10^9): use 23 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 23) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(79) ∈ (4369447852/10⁹, 4369447853/10⁹). n_hi=23, n_lo=20 -/
theorem log_enc_79 :
    (4369447852 : ℝ) / 10^9 < Real.log 79 ∧
    Real.log 79 < (4369447853 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 79) ?_ ?_
  · -- exp(4369447852/10^9) < 79: use 20 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 20) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 79 < exp(4369447853/10^9): use 23 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 23) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(83) ∈ (4418840607/10⁹, 4418840608/10⁹). n_hi=24, n_lo=20 -/
theorem log_enc_83 :
    (4418840607 : ℝ) / 10^9 < Real.log 83 ∧
    Real.log 83 < (4418840608 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 83) ?_ ?_
  · -- exp(4418840607/10^9) < 83: use 20 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 20) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 83 < exp(4418840608/10^9): use 24 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 24) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(89) ∈ (4488636369/10⁹, 4488636370/10⁹). n_hi=24, n_lo=20 -/
theorem log_enc_89 :
    (4488636369 : ℝ) / 10^9 < Real.log 89 ∧
    Real.log 89 < (4488636370 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 89) ?_ ?_
  · -- exp(4488636369/10^9) < 89: use 20 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 20) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 89 < exp(4488636370/10^9): use 24 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 24) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(97) ∈ (4574710978/10⁹, 4574710979/10⁹). n_hi=24, n_lo=20 -/
theorem log_enc_97 :
    (4574710978 : ℝ) / 10^9 < Real.log 97 ∧
    Real.log 97 < (4574710979 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 97) ?_ ?_
  · -- exp(4574710978/10^9) < 97: use 20 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 20) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 97 < exp(4574710979/10^9): use 24 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 24) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(101) ∈ (4615120516/10⁹, 4615120517/10⁹). n_hi=25, n_lo=20 -/
theorem log_enc_101 :
    (4615120516 : ℝ) / 10^9 < Real.log 101 ∧
    Real.log 101 < (4615120517 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 101) ?_ ?_
  · -- exp(4615120516/10^9) < 101: use 20 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 20) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 101 < exp(4615120517/10^9): use 25 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 25) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(103) ∈ (4634728988/10⁹, 4634728989/10⁹). n_hi=24, n_lo=21 -/
theorem log_enc_103 :
    (4634728988 : ℝ) / 10^9 < Real.log 103 ∧
    Real.log 103 < (4634728989 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 103) ?_ ?_
  · -- exp(4634728988/10^9) < 103: use 21 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 21) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 103 < exp(4634728989/10^9): use 24 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 24) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(107) ∈ (4672828834/10⁹, 4672828835/10⁹). n_hi=24, n_lo=20 -/
theorem log_enc_107 :
    (4672828834 : ℝ) / 10^9 < Real.log 107 ∧
    Real.log 107 < (4672828835 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 107) ?_ ?_
  · -- exp(4672828834/10^9) < 107: use 20 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 20) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 107 < exp(4672828835/10^9): use 24 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 24) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(109) ∈ (4691347882/10⁹, 4691347883/10⁹). n_hi=24, n_lo=21 -/
theorem log_enc_109 :
    (4691347882 : ℝ) / 10^9 < Real.log 109 ∧
    Real.log 109 < (4691347883 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 109) ?_ ?_
  · -- exp(4691347882/10^9) < 109: use 21 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 21) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 109 < exp(4691347883/10^9): use 24 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 24) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(113) ∈ (4727387818/10⁹, 4727387819/10⁹). n_hi=24, n_lo=20 -/
theorem log_enc_113 :
    (4727387818 : ℝ) / 10^9 < Real.log 113 ∧
    Real.log 113 < (4727387819 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 113) ?_ ?_
  · -- exp(4727387818/10^9) < 113: use 20 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 20) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 113 < exp(4727387819/10^9): use 24 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 24) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(127) ∈ (4844187086/10⁹, 4844187087/10⁹). n_hi=24, n_lo=21 -/
theorem log_enc_127 :
    (4844187086 : ℝ) / 10^9 < Real.log 127 ∧
    Real.log 127 < (4844187087 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 127) ?_ ?_
  · -- exp(4844187086/10^9) < 127: use 21 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 21) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 127 < exp(4844187087/10^9): use 24 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 24) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(131) ∈ (4875197323/10⁹, 4875197324/10⁹). n_hi=24, n_lo=21 -/
theorem log_enc_131 :
    (4875197323 : ℝ) / 10^9 < Real.log 131 ∧
    Real.log 131 < (4875197324 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 131) ?_ ?_
  · -- exp(4875197323/10^9) < 131: use 21 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 21) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 131 < exp(4875197324/10^9): use 24 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 24) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(137) ∈ (4919980925/10⁹, 4919980926/10⁹). n_hi=25, n_lo=21 -/
theorem log_enc_137 :
    (4919980925 : ℝ) / 10^9 < Real.log 137 ∧
    Real.log 137 < (4919980926 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 137) ?_ ?_
  · -- exp(4919980925/10^9) < 137: use 21 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 21) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 137 < exp(4919980926/10^9): use 25 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 25) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(139) ∈ (4934473933/10⁹, 4934473934/10⁹). n_hi=24, n_lo=22 -/
theorem log_enc_139 :
    (4934473933 : ℝ) / 10^9 < Real.log 139 ∧
    Real.log 139 < (4934473934 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 139) ?_ ?_
  · -- exp(4934473933/10^9) < 139: use 22 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 22) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 139 < exp(4934473934/10^9): use 24 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 24) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(149) ∈ (5003946305/10⁹, 5003946306/10⁹). n_hi=26, n_lo=21 -/
theorem log_enc_149 :
    (5003946305 : ℝ) / 10^9 < Real.log 149 ∧
    Real.log 149 < (5003946306 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 149) ?_ ?_
  · -- exp(5003946305/10^9) < 149: use 21 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 21) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 149 < exp(5003946306/10^9): use 26 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 26) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(151) ∈ (5017279836/10⁹, 5017279837/10⁹). n_hi=25, n_lo=21 -/
theorem log_enc_151 :
    (5017279836 : ℝ) / 10^9 < Real.log 151 ∧
    Real.log 151 < (5017279837 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 151) ?_ ?_
  · -- exp(5017279836/10^9) < 151: use 21 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 21) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 151 < exp(5017279837/10^9): use 25 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 25) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(157) ∈ (5056245805/10⁹, 5056245806/10⁹). n_hi=25, n_lo=22 -/
theorem log_enc_157 :
    (5056245805 : ℝ) / 10^9 < Real.log 157 ∧
    Real.log 157 < (5056245806 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 157) ?_ ?_
  · -- exp(5056245805/10^9) < 157: use 22 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 22) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 157 < exp(5056245806/10^9): use 25 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 25) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(163) ∈ (5093750200/10⁹, 5093750201/10⁹). n_hi=26, n_lo=21 -/
theorem log_enc_163 :
    (5093750200 : ℝ) / 10^9 < Real.log 163 ∧
    Real.log 163 < (5093750201 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 163) ?_ ?_
  · -- exp(5093750200/10^9) < 163: use 21 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 21) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 163 < exp(5093750201/10^9): use 26 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 26) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(167) ∈ (5117993812/10⁹, 5117993813/10⁹). n_hi=25, n_lo=22 -/
theorem log_enc_167 :
    (5117993812 : ℝ) / 10^9 < Real.log 167 ∧
    Real.log 167 < (5117993813 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 167) ?_ ?_
  · -- exp(5117993812/10^9) < 167: use 22 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 22) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 167 < exp(5117993813/10^9): use 25 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 25) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(173) ∈ (5153291594/10⁹, 5153291595/10⁹). n_hi=25, n_lo=22 -/
theorem log_enc_173 :
    (5153291594 : ℝ) / 10^9 < Real.log 173 ∧
    Real.log 173 < (5153291595 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 173) ?_ ?_
  · -- exp(5153291594/10^9) < 173: use 22 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 22) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 173 < exp(5153291595/10^9): use 25 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 25) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(179) ∈ (5187385805/10⁹, 5187385806/10⁹). n_hi=26, n_lo=21 -/
theorem log_enc_179 :
    (5187385805 : ℝ) / 10^9 < Real.log 179 ∧
    Real.log 179 < (5187385806 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 179) ?_ ?_
  · -- exp(5187385805/10^9) < 179: use 21 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 21) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 179 < exp(5187385806/10^9): use 26 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 26) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(181) ∈ (5198497031/10⁹, 5198497032/10⁹). n_hi=25, n_lo=22 -/
theorem log_enc_181 :
    (5198497031 : ℝ) / 10^9 < Real.log 181 ∧
    Real.log 181 < (5198497032 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 181) ?_ ?_
  · -- exp(5198497031/10^9) < 181: use 22 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 22) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 181 < exp(5198497032/10^9): use 25 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 25) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(191) ∈ (5252273428/10⁹, 5252273429/10⁹). n_hi=25, n_lo=23 -/
theorem log_enc_191 :
    (5252273428 : ℝ) / 10^9 < Real.log 191 ∧
    Real.log 191 < (5252273429 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 191) ?_ ?_
  · -- exp(5252273428/10^9) < 191: use 23 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 23) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 191 < exp(5252273429/10^9): use 25 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 25) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(193) ∈ (5262690188/10⁹, 5262690189/10⁹). n_hi=26, n_lo=21 -/
theorem log_enc_193 :
    (5262690188 : ℝ) / 10^9 < Real.log 193 ∧
    Real.log 193 < (5262690189 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 193) ?_ ?_
  · -- exp(5262690188/10^9) < 193: use 21 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 21) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 193 < exp(5262690189/10^9): use 26 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 26) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(197) ∈ (5283203728/10⁹, 5283203729/10⁹). n_hi=26, n_lo=22 -/
theorem log_enc_197 :
    (5283203728 : ℝ) / 10^9 < Real.log 197 ∧
    Real.log 197 < (5283203729 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 197) ?_ ?_
  · -- exp(5283203728/10^9) < 197: use 22 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 22) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 197 < exp(5283203729/10^9): use 26 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 26) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(199) ∈ (5293304824/10⁹, 5293304825/10⁹). n_hi=26, n_lo=22 -/
theorem log_enc_199 :
    (5293304824 : ℝ) / 10^9 < Real.log 199 ∧
    Real.log 199 < (5293304825 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 199) ?_ ?_
  · -- exp(5293304824/10^9) < 199: use 22 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 22) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 199 < exp(5293304825/10^9): use 26 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 26) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(211) ∈ (5351858133/10⁹, 5351858134/10⁹). n_hi=26, n_lo=22 -/
theorem log_enc_211 :
    (5351858133 : ℝ) / 10^9 < Real.log 211 ∧
    Real.log 211 < (5351858134 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 211) ?_ ?_
  · -- exp(5351858133/10^9) < 211: use 22 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 22) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 211 < exp(5351858134/10^9): use 26 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 26) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(223) ∈ (5407171771/10⁹, 5407171772/10⁹). n_hi=26, n_lo=22 -/
theorem log_enc_223 :
    (5407171771 : ℝ) / 10^9 < Real.log 223 ∧
    Real.log 223 < (5407171772 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 223) ?_ ?_
  · -- exp(5407171771/10^9) < 223: use 22 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 22) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 223 < exp(5407171772/10^9): use 26 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 26) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(227) ∈ (5424950017/10⁹, 5424950018/10⁹). n_hi=26, n_lo=22 -/
theorem log_enc_227 :
    (5424950017 : ℝ) / 10^9 < Real.log 227 ∧
    Real.log 227 < (5424950018 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 227) ?_ ?_
  · -- exp(5424950017/10^9) < 227: use 22 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 22) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 227 < exp(5424950018/10^9): use 26 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 26) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(229) ∈ (5433722003/10⁹, 5433722004/10⁹). n_hi=26, n_lo=22 -/
theorem log_enc_229 :
    (5433722003 : ℝ) / 10^9 < Real.log 229 ∧
    Real.log 229 < (5433722004 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 229) ?_ ?_
  · -- exp(5433722003/10^9) < 229: use 22 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 22) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 229 < exp(5433722004/10^9): use 26 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 26) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(233) ∈ (5451038453/10⁹, 5451038454/10⁹). n_hi=26, n_lo=22 -/
theorem log_enc_233 :
    (5451038453 : ℝ) / 10^9 < Real.log 233 ∧
    Real.log 233 < (5451038454 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 233) ?_ ?_
  · -- exp(5451038453/10^9) < 233: use 22 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 22) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 233 < exp(5451038454/10^9): use 26 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 26) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(239) ∈ (5476463551/10⁹, 5476463552/10⁹). n_hi=27, n_lo=22 -/
theorem log_enc_239 :
    (5476463551 : ℝ) / 10^9 < Real.log 239 ∧
    Real.log 239 < (5476463552 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 239) ?_ ?_
  · -- exp(5476463551/10^9) < 239: use 22 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 22) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 239 < exp(5476463552/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(241) ∈ (5484796933/10⁹, 5484796934/10⁹). n_hi=26, n_lo=22 -/
theorem log_enc_241 :
    (5484796933 : ℝ) / 10^9 < Real.log 241 ∧
    Real.log 241 < (5484796934 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 241) ?_ ?_
  · -- exp(5484796933/10^9) < 241: use 22 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 22) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 241 < exp(5484796934/10^9): use 26 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 26) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(251) ∈ (5525452939/10⁹, 5525452940/10⁹). n_hi=26, n_lo=23 -/
theorem log_enc_251 :
    (5525452939 : ℝ) / 10^9 < Real.log 251 ∧
    Real.log 251 < (5525452940 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 251) ?_ ?_
  · -- exp(5525452939/10^9) < 251: use 23 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 23) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 251 < exp(5525452940/10^9): use 26 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 26) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(257) ∈ (5549076084/10⁹, 5549076085/10⁹). n_hi=27, n_lo=22 -/
theorem log_enc_257 :
    (5549076084 : ℝ) / 10^9 < Real.log 257 ∧
    Real.log 257 < (5549076085 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 257) ?_ ?_
  · -- exp(5549076084/10^9) < 257: use 22 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 22) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 257 < exp(5549076085/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(263) ∈ (5572154032/10⁹, 5572154033/10⁹). n_hi=26, n_lo=23 -/
theorem log_enc_263 :
    (5572154032 : ℝ) / 10^9 < Real.log 263 ∧
    Real.log 263 < (5572154033 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 263) ?_ ?_
  · -- exp(5572154032/10^9) < 263: use 23 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 23) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 263 < exp(5572154033/10^9): use 26 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 26) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(269) ∈ (5594711379/10⁹, 5594711380/10⁹). n_hi=26, n_lo=22 -/
theorem log_enc_269 :
    (5594711379 : ℝ) / 10^9 < Real.log 269 ∧
    Real.log 269 < (5594711380 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 269) ?_ ?_
  · -- exp(5594711379/10^9) < 269: use 22 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 22) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 269 < exp(5594711380/10^9): use 26 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 26) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(271) ∈ (5602118820/10⁹, 5602118821/10⁹). n_hi=27, n_lo=22 -/
theorem log_enc_271 :
    (5602118820 : ℝ) / 10^9 < Real.log 271 ∧
    Real.log 271 < (5602118821 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 271) ?_ ?_
  · -- exp(5602118820/10^9) < 271: use 22 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 22) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 271 < exp(5602118821/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(277) ∈ (5624017506/10⁹, 5624017507/10⁹). n_hi=26, n_lo=23 -/
theorem log_enc_277 :
    (5624017506 : ℝ) / 10^9 < Real.log 277 ∧
    Real.log 277 < (5624017507 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 277) ?_ ?_
  · -- exp(5624017506/10^9) < 277: use 23 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 23) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 277 < exp(5624017507/10^9): use 26 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 26) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(281) ∈ (5638354669/10⁹, 5638354670/10⁹). n_hi=26, n_lo=23 -/
theorem log_enc_281 :
    (5638354669 : ℝ) / 10^9 < Real.log 281 ∧
    Real.log 281 < (5638354670 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 281) ?_ ?_
  · -- exp(5638354669/10^9) < 281: use 23 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 23) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 281 < exp(5638354670/10^9): use 26 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 26) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(283) ∈ (5645446897/10⁹, 5645446898/10⁹). n_hi=27, n_lo=22 -/
theorem log_enc_283 :
    (5645446897 : ℝ) / 10^9 < Real.log 283 ∧
    Real.log 283 < (5645446898 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 283) ?_ ?_
  · -- exp(5645446897/10^9) < 283: use 22 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 22) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 283 < exp(5645446898/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(293) ∈ (5680172609/10⁹, 5680172610/10⁹). n_hi=26, n_lo=25 -/
theorem log_enc_293 :
    (5680172609 : ℝ) / 10^9 < Real.log 293 ∧
    Real.log 293 < (5680172610 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 293) ?_ ?_
  · -- exp(5680172609/10^9) < 293: use 25 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 25) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 293 < exp(5680172610/10^9): use 26 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 26) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(307) ∈ (5726847747/10⁹, 5726847748/10⁹). n_hi=27, n_lo=23 -/
theorem log_enc_307 :
    (5726847747 : ℝ) / 10^9 < Real.log 307 ∧
    Real.log 307 < (5726847748 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 307) ?_ ?_
  · -- exp(5726847747/10^9) < 307: use 23 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 23) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 307 < exp(5726847748/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(311) ∈ (5739792912/10⁹, 5739792913/10⁹). n_hi=26, n_lo=23 -/
theorem log_enc_311 :
    (5739792912 : ℝ) / 10^9 < Real.log 311 ∧
    Real.log 311 < (5739792913 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 311) ?_ ?_
  · -- exp(5739792912/10^9) < 311: use 23 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 23) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 311 < exp(5739792913/10^9): use 26 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 26) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(313) ∈ (5746203190/10⁹, 5746203191/10⁹). n_hi=27, n_lo=23 -/
theorem log_enc_313 :
    (5746203190 : ℝ) / 10^9 < Real.log 313 ∧
    Real.log 313 < (5746203191 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 313) ?_ ?_
  · -- exp(5746203190/10^9) < 313: use 23 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 23) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 313 < exp(5746203191/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(317) ∈ (5758901773/10⁹, 5758901774/10⁹). n_hi=28, n_lo=22 -/
theorem log_enc_317 :
    (5758901773 : ℝ) / 10^9 < Real.log 317 ∧
    Real.log 317 < (5758901774 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 317) ?_ ?_
  · -- exp(5758901773/10^9) < 317: use 22 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 22) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 317 < exp(5758901774/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(331) ∈ (5802118375/10⁹, 5802118376/10⁹). n_hi=27, n_lo=23 -/
theorem log_enc_331 :
    (5802118375 : ℝ) / 10^9 < Real.log 331 ∧
    Real.log 331 < (5802118376 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 331) ?_ ?_
  · -- exp(5802118375/10^9) < 331: use 23 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 23) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 331 < exp(5802118376/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(337) ∈ (5820082930/10⁹, 5820082931/10⁹). n_hi=27, n_lo=23 -/
theorem log_enc_337 :
    (5820082930 : ℝ) / 10^9 < Real.log 337 ∧
    Real.log 337 < (5820082931 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 337) ?_ ?_
  · -- exp(5820082930/10^9) < 337: use 23 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 23) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 337 < exp(5820082931/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(347) ∈ (5849324779/10⁹, 5849324780/10⁹). n_hi=28, n_lo=23 -/
theorem log_enc_347 :
    (5849324779 : ℝ) / 10^9 < Real.log 347 ∧
    Real.log 347 < (5849324780 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 347) ?_ ?_
  · -- exp(5849324779/10^9) < 347: use 23 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 23) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 347 < exp(5849324780/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(349) ∈ (5855071922/10⁹, 5855071923/10⁹). n_hi=27, n_lo=24 -/
theorem log_enc_349 :
    (5855071922 : ℝ) / 10^9 < Real.log 349 ∧
    Real.log 349 < (5855071923 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 349) ?_ ?_
  · -- exp(5855071922/10^9) < 349: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 349 < exp(5855071923/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(353) ∈ (5866468056/10⁹, 5866468057/10⁹). n_hi=28, n_lo=23 -/
theorem log_enc_353 :
    (5866468056 : ℝ) / 10^9 < Real.log 353 ∧
    Real.log 353 < (5866468057 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 353) ?_ ?_
  · -- exp(5866468056/10^9) < 353: use 23 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 23) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 353 < exp(5866468057/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(359) ∈ (5883322388/10⁹, 5883322389/10⁹). n_hi=27, n_lo=23 -/
theorem log_enc_359 :
    (5883322388 : ℝ) / 10^9 < Real.log 359 ∧
    Real.log 359 < (5883322389 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 359) ?_ ?_
  · -- exp(5883322388/10^9) < 359: use 23 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 23) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 359 < exp(5883322389/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(367) ∈ (5905361848/10⁹, 5905361849/10⁹). n_hi=27, n_lo=25 -/
theorem log_enc_367 :
    (5905361848 : ℝ) / 10^9 < Real.log 367 ∧
    Real.log 367 < (5905361849 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 367) ?_ ?_
  · -- exp(5905361848/10^9) < 367: use 25 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 25) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 367 < exp(5905361849/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(373) ∈ (5921578419/10⁹, 5921578420/10⁹). n_hi=27, n_lo=23 -/
theorem log_enc_373 :
    (5921578419 : ℝ) / 10^9 < Real.log 373 ∧
    Real.log 373 < (5921578420 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 373) ?_ ?_
  · -- exp(5921578419/10^9) < 373: use 23 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 23) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 373 < exp(5921578420/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(379) ∈ (5937536205/10⁹, 5937536206/10⁹). n_hi=27, n_lo=24 -/
theorem log_enc_379 :
    (5937536205 : ℝ) / 10^9 < Real.log 379 ∧
    Real.log 379 < (5937536206 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 379) ?_ ?_
  · -- exp(5937536205/10^9) < 379: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 379 < exp(5937536206/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(383) ∈ (5948034989/10⁹, 5948034990/10⁹). n_hi=27, n_lo=24 -/
theorem log_enc_383 :
    (5948034989 : ℝ) / 10^9 < Real.log 383 ∧
    Real.log 383 < (5948034990 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 383) ?_ ?_
  · -- exp(5948034989/10^9) < 383: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 383 < exp(5948034990/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(389) ∈ (5963579343/10⁹, 5963579344/10⁹). n_hi=27, n_lo=23 -/
theorem log_enc_389 :
    (5963579343 : ℝ) / 10^9 < Real.log 389 ∧
    Real.log 389 < (5963579344 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 389) ?_ ?_
  · -- exp(5963579343/10^9) < 389: use 23 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 23) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 389 < exp(5963579344/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(397) ∈ (5983936280/10⁹, 5983936281/10⁹). n_hi=27, n_lo=23 -/
theorem log_enc_397 :
    (5983936280 : ℝ) / 10^9 < Real.log 397 ∧
    Real.log 397 < (5983936281 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 397) ?_ ?_
  · -- exp(5983936280/10^9) < 397: use 23 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 23) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 397 < exp(5983936281/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(401) ∈ (5993961427/10⁹, 5993961428/10⁹). n_hi=27, n_lo=24 -/
theorem log_enc_401 :
    (5993961427 : ℝ) / 10^9 < Real.log 401 ∧
    Real.log 401 < (5993961428 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 401) ?_ ?_
  · -- exp(5993961427/10^9) < 401: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 401 < exp(5993961428/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(409) ∈ (6013715156/10⁹, 6013715157/10⁹). n_hi=27, n_lo=25 -/
theorem log_enc_409 :
    (6013715156 : ℝ) / 10^9 < Real.log 409 ∧
    Real.log 409 < (6013715157 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 409) ?_ ?_
  · -- exp(6013715156/10^9) < 409: use 25 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 25) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 409 < exp(6013715157/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(419) ∈ (6037870919/10⁹, 6037870920/10⁹). n_hi=28, n_lo=23 -/
theorem log_enc_419 :
    (6037870919 : ℝ) / 10^9 < Real.log 419 ∧
    Real.log 419 < (6037870920 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 419) ?_ ?_
  · -- exp(6037870919/10^9) < 419: use 23 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 23) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 419 < exp(6037870920/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(421) ∈ (6042632833/10⁹, 6042632834/10⁹). n_hi=28, n_lo=23 -/
theorem log_enc_421 :
    (6042632833 : ℝ) / 10^9 < Real.log 421 ∧
    Real.log 421 < (6042632834 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 421) ?_ ?_
  · -- exp(6042632833/10^9) < 421: use 23 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 23) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 421 < exp(6042632834/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(431) ∈ (6066108090/10⁹, 6066108091/10⁹). n_hi=27, n_lo=25 -/
theorem log_enc_431 :
    (6066108090 : ℝ) / 10^9 < Real.log 431 ∧
    Real.log 431 < (6066108091 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 431) ?_ ?_
  · -- exp(6066108090/10^9) < 431: use 25 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 25) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 431 < exp(6066108091/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(433) ∈ (6070737728/10⁹, 6070737729/10⁹). n_hi=27, n_lo=27 -/
theorem log_enc_433 :
    (6070737728 : ℝ) / 10^9 < Real.log 433 ∧
    Real.log 433 < (6070737729 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 433) ?_ ?_
  · -- exp(6070737728/10^9) < 433: use 27 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 27) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 433 < exp(6070737729/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(439) ∈ (6084499413/10⁹, 6084499414/10⁹). n_hi=27, n_lo=25 -/
theorem log_enc_439 :
    (6084499413 : ℝ) / 10^9 < Real.log 439 ∧
    Real.log 439 < (6084499414 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 439) ?_ ?_
  · -- exp(6084499413/10^9) < 439: use 25 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 25) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 439 < exp(6084499414/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(443) ∈ (6093569770/10⁹, 6093569771/10⁹). n_hi=27, n_lo=25 -/
theorem log_enc_443 :
    (6093569770 : ℝ) / 10^9 < Real.log 443 ∧
    Real.log 443 < (6093569771 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 443) ?_ ?_
  · -- exp(6093569770/10^9) < 443: use 25 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 25) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 443 < exp(6093569771/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(449) ∈ (6107022887/10⁹, 6107022888/10⁹). n_hi=28, n_lo=23 -/
theorem log_enc_449 :
    (6107022887 : ℝ) / 10^9 < Real.log 449 ∧
    Real.log 449 < (6107022888 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 449) ?_ ?_
  · -- exp(6107022887/10^9) < 449: use 23 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 23) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 449 < exp(6107022888/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(457) ∈ (6124683390/10⁹, 6124683391/10⁹). n_hi=28, n_lo=23 -/
theorem log_enc_457 :
    (6124683390 : ℝ) / 10^9 < Real.log 457 ∧
    Real.log 457 < (6124683391 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 457) ?_ ?_
  · -- exp(6124683390/10^9) < 457: use 23 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 23) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 457 < exp(6124683391/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(461) ∈ (6133398042/10⁹, 6133398043/10⁹). n_hi=31, n_lo=23 -/
theorem log_enc_461 :
    (6133398042 : ℝ) / 10^9 < Real.log 461 ∧
    Real.log 461 < (6133398043 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 461) ?_ ?_
  · -- exp(6133398042/10^9) < 461: use 23 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 23) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 461 < exp(6133398043/10^9): use 31 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 31) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(463) ∈ (6137727054/10⁹, 6137727055/10⁹). n_hi=27, n_lo=25 -/
theorem log_enc_463 :
    (6137727054 : ℝ) / 10^9 < Real.log 463 ∧
    Real.log 463 < (6137727055 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 463) ?_ ?_
  · -- exp(6137727054/10^9) < 463: use 25 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 25) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 463 < exp(6137727055/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(467) ∈ (6146329257/10⁹, 6146329258/10⁹). n_hi=28, n_lo=24 -/
theorem log_enc_467 :
    (6146329257 : ℝ) / 10^9 < Real.log 467 ∧
    Real.log 467 < (6146329258 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 467) ?_ ?_
  · -- exp(6146329257/10^9) < 467: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 467 < exp(6146329258/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(479) ∈ (6171700597/10⁹, 6171700598/10⁹). n_hi=27, n_lo=24 -/
theorem log_enc_479 :
    (6171700597 : ℝ) / 10^9 < Real.log 479 ∧
    Real.log 479 < (6171700598 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 479) ?_ ?_
  · -- exp(6171700597/10^9) < 479: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 479 < exp(6171700598/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(487) ∈ (6188264123/10⁹, 6188264124/10⁹). n_hi=27, n_lo=25 -/
theorem log_enc_487 :
    (6188264123 : ℝ) / 10^9 < Real.log 487 ∧
    Real.log 487 < (6188264124 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 487) ?_ ?_
  · -- exp(6188264123/10^9) < 487: use 25 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 25) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 487 < exp(6188264124/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(491) ∈ (6196444127/10⁹, 6196444128/10⁹). n_hi=28, n_lo=24 -/
theorem log_enc_491 :
    (6196444127 : ℝ) / 10^9 < Real.log 491 ∧
    Real.log 491 < (6196444128 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 491) ?_ ?_
  · -- exp(6196444127/10^9) < 491: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 491 < exp(6196444128/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(499) ∈ (6212606095/10⁹, 6212606096/10⁹). n_hi=28, n_lo=24 -/
theorem log_enc_499 :
    (6212606095 : ℝ) / 10^9 < Real.log 499 ∧
    Real.log 499 < (6212606096 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 499) ?_ ?_
  · -- exp(6212606095/10^9) < 499: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 499 < exp(6212606096/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(503) ∈ (6220590170/10⁹, 6220590171/10⁹). n_hi=27, n_lo=25 -/
theorem log_enc_503 :
    (6220590170 : ℝ) / 10^9 < Real.log 503 ∧
    Real.log 503 < (6220590171 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 503) ?_ ?_
  · -- exp(6220590170/10^9) < 503: use 25 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 25) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 503 < exp(6220590171/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(509) ∈ (6232448016/10⁹, 6232448017/10⁹). n_hi=28, n_lo=24 -/
theorem log_enc_509 :
    (6232448016 : ℝ) / 10^9 < Real.log 509 ∧
    Real.log 509 < (6232448017 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 509) ?_ ?_
  · -- exp(6232448016/10^9) < 509: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 509 < exp(6232448017/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(521) ∈ (6255750041/10⁹, 6255750042/10⁹). n_hi=28, n_lo=24 -/
theorem log_enc_521 :
    (6255750041 : ℝ) / 10^9 < Real.log 521 ∧
    Real.log 521 < (6255750042 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 521) ?_ ?_
  · -- exp(6255750041/10^9) < 521: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 521 < exp(6255750042/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(523) ∈ (6259581464/10⁹, 6259581465/10⁹). n_hi=27, n_lo=25 -/
theorem log_enc_523 :
    (6259581464 : ℝ) / 10^9 < Real.log 523 ∧
    Real.log 523 < (6259581465 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 523) ?_ ?_
  · -- exp(6259581464/10^9) < 523: use 25 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 25) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 523 < exp(6259581465/10^9): use 27 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 27) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(541) ∈ (6293419278/10⁹, 6293419279/10⁹). n_hi=29, n_lo=24 -/
theorem log_enc_541 :
    (6293419278 : ℝ) / 10^9 < Real.log 541 ∧
    Real.log 541 < (6293419279 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 541) ?_ ?_
  · -- exp(6293419278/10^9) < 541: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 541 < exp(6293419279/10^9): use 29 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 29) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(547) ∈ (6304448802/10⁹, 6304448803/10⁹). n_hi=28, n_lo=24 -/
theorem log_enc_547 :
    (6304448802 : ℝ) / 10^9 < Real.log 547 ∧
    Real.log 547 < (6304448803 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 547) ?_ ?_
  · -- exp(6304448802/10^9) < 547: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 547 < exp(6304448803/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(557) ∈ (6322565239/10⁹, 6322565240/10⁹). n_hi=29, n_lo=24 -/
theorem log_enc_557 :
    (6322565239 : ℝ) / 10^9 < Real.log 557 ∧
    Real.log 557 < (6322565240 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 557) ?_ ?_
  · -- exp(6322565239/10^9) < 557: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 557 < exp(6322565240/10^9): use 29 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 29) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(563) ∈ (6333279628/10⁹, 6333279629/10⁹). n_hi=28, n_lo=25 -/
theorem log_enc_563 :
    (6333279628 : ℝ) / 10^9 < Real.log 563 ∧
    Real.log 563 < (6333279629 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 563) ?_ ?_
  · -- exp(6333279628/10^9) < 563: use 25 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 25) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 563 < exp(6333279629/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(569) ∈ (6343880434/10⁹, 6343880435/10⁹). n_hi=28, n_lo=25 -/
theorem log_enc_569 :
    (6343880434 : ℝ) / 10^9 < Real.log 569 ∧
    Real.log 569 < (6343880435 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 569) ?_ ?_
  · -- exp(6343880434/10^9) < 569: use 25 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 25) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 569 < exp(6343880435/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(571) ∈ (6347389209/10⁹, 6347389210/10⁹). n_hi=28, n_lo=24 -/
theorem log_enc_571 :
    (6347389209 : ℝ) / 10^9 < Real.log 571 ∧
    Real.log 571 < (6347389210 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 571) ?_ ?_
  · -- exp(6347389209/10^9) < 571: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 571 < exp(6347389210/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(577) ∈ (6357842266/10⁹, 6357842267/10⁹). n_hi=28, n_lo=24 -/
theorem log_enc_577 :
    (6357842266 : ℝ) / 10^9 < Real.log 577 ∧
    Real.log 577 < (6357842267 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 577) ?_ ?_
  · -- exp(6357842266/10^9) < 577: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 577 < exp(6357842267/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(587) ∈ (6375024819/10⁹, 6375024820/10⁹). n_hi=29, n_lo=24 -/
theorem log_enc_587 :
    (6375024819 : ℝ) / 10^9 < Real.log 587 ∧
    Real.log 587 < (6375024820 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 587) ?_ ?_
  · -- exp(6375024819/10^9) < 587: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 587 < exp(6375024820/10^9): use 29 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 29) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(593) ∈ (6385194398/10⁹, 6385194399/10⁹). n_hi=32, n_lo=24 -/
theorem log_enc_593 :
    (6385194398 : ℝ) / 10^9 < Real.log 593 ∧
    Real.log 593 < (6385194399 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 593) ?_ ?_
  · -- exp(6385194398/10^9) < 593: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 593 < exp(6385194399/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(599) ∈ (6395261598/10⁹, 6395261599/10⁹). n_hi=28, n_lo=25 -/
theorem log_enc_599 :
    (6395261598 : ℝ) / 10^9 < Real.log 599 ∧
    Real.log 599 < (6395261599 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 599) ?_ ?_
  · -- exp(6395261598/10^9) < 599: use 25 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 25) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 599 < exp(6395261599/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(601) ∈ (6398594934/10⁹, 6398594935/10⁹). n_hi=28, n_lo=24 -/
theorem log_enc_601 :
    (6398594934 : ℝ) / 10^9 < Real.log 601 ∧
    Real.log 601 < (6398594935 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 601) ?_ ?_
  · -- exp(6398594934/10^9) < 601: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 601 < exp(6398594935/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(607) ∈ (6408528791/10⁹, 6408528792/10⁹). n_hi=28, n_lo=26 -/
theorem log_enc_607 :
    (6408528791 : ℝ) / 10^9 < Real.log 607 ∧
    Real.log 607 < (6408528792 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 607) ?_ ?_
  · -- exp(6408528791/10^9) < 607: use 26 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 26) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 607 < exp(6408528792/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(613) ∈ (6418364935/10⁹, 6418364936/10⁹). n_hi=29, n_lo=24 -/
theorem log_enc_613 :
    (6418364935 : ℝ) / 10^9 < Real.log 613 ∧
    Real.log 613 < (6418364936 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 613) ?_ ?_
  · -- exp(6418364935/10^9) < 613: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 613 < exp(6418364936/10^9): use 29 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 29) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(617) ∈ (6424869023/10⁹, 6424869024/10⁹). n_hi=29, n_lo=24 -/
theorem log_enc_617 :
    (6424869023 : ℝ) / 10^9 < Real.log 617 ∧
    Real.log 617 < (6424869024 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 617) ?_ ?_
  · -- exp(6424869023/10^9) < 617: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 617 < exp(6424869024/10^9): use 29 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 29) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(619) ∈ (6428105272/10⁹, 6428105273/10⁹). n_hi=28, n_lo=24 -/
theorem log_enc_619 :
    (6428105272 : ℝ) / 10^9 < Real.log 619 ∧
    Real.log 619 < (6428105273 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 619) ?_ ?_
  · -- exp(6428105272/10^9) < 619: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 619 < exp(6428105273/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(631) ∈ (6447305862/10⁹, 6447305863/10⁹). n_hi=28, n_lo=24 -/
theorem log_enc_631 :
    (6447305862 : ℝ) / 10^9 < Real.log 631 ∧
    Real.log 631 < (6447305863 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 631) ?_ ?_
  · -- exp(6447305862/10^9) < 631: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 631 < exp(6447305863/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(641) ∈ (6463029456/10⁹, 6463029457/10⁹). n_hi=29, n_lo=24 -/
theorem log_enc_641 :
    (6463029456 : ℝ) / 10^9 < Real.log 641 ∧
    Real.log 641 < (6463029457 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 641) ?_ ?_
  · -- exp(6463029456/10^9) < 641: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 641 < exp(6463029457/10^9): use 29 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 29) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(643) ∈ (6466144724/10⁹, 6466144725/10⁹). n_hi=28, n_lo=25 -/
theorem log_enc_643 :
    (6466144724 : ℝ) / 10^9 < Real.log 643 ∧
    Real.log 643 < (6466144725 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 643) ?_ ?_
  · -- exp(6466144724/10^9) < 643: use 25 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 25) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 643 < exp(6466144725/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(647) ∈ (6472346294/10⁹, 6472346295/10⁹). n_hi=28, n_lo=24 -/
theorem log_enc_647 :
    (6472346294 : ℝ) / 10^9 < Real.log 647 ∧
    Real.log 647 < (6472346295 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 647) ?_ ?_
  · -- exp(6472346294/10^9) < 647: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 647 < exp(6472346295/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(653) ∈ (6481577129/10⁹, 6481577130/10⁹). n_hi=28, n_lo=25 -/
theorem log_enc_653 :
    (6481577129 : ℝ) / 10^9 < Real.log 653 ∧
    Real.log 653 < (6481577130 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 653) ?_ ?_
  · -- exp(6481577129/10^9) < 653: use 25 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 25) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 653 < exp(6481577130/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(659) ∈ (6490723534/10⁹, 6490723535/10⁹). n_hi=28, n_lo=24 -/
theorem log_enc_659 :
    (6490723534 : ℝ) / 10^9 < Real.log 659 ∧
    Real.log 659 < (6490723535 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 659) ?_ ?_
  · -- exp(6490723534/10^9) < 659: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 659 < exp(6490723535/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(661) ∈ (6493753839/10⁹, 6493753840/10⁹). n_hi=29, n_lo=24 -/
theorem log_enc_661 :
    (6493753839 : ℝ) / 10^9 < Real.log 661 ∧
    Real.log 661 < (6493753840 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 661) ?_ ?_
  · -- exp(6493753839/10^9) < 661: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 661 < exp(6493753840/10^9): use 29 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 29) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(673) ∈ (6511745329/10⁹, 6511745330/10⁹). n_hi=29, n_lo=24 -/
theorem log_enc_673 :
    (6511745329 : ℝ) / 10^9 < Real.log 673 ∧
    Real.log 673 < (6511745330 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 673) ?_ ?_
  · -- exp(6511745329/10^9) < 673: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 673 < exp(6511745330/10^9): use 29 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 29) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(677) ∈ (6517671272/10⁹, 6517671273/10⁹). n_hi=29, n_lo=24 -/
theorem log_enc_677 :
    (6517671272 : ℝ) / 10^9 < Real.log 677 ∧
    Real.log 677 < (6517671273 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 677) ?_ ?_
  · -- exp(6517671272/10^9) < 677: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 677 < exp(6517671273/10^9): use 29 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 29) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(683) ∈ (6526494859/10⁹, 6526494860/10⁹). n_hi=28, n_lo=24 -/
theorem log_enc_683 :
    (6526494859 : ℝ) / 10^9 < Real.log 683 ∧
    Real.log 683 < (6526494860 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 683) ?_ ?_
  · -- exp(6526494859/10^9) < 683: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 683 < exp(6526494860/10^9): use 28 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 28) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(691) ∈ (6538139823/10⁹, 6538139824/10⁹). n_hi=29, n_lo=24 -/
theorem log_enc_691 :
    (6538139823 : ℝ) / 10^9 < Real.log 691 ∧
    Real.log 691 < (6538139824 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 691) ?_ ?_
  · -- exp(6538139823/10^9) < 691: use 24 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 24) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 691 < exp(6538139824/10^9): use 29 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 29) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

end Goldbach
