/-
  Goldbach/PrimeLogEnclosures.lean
  1229 theorems proving log(p) enclosures for all primes p ≤ 9973.

  For each prime p, we prove:
    ⌊log(p)·10⁹⌋/10⁹ < log(p) < (⌊log(p)·10⁹⌋+1)/10⁹

  Strategy:
  - Hi-side (p < exp(hi)): via S_n(hi) ≤ exp(hi) [Mathlib: sum_le_exp_of_nonneg]
    then p < S_n(hi) [by norm_num after Finset.sum unfolding].
  - Lo-side (exp(lo) < p): via exp(lo) ≤ S_n(lo) + tail [ExpBounds]
    then S_n(lo) + tail < p [by norm_num].

  Sorry count: 0

  Generated by generate_prime_enclosures_v4.py
-/
import Goldbach.ExpBounds
import Goldbach.A2CertificateData
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Analysis.SpecialFunctions.Exp
import Mathlib.Data.Real.Basic
import Mathlib.Tactic

namespace Goldbach

open Finset Real BigOperators

/-! ## Individual prime log enclosures

Each theorem has the form:
  `lo/10^9 < log(p) < hi/10^9`
proved via the master combinator `log_enclosure_of_exp_bounds`.
-/

/-- log(9829) ∈ (9193092478/10⁹, 9193092479/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9829 :
    (9193092478 : ℝ) / 10^9 < Real.log 9829 ∧
    Real.log 9829 < (9193092479 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9829) ?_ ?_
  · -- exp(9193092478/10^9) < 9829: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9829 < exp(9193092479/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9833) ∈ (9193499354/10⁹, 9193499355/10⁹). n_hi=35, n_lo=30 -/
theorem log_enc_9833 :
    (9193499354 : ℝ) / 10^9 < Real.log 9833 ∧
    Real.log 9833 < (9193499355 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9833) ?_ ?_
  · -- exp(9193499354/10^9) < 9833: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9833 < exp(9193499355/10^9): use 35 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 35) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9839) ∈ (9194109358/10⁹, 9194109359/10⁹). n_hi=35, n_lo=29 -/
theorem log_enc_9839 :
    (9194109358 : ℝ) / 10^9 < Real.log 9839 ∧
    Real.log 9839 < (9194109359 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9839) ?_ ?_
  · -- exp(9194109358/10^9) < 9839: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9839 < exp(9194109359/10^9): use 35 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 35) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9851) ∈ (9195328251/10⁹, 9195328252/10⁹). n_hi=35, n_lo=29 -/
theorem log_enc_9851 :
    (9195328251 : ℝ) / 10^9 < Real.log 9851 ∧
    Real.log 9851 < (9195328252 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9851) ?_ ?_
  · -- exp(9195328251/10^9) < 9851: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9851 < exp(9195328252/10^9): use 35 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 35) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9857) ∈ (9195937141/10⁹, 9195937142/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9857 :
    (9195937141 : ℝ) / 10^9 < Real.log 9857 ∧
    Real.log 9857 < (9195937142 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9857) ?_ ?_
  · -- exp(9195937141/10^9) < 9857: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9857 < exp(9195937142/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9859) ∈ (9196140022/10⁹, 9196140023/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9859 :
    (9196140022 : ℝ) / 10^9 < Real.log 9859 ∧
    Real.log 9859 < (9196140023 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9859) ?_ ?_
  · -- exp(9196140022/10^9) < 9859: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9859 < exp(9196140023/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

end Goldbach
