/-
  Goldbach/PrimeLogEnclosures.lean
  1229 theorems proving log(p) enclosures for all primes p ≤ 9973.

  For each prime p, we prove:
    ⌊log(p)·10⁹⌋/10⁹ < log(p) < (⌊log(p)·10⁹⌋+1)/10⁹

  Strategy:
  - Hi-side (p < exp(hi)): via S_n(hi) ≤ exp(hi) [Mathlib: sum_le_exp_of_nonneg]
    then p < S_n(hi) [by norm_num after Finset.sum unfolding].
  - Lo-side (exp(lo) < p): via exp(lo) ≤ S_n(lo) + tail [ExpBounds]
    then S_n(lo) + tail < p [by norm_num].

  Sorry count: 0

  Generated by generate_prime_enclosures_v4.py
-/
import Goldbach.ExpBounds
import Goldbach.A2CertificateData
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Analysis.SpecialFunctions.Exp
import Mathlib.Data.Real.Basic
import Mathlib.Tactic

namespace Goldbach

open Finset Real BigOperators

/-! ## Individual prime log enclosures

Each theorem has the form:
  `lo/10^9 < log(p) < hi/10^9`
proved via the master combinator `log_enclosure_of_exp_bounds`.
-/

/-- log(4639) ∈ (8442254104/10⁹, 8442254105/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4639 :
    (8442254104 : ℝ) / 10^9 < Real.log 4639 ∧
    Real.log 4639 < (8442254105 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4639) ?_ ?_
  · -- exp(8442254104/10^9) < 4639: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4639 < exp(8442254105/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4643) ∈ (8443115988/10⁹, 8443115989/10⁹). n_hi=32, n_lo=31 -/
theorem log_enc_4643 :
    (8443115988 : ℝ) / 10^9 < Real.log 4643 ∧
    Real.log 4643 < (8443115989 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4643) ?_ ?_
  · -- exp(8443115988/10^9) < 4643: use 31 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 31) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4643 < exp(8443115989/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4649) ∈ (8444407421/10⁹, 8444407422/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4649 :
    (8444407421 : ℝ) / 10^9 < Real.log 4649 ∧
    Real.log 4649 < (8444407422 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4649) ?_ ?_
  · -- exp(8444407421/10^9) < 4649: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4649 < exp(8444407422/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4651) ∈ (8444837529/10⁹, 8444837530/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4651 :
    (8444837529 : ℝ) / 10^9 < Real.log 4651 ∧
    Real.log 4651 < (8444837530 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4651) ?_ ?_
  · -- exp(8444837529/10^9) < 4651: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4651 < exp(8444837530/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4657) ∈ (8446126742/10⁹, 8446126743/10⁹). n_hi=35, n_lo=28 -/
theorem log_enc_4657 :
    (8446126742 : ℝ) / 10^9 < Real.log 4657 ∧
    Real.log 4657 < (8446126743 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4657) ?_ ?_
  · -- exp(8446126742/10^9) < 4657: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4657 < exp(8446126743/10^9): use 35 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 35) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4663) ∈ (8447414296/10⁹, 8447414297/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4663 :
    (8447414296 : ℝ) / 10^9 < Real.log 4663 ∧
    Real.log 4663 < (8447414297 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4663) ?_ ?_
  · -- exp(8447414296/10^9) < 4663: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4663 < exp(8447414297/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4673) ∈ (8449556542/10⁹, 8449556543/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4673 :
    (8449556542 : ℝ) / 10^9 < Real.log 4673 ∧
    Real.log 4673 < (8449556543 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4673) ?_ ?_
  · -- exp(8449556542/10^9) < 4673: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4673 < exp(8449556543/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4679) ∈ (8450839690/10⁹, 8450839691/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4679 :
    (8450839690 : ℝ) / 10^9 < Real.log 4679 ∧
    Real.log 4679 < (8450839691 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4679) ?_ ?_
  · -- exp(8450839690/10^9) < 4679: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4679 < exp(8450839691/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4691) ∈ (8453401058/10⁹, 8453401059/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4691 :
    (8453401058 : ℝ) / 10^9 < Real.log 4691 ∧
    Real.log 4691 < (8453401059 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4691) ?_ ?_
  · -- exp(8453401058/10^9) < 4691: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4691 < exp(8453401059/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4703) ∈ (8455955881/10⁹, 8455955882/10⁹). n_hi=34, n_lo=28 -/
theorem log_enc_4703 :
    (8455955881 : ℝ) / 10^9 < Real.log 4703 ∧
    Real.log 4703 < (8455955882 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4703) ?_ ?_
  · -- exp(8455955881/10^9) < 4703: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4703 < exp(8455955882/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4721) ∈ (8459775920/10⁹, 8459775921/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4721 :
    (8459775920 : ℝ) / 10^9 < Real.log 4721 ∧
    Real.log 4721 < (8459775921 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4721) ?_ ?_
  · -- exp(8459775920/10^9) < 4721: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4721 < exp(8459775921/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4723) ∈ (8460199469/10⁹, 8460199470/10⁹). n_hi=34, n_lo=28 -/
theorem log_enc_4723 :
    (8460199469 : ℝ) / 10^9 < Real.log 4723 ∧
    Real.log 4723 < (8460199470 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4723) ?_ ?_
  · -- exp(8460199469/10^9) < 4723: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4723 < exp(8460199470/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4729) ∈ (8461469042/10⁹, 8461469043/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4729 :
    (8461469042 : ℝ) / 10^9 < Real.log 4729 ∧
    Real.log 4729 < (8461469043 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4729) ?_ ?_
  · -- exp(8461469042/10^9) < 4729: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4729 < exp(8461469043/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4733) ∈ (8462314529/10⁹, 8462314530/10⁹). n_hi=34, n_lo=28 -/
theorem log_enc_4733 :
    (8462314529 : ℝ) / 10^9 < Real.log 4733 ∧
    Real.log 4733 < (8462314530 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4733) ?_ ?_
  · -- exp(8462314529/10^9) < 4733: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4733 < exp(8462314530/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4751) ∈ (8466110401/10⁹, 8466110402/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4751 :
    (8466110401 : ℝ) / 10^9 < Real.log 4751 ∧
    Real.log 4751 < (8466110402 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4751) ?_ ?_
  · -- exp(8466110401/10^9) < 4751: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4751 < exp(8466110402/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4759) ∈ (8467792841/10⁹, 8467792842/10⁹). n_hi=32, n_lo=30 -/
theorem log_enc_4759 :
    (8467792841 : ℝ) / 10^9 < Real.log 4759 ∧
    Real.log 4759 < (8467792842 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4759) ?_ ?_
  · -- exp(8467792841/10^9) < 4759: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4759 < exp(8467792842/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4783) ∈ (8472823243/10⁹, 8472823244/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4783 :
    (8472823243 : ℝ) / 10^9 < Real.log 4783 ∧
    Real.log 4783 < (8472823244 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4783) ?_ ?_
  · -- exp(8472823243/10^9) < 4783: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4783 < exp(8472823244/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4787) ∈ (8473659189/10⁹, 8473659190/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4787 :
    (8473659189 : ℝ) / 10^9 < Real.log 4787 ∧
    Real.log 4787 < (8473659190 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4787) ?_ ?_
  · -- exp(8473659189/10^9) < 4787: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4787 < exp(8473659190/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4789) ∈ (8474076900/10⁹, 8474076901/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4789 :
    (8474076900 : ℝ) / 10^9 < Real.log 4789 ∧
    Real.log 4789 < (8474076901 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4789) ?_ ?_
  · -- exp(8474076900/10^9) < 4789: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4789 < exp(8474076901/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4793) ∈ (8474911799/10⁹, 8474911800/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4793 :
    (8474911799 : ℝ) / 10^9 < Real.log 4793 ∧
    Real.log 4793 < (8474911800 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4793) ?_ ?_
  · -- exp(8474911799/10^9) < 4793: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4793 < exp(8474911800/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4799) ∈ (8476162841/10⁹, 8476162842/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4799 :
    (8476162841 : ℝ) / 10^9 < Real.log 4799 ∧
    Real.log 4799 < (8476162842 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4799) ?_ ?_
  · -- exp(8476162841/10^9) < 4799: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4799 < exp(8476162842/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4801) ∈ (8476579508/10⁹, 8476579509/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4801 :
    (8476579508 : ℝ) / 10^9 < Real.log 4801 ∧
    Real.log 4801 < (8476579509 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4801) ?_ ?_
  · -- exp(8476579508/10^9) < 4801: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4801 < exp(8476579509/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4813) ∈ (8479075869/10⁹, 8479075870/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4813 :
    (8479075869 : ℝ) / 10^9 < Real.log 4813 ∧
    Real.log 4813 < (8479075870 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4813) ?_ ?_
  · -- exp(8479075869/10^9) < 4813: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4813 < exp(8479075870/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4817) ∈ (8479906606/10⁹, 8479906607/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4817 :
    (8479906606 : ℝ) / 10^9 < Real.log 4817 ∧
    Real.log 4817 < (8479906607 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4817) ?_ ?_
  · -- exp(8479906606/10^9) < 4817: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4817 < exp(8479906607/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4831) ∈ (8482808764/10⁹, 8482808765/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4831 :
    (8482808764 : ℝ) / 10^9 < Real.log 4831 ∧
    Real.log 4831 < (8482808765 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4831) ?_ ?_
  · -- exp(8482808764/10^9) < 4831: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4831 < exp(8482808765/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4861) ∈ (8488999457/10⁹, 8488999458/10⁹). n_hi=32, n_lo=30 -/
theorem log_enc_4861 :
    (8488999457 : ℝ) / 10^9 < Real.log 4861 ∧
    Real.log 4861 < (8488999458 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4861) ?_ ?_
  · -- exp(8488999457/10^9) < 4861: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4861 < exp(8488999458/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4871) ∈ (8491054533/10⁹, 8491054534/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4871 :
    (8491054533 : ℝ) / 10^9 < Real.log 4871 ∧
    Real.log 4871 < (8491054534 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4871) ?_ ?_
  · -- exp(8491054533/10^9) < 4871: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4871 < exp(8491054534/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4877) ∈ (8492285555/10⁹, 8492285556/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4877 :
    (8492285555 : ℝ) / 10^9 < Real.log 4877 ∧
    Real.log 4877 < (8492285556 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4877) ?_ ?_
  · -- exp(8492285555/10^9) < 4877: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4877 < exp(8492285556/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4889) ∈ (8494743062/10⁹, 8494743063/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4889 :
    (8494743062 : ℝ) / 10^9 < Real.log 4889 ∧
    Real.log 4889 < (8494743063 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4889) ?_ ?_
  · -- exp(8494743062/10^9) < 4889: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4889 < exp(8494743063/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4903) ∈ (8497602541/10⁹, 8497602542/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4903 :
    (8497602541 : ℝ) / 10^9 < Real.log 4903 ∧
    Real.log 4903 < (8497602542 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4903) ?_ ?_
  · -- exp(8497602541/10^9) < 4903: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4903 < exp(8497602542/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4909) ∈ (8498825534/10⁹, 8498825535/10⁹). n_hi=32, n_lo=30 -/
theorem log_enc_4909 :
    (8498825534 : ℝ) / 10^9 < Real.log 4909 ∧
    Real.log 4909 < (8498825535 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4909) ?_ ?_
  · -- exp(8498825534/10^9) < 4909: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4909 < exp(8498825535/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4919) ∈ (8500860536/10⁹, 8500860537/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4919 :
    (8500860536 : ℝ) / 10^9 < Real.log 4919 ∧
    Real.log 4919 < (8500860537 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4919) ?_ ?_
  · -- exp(8500860536/10^9) < 4919: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4919 < exp(8500860537/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4931) ∈ (8503297086/10⁹, 8503297087/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4931 :
    (8503297086 : ℝ) / 10^9 < Real.log 4931 ∧
    Real.log 4931 < (8503297087 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4931) ?_ ?_
  · -- exp(8503297086/10^9) < 4931: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4931 < exp(8503297087/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4933) ∈ (8503702601/10⁹, 8503702602/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4933 :
    (8503702601 : ℝ) / 10^9 < Real.log 4933 ∧
    Real.log 4933 < (8503702602 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4933) ?_ ?_
  · -- exp(8503702601/10^9) < 4933: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4933 < exp(8503702602/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4937) ∈ (8504513138/10⁹, 8504513139/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4937 :
    (8504513138 : ℝ) / 10^9 < Real.log 4937 ∧
    Real.log 4937 < (8504513139 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4937) ?_ ?_
  · -- exp(8504513138/10^9) < 4937: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4937 < exp(8504513139/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4943) ∈ (8505727713/10⁹, 8505727714/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4943 :
    (8505727713 : ℝ) / 10^9 < Real.log 4943 ∧
    Real.log 4943 < (8505727714 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4943) ?_ ?_
  · -- exp(8505727713/10^9) < 4943: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4943 < exp(8505727714/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4951) ∈ (8507344855/10⁹, 8507344856/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_4951 :
    (8507344855 : ℝ) / 10^9 < Real.log 4951 ∧
    Real.log 4951 < (8507344856 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4951) ?_ ?_
  · -- exp(8507344855/10^9) < 4951: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4951 < exp(8507344856/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4957) ∈ (8508555998/10⁹, 8508555999/10⁹). n_hi=32, n_lo=31 -/
theorem log_enc_4957 :
    (8508555998 : ℝ) / 10^9 < Real.log 4957 ∧
    Real.log 4957 < (8508555999 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4957) ?_ ?_
  · -- exp(8508555998/10^9) < 4957: use 31 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 31) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4957 < exp(8508555999/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4967) ∈ (8510571315/10⁹, 8510571316/10⁹). n_hi=32, n_lo=30 -/
theorem log_enc_4967 :
    (8510571315 : ℝ) / 10^9 < Real.log 4967 ∧
    Real.log 4967 < (8510571316 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4967) ?_ ?_
  · -- exp(8510571315/10^9) < 4967: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4967 < exp(8510571316/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4969) ∈ (8510973891/10⁹, 8510973892/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4969 :
    (8510973891 : ℝ) / 10^9 < Real.log 4969 ∧
    Real.log 4969 < (8510973892 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4969) ?_ ?_
  · -- exp(8510973891/10^9) < 4969: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4969 < exp(8510973892/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4973) ∈ (8511778558/10⁹, 8511778559/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_4973 :
    (8511778558 : ℝ) / 10^9 < Real.log 4973 ∧
    Real.log 4973 < (8511778559 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4973) ?_ ?_
  · -- exp(8511778558/10^9) < 4973: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4973 < exp(8511778559/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4987) ∈ (8514589805/10⁹, 8514589806/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_4987 :
    (8514589805 : ℝ) / 10^9 < Real.log 4987 ∧
    Real.log 4987 < (8514589806 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4987) ?_ ?_
  · -- exp(8514589805/10^9) < 4987: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4987 < exp(8514589806/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4993) ∈ (8515792210/10⁹, 8515792211/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_4993 :
    (8515792210 : ℝ) / 10^9 < Real.log 4993 ∧
    Real.log 4993 < (8515792211 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4993) ?_ ?_
  · -- exp(8515792210/10^9) < 4993: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4993 < exp(8515792211/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(4999) ∈ (8516993171/10⁹, 8516993172/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_4999 :
    (8516993171 : ℝ) / 10^9 < Real.log 4999 ∧
    Real.log 4999 < (8516993172 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 4999) ?_ ?_
  · -- exp(8516993171/10^9) < 4999: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 4999 < exp(8516993172/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5003) ∈ (8517793011/10⁹, 8517793012/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5003 :
    (8517793011 : ℝ) / 10^9 < Real.log 5003 ∧
    Real.log 5003 < (8517793012 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5003) ?_ ?_
  · -- exp(8517793011/10^9) < 5003: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5003 < exp(8517793012/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5009) ∈ (8518991573/10⁹, 8518991574/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_5009 :
    (8518991573 : ℝ) / 10^9 < Real.log 5009 ∧
    Real.log 5009 < (8518991574 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5009) ?_ ?_
  · -- exp(8518991573/10^9) < 5009: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5009 < exp(8518991574/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5011) ∈ (8519390774/10⁹, 8519390775/10⁹). n_hi=34, n_lo=28 -/
theorem log_enc_5011 :
    (8519390774 : ℝ) / 10^9 < Real.log 5011 ∧
    Real.log 5011 < (8519390775 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5011) ?_ ?_
  · -- exp(8519390774/10^9) < 5011: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5011 < exp(8519390775/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5021) ∈ (8521384396/10⁹, 8521384397/10⁹). n_hi=32, n_lo=31 -/
theorem log_enc_5021 :
    (8521384396 : ℝ) / 10^9 < Real.log 5021 ∧
    Real.log 5021 < (8521384397 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5021) ?_ ?_
  · -- exp(8521384396/10^9) < 5021: use 31 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 31) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5021 < exp(8521384397/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5023) ∈ (8521782643/10⁹, 8521782644/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_5023 :
    (8521782643 : ℝ) / 10^9 < Real.log 5023 ∧
    Real.log 5023 < (8521782644 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5023) ?_ ?_
  · -- exp(8521782643/10^9) < 5023: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5023 < exp(8521782644/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5039) ∈ (8524962928/10⁹, 8524962929/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_5039 :
    (8524962928 : ℝ) / 10^9 < Real.log 5039 ∧
    Real.log 5039 < (8524962929 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5039) ?_ ?_
  · -- exp(8524962928/10^9) < 5039: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5039 < exp(8524962929/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5051) ∈ (8527341522/10⁹, 8527341523/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5051 :
    (8527341522 : ℝ) / 10^9 < Real.log 5051 ∧
    Real.log 5051 < (8527341523 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5051) ?_ ?_
  · -- exp(8527341522/10^9) < 5051: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5051 < exp(8527341523/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5059) ∈ (8528924114/10⁹, 8528924115/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_5059 :
    (8528924114 : ℝ) / 10^9 < Real.log 5059 ∧
    Real.log 5059 < (8528924115 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5059) ?_ ?_
  · -- exp(8528924114/10^9) < 5059: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5059 < exp(8528924115/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5077) ∈ (8532475814/10⁹, 8532475815/10⁹). n_hi=34, n_lo=28 -/
theorem log_enc_5077 :
    (8532475814 : ℝ) / 10^9 < Real.log 5077 ∧
    Real.log 5077 < (8532475815 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5077) ?_ ?_
  · -- exp(8532475814/10^9) < 5077: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5077 < exp(8532475815/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5081) ∈ (8533263371/10⁹, 8533263372/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_5081 :
    (8533263371 : ℝ) / 10^9 < Real.log 5081 ∧
    Real.log 5081 < (8533263372 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5081) ?_ ?_
  · -- exp(8533263371/10^9) < 5081: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5081 < exp(8533263372/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5087) ∈ (8534443544/10⁹, 8534443545/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_5087 :
    (8534443544 : ℝ) / 10^9 < Real.log 5087 ∧
    Real.log 5087 < (8534443545 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5087) ?_ ?_
  · -- exp(8534443544/10^9) < 5087: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5087 < exp(8534443545/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5099) ∈ (8536799721/10⁹, 8536799722/10⁹). n_hi=32, n_lo=30 -/
theorem log_enc_5099 :
    (8536799721 : ℝ) / 10^9 < Real.log 5099 ∧
    Real.log 5099 < (8536799722 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5099) ?_ ?_
  · -- exp(8536799721/10^9) < 5099: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5099 < exp(8536799722/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5101) ∈ (8537191877/10⁹, 8537191878/10⁹). n_hi=34, n_lo=28 -/
theorem log_enc_5101 :
    (8537191877 : ℝ) / 10^9 < Real.log 5101 ∧
    Real.log 5101 < (8537191878 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5101) ?_ ?_
  · -- exp(8537191877/10^9) < 5101: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5101 < exp(8537191878/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5107) ∈ (8538367426/10⁹, 8538367427/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_5107 :
    (8538367426 : ℝ) / 10^9 < Real.log 5107 ∧
    Real.log 5107 < (8538367427 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5107) ?_ ?_
  · -- exp(8538367426/10^9) < 5107: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5107 < exp(8538367427/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5113) ∈ (8539541595/10⁹, 8539541596/10⁹). n_hi=32, n_lo=30 -/
theorem log_enc_5113 :
    (8539541595 : ℝ) / 10^9 < Real.log 5113 ∧
    Real.log 5113 < (8539541596 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5113) ?_ ?_
  · -- exp(8539541595/10^9) < 5113: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5113 < exp(8539541596/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5119) ∈ (8540714386/10⁹, 8540714387/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5119 :
    (8540714386 : ℝ) / 10^9 < Real.log 5119 ∧
    Real.log 5119 < (8540714387 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5119) ?_ ?_
  · -- exp(8540714386/10^9) < 5119: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5119 < exp(8540714387/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5147) ∈ (8546169299/10⁹, 8546169300/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_5147 :
    (8546169299 : ℝ) / 10^9 < Real.log 5147 ∧
    Real.log 5147 < (8546169300 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5147) ?_ ?_
  · -- exp(8546169299/10^9) < 5147: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5147 < exp(8546169300/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5153) ∈ (8547334348/10⁹, 8547334349/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_5153 :
    (8547334348 : ℝ) / 10^9 < Real.log 5153 ∧
    Real.log 5153 < (8547334349 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5153) ?_ ?_
  · -- exp(8547334348/10^9) < 5153: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5153 < exp(8547334349/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5167) ∈ (8550047528/10⁹, 8550047529/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_5167 :
    (8550047528 : ℝ) / 10^9 < Real.log 5167 ∧
    Real.log 5167 < (8550047529 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5167) ?_ ?_
  · -- exp(8550047528/10^9) < 5167: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5167 < exp(8550047529/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5171) ∈ (8550821372/10⁹, 8550821373/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5171 :
    (8550821372 : ℝ) / 10^9 < Real.log 5171 ∧
    Real.log 5171 < (8550821373 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5171) ?_ ?_
  · -- exp(8550821372/10^9) < 5171: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5171 < exp(8550821373/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5179) ∈ (8552367266/10⁹, 8552367267/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5179 :
    (8552367266 : ℝ) / 10^9 < Real.log 5179 ∧
    Real.log 5179 < (8552367267 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5179) ?_ ?_
  · -- exp(8552367266/10^9) < 5179: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5179 < exp(8552367267/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5189) ∈ (8554296279/10⁹, 8554296280/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5189 :
    (8554296279 : ℝ) / 10^9 < Real.log 5189 ∧
    Real.log 5189 < (8554296280 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5189) ?_ ?_
  · -- exp(8554296279/10^9) < 5189: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5189 < exp(8554296280/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5197) ∈ (8555836815/10⁹, 8555836816/10⁹). n_hi=32, n_lo=32 -/
theorem log_enc_5197 :
    (8555836815 : ℝ) / 10^9 < Real.log 5197 ∧
    Real.log 5197 < (8555836816 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5197) ?_ ?_
  · -- exp(8555836815/10^9) < 5197: use 32 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 32) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5197 < exp(8555836816/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5209) ∈ (8558143177/10⁹, 8558143178/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_5209 :
    (8558143177 : ℝ) / 10^9 < Real.log 5209 ∧
    Real.log 5209 < (8558143178 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5209) ?_ ?_
  · -- exp(8558143177/10^9) < 5209: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5209 < exp(8558143178/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5227) ∈ (8561592778/10⁹, 8561592779/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_5227 :
    (8561592778 : ℝ) / 10^9 < Real.log 5227 ∧
    Real.log 5227 < (8561592779 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5227) ?_ ?_
  · -- exp(8561592778/10^9) < 5227: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5227 < exp(8561592779/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5231) ∈ (8562357743/10⁹, 8562357744/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5231 :
    (8562357743 : ℝ) / 10^9 < Real.log 5231 ∧
    Real.log 5231 < (8562357744 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5231) ?_ ?_
  · -- exp(8562357743/10^9) < 5231: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5231 < exp(8562357744/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5233) ∈ (8562740006/10⁹, 8562740007/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5233 :
    (8562740006 : ℝ) / 10^9 < Real.log 5233 ∧
    Real.log 5233 < (8562740007 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5233) ?_ ?_
  · -- exp(8562740006/10^9) < 5233: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5233 < exp(8562740007/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5237) ∈ (8563504094/10⁹, 8563504095/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_5237 :
    (8563504094 : ℝ) / 10^9 < Real.log 5237 ∧
    Real.log 5237 < (8563504095 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5237) ?_ ?_
  · -- exp(8563504094/10^9) < 5237: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5237 < exp(8563504095/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5261) ∈ (8568076401/10⁹, 8568076402/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_5261 :
    (8568076401 : ℝ) / 10^9 < Real.log 5261 ∧
    Real.log 5261 < (8568076402 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5261) ?_ ?_
  · -- exp(8568076401/10^9) < 5261: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5261 < exp(8568076402/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5273) ∈ (8570354739/10⁹, 8570354740/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5273 :
    (8570354739 : ℝ) / 10^9 < Real.log 5273 ∧
    Real.log 5273 < (8570354740 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5273) ?_ ?_
  · -- exp(8570354739/10^9) < 5273: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5273 < exp(8570354740/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5279) ∈ (8571491964/10⁹, 8571491965/10⁹). n_hi=34, n_lo=28 -/
theorem log_enc_5279 :
    (8571491964 : ℝ) / 10^9 < Real.log 5279 ∧
    Real.log 5279 < (8571491965 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5279) ?_ ?_
  · -- exp(8571491964/10^9) < 5279: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5279 < exp(8571491965/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5281) ∈ (8571870752/10⁹, 8571870753/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_5281 :
    (8571870752 : ℝ) / 10^9 < Real.log 5281 ∧
    Real.log 5281 < (8571870753 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5281) ?_ ?_
  · -- exp(8571870752/10^9) < 5281: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5281 < exp(8571870753/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5297) ∈ (8574895901/10⁹, 8574895902/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5297 :
    (8574895901 : ℝ) / 10^9 < Real.log 5297 ∧
    Real.log 5297 < (8574895902 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5297) ?_ ?_
  · -- exp(8574895901/10^9) < 5297: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5297 < exp(8574895902/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5303) ∈ (8576027977/10⁹, 8576027978/10⁹). n_hi=32, n_lo=30 -/
theorem log_enc_5303 :
    (8576027977 : ℝ) / 10^9 < Real.log 5303 ∧
    Real.log 5303 < (8576027978 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5303) ?_ ?_
  · -- exp(8576027977/10^9) < 5303: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5303 < exp(8576027978/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5309) ∈ (8577158772/10⁹, 8577158773/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5309 :
    (8577158772 : ℝ) / 10^9 < Real.log 5309 ∧
    Real.log 5309 < (8577158773 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5309) ?_ ?_
  · -- exp(8577158772/10^9) < 5309: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5309 < exp(8577158773/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5323) ∈ (8579792333/10⁹, 8579792334/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_5323 :
    (8579792333 : ℝ) / 10^9 < Real.log 5323 ∧
    Real.log 5323 < (8579792334 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5323) ?_ ?_
  · -- exp(8579792333/10^9) < 5323: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5323 < exp(8579792334/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5333) ∈ (8581669210/10⁹, 8581669211/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5333 :
    (8581669210 : ℝ) / 10^9 < Real.log 5333 ∧
    Real.log 5333 < (8581669211 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5333) ?_ ?_
  · -- exp(8581669210/10^9) < 5333: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5333 < exp(8581669211/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5347) ∈ (8584290934/10⁹, 8584290935/10⁹). n_hi=34, n_lo=28 -/
theorem log_enc_5347 :
    (8584290934 : ℝ) / 10^9 < Real.log 5347 ∧
    Real.log 5347 < (8584290935 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5347) ?_ ?_
  · -- exp(8584290934/10^9) < 5347: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5347 < exp(8584290935/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5351) ∈ (8585038738/10⁹, 8585038739/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5351 :
    (8585038738 : ℝ) / 10^9 < Real.log 5351 ∧
    Real.log 5351 < (8585038739 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5351) ?_ ?_
  · -- exp(8585038738/10^9) < 5351: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5351 < exp(8585038739/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5381) ∈ (8590629509/10⁹, 8590629510/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5381 :
    (8590629509 : ℝ) / 10^9 < Real.log 5381 ∧
    Real.log 5381 < (8590629510 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5381) ?_ ?_
  · -- exp(8590629509/10^9) < 5381: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5381 < exp(8590629510/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5387) ∈ (8591743922/10⁹, 8591743923/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5387 :
    (8591743922 : ℝ) / 10^9 < Real.log 5387 ∧
    Real.log 5387 < (8591743923 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5387) ?_ ?_
  · -- exp(8591743922/10^9) < 5387: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5387 < exp(8591743923/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5393) ∈ (8592857095/10⁹, 8592857096/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5393 :
    (8592857095 : ℝ) / 10^9 < Real.log 5393 ∧
    Real.log 5393 < (8592857096 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5393) ?_ ?_
  · -- exp(8592857095/10^9) < 5393: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5393 < exp(8592857096/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5399) ∈ (8593969030/10⁹, 8593969031/10⁹). n_hi=32, n_lo=29 -/
theorem log_enc_5399 :
    (8593969030 : ℝ) / 10^9 < Real.log 5399 ∧
    Real.log 5399 < (8593969031 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5399) ?_ ?_
  · -- exp(8593969030/10^9) < 5399: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5399 < exp(8593969031/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5407) ∈ (8595449689/10⁹, 8595449690/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5407 :
    (8595449689 : ℝ) / 10^9 < Real.log 5407 ∧
    Real.log 5407 < (8595449690 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5407) ?_ ?_
  · -- exp(8595449689/10^9) < 5407: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5407 < exp(8595449690/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5413) ∈ (8596558746/10⁹, 8596558747/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_5413 :
    (8596558746 : ℝ) / 10^9 < Real.log 5413 ∧
    Real.log 5413 < (8596558747 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5413) ?_ ?_
  · -- exp(8596558746/10^9) < 5413: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5413 < exp(8596558747/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5417) ∈ (8597297435/10⁹, 8597297436/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5417 :
    (8597297435 : ℝ) / 10^9 < Real.log 5417 ∧
    Real.log 5417 < (8597297436 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5417) ?_ ?_
  · -- exp(8597297435/10^9) < 5417: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5417 < exp(8597297436/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5419) ∈ (8597666575/10⁹, 8597666576/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5419 :
    (8597666575 : ℝ) / 10^9 < Real.log 5419 ∧
    Real.log 5419 < (8597666576 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5419) ?_ ?_
  · -- exp(8597666575/10^9) < 5419: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5419 < exp(8597666576/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5431) ∈ (8599878558/10⁹, 8599878559/10⁹). n_hi=32, n_lo=31 -/
theorem log_enc_5431 :
    (8599878558 : ℝ) / 10^9 < Real.log 5431 ∧
    Real.log 5431 < (8599878559 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5431) ?_ ?_
  · -- exp(8599878558/10^9) < 5431: use 31 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 31) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5431 < exp(8599878559/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5437) ∈ (8600982717/10⁹, 8600982718/10⁹). n_hi=32, n_lo=30 -/
theorem log_enc_5437 :
    (8600982717 : ℝ) / 10^9 < Real.log 5437 ∧
    Real.log 5437 < (8600982718 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5437) ?_ ?_
  · -- exp(8600982717/10^9) < 5437: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5437 < exp(8600982718/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5441) ∈ (8601718146/10⁹, 8601718147/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5441 :
    (8601718146 : ℝ) / 10^9 < Real.log 5441 ∧
    Real.log 5441 < (8601718147 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5441) ?_ ?_
  · -- exp(8601718146/10^9) < 5441: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5441 < exp(8601718147/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5443) ∈ (8602085658/10⁹, 8602085659/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5443 :
    (8602085658 : ℝ) / 10^9 < Real.log 5443 ∧
    Real.log 5443 < (8602085659 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5443) ?_ ?_
  · -- exp(8602085658/10^9) < 5443: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5443 < exp(8602085659/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5449) ∈ (8603187384/10⁹, 8603187385/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5449 :
    (8603187384 : ℝ) / 10^9 < Real.log 5449 ∧
    Real.log 5449 < (8603187385 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5449) ?_ ?_
  · -- exp(8603187384/10^9) < 5449: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5449 < exp(8603187385/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5471) ∈ (8607216694/10⁹, 8607216695/10⁹). n_hi=32, n_lo=30 -/
theorem log_enc_5471 :
    (8607216694 : ℝ) / 10^9 < Real.log 5471 ∧
    Real.log 5471 < (8607216695 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5471) ?_ ?_
  · -- exp(8607216694/10^9) < 5471: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5471 < exp(8607216695/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5477) ∈ (8608312784/10⁹, 8608312785/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_5477 :
    (8608312784 : ℝ) / 10^9 < Real.log 5477 ∧
    Real.log 5477 < (8608312785 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5477) ?_ ?_
  · -- exp(8608312784/10^9) < 5477: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5477 < exp(8608312785/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5479) ∈ (8608677881/10⁹, 8608677882/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5479 :
    (8608677881 : ℝ) / 10^9 < Real.log 5479 ∧
    Real.log 5479 < (8608677882 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5479) ?_ ?_
  · -- exp(8608677881/10^9) < 5479: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5479 < exp(8608677882/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5483) ∈ (8609407675/10⁹, 8609407676/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5483 :
    (8609407675 : ℝ) / 10^9 < Real.log 5483 ∧
    Real.log 5483 < (8609407676 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5483) ?_ ?_
  · -- exp(8609407675/10^9) < 5483: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5483 < exp(8609407676/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5501) ∈ (8612685172/10⁹, 8612685173/10⁹). n_hi=34, n_lo=28 -/
theorem log_enc_5501 :
    (8612685172 : ℝ) / 10^9 < Real.log 5501 ∧
    Real.log 5501 < (8612685173 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5501) ?_ ?_
  · -- exp(8612685172/10^9) < 5501: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5501 < exp(8612685173/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5503) ∈ (8613048677/10⁹, 8613048678/10⁹). n_hi=32, n_lo=30 -/
theorem log_enc_5503 :
    (8613048677 : ℝ) / 10^9 < Real.log 5503 ∧
    Real.log 5503 < (8613048678 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5503) ?_ ?_
  · -- exp(8613048677/10^9) < 5503: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5503 < exp(8613048678/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5507) ∈ (8613775289/10⁹, 8613775290/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5507 :
    (8613775289 : ℝ) / 10^9 < Real.log 5507 ∧
    Real.log 5507 < (8613775290 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5507) ?_ ?_
  · -- exp(8613775289/10^9) < 5507: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5507 < exp(8613775290/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5519) ∈ (8615951963/10⁹, 8615951964/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5519 :
    (8615951963 : ℝ) / 10^9 < Real.log 5519 ∧
    Real.log 5519 < (8615951964 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5519) ?_ ?_
  · -- exp(8615951963/10^9) < 5519: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5519 < exp(8615951964/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5521) ∈ (8616314282/10⁹, 8616314283/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5521 :
    (8616314282 : ℝ) / 10^9 < Real.log 5521 ∧
    Real.log 5521 < (8616314283 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5521) ?_ ?_
  · -- exp(8616314282/10^9) < 5521: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5521 < exp(8616314283/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5527) ∈ (8617400451/10⁹, 8617400452/10⁹). n_hi=34, n_lo=28 -/
theorem log_enc_5527 :
    (8617400451 : ℝ) / 10^9 < Real.log 5527 ∧
    Real.log 5527 < (8617400452 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5527) ?_ ?_
  · -- exp(8617400451/10^9) < 5527: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5527 < exp(8617400452/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5531) ∈ (8618123909/10⁹, 8618123910/10⁹). n_hi=36, n_lo=28 -/
theorem log_enc_5531 :
    (8618123909 : ℝ) / 10^9 < Real.log 5531 ∧
    Real.log 5531 < (8618123910 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5531) ?_ ?_
  · -- exp(8618123909/10^9) < 5531: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5531 < exp(8618123910/10^9): use 36 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 36) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5557) ∈ (8622813673/10⁹, 8622813674/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5557 :
    (8622813673 : ℝ) / 10^9 < Real.log 5557 ∧
    Real.log 5557 < (8622813674 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5557) ?_ ?_
  · -- exp(8622813673/10^9) < 5557: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5557 < exp(8622813674/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5563) ∈ (8623892810/10⁹, 8623892811/10⁹). n_hi=32, n_lo=30 -/
theorem log_enc_5563 :
    (8623892810 : ℝ) / 10^9 < Real.log 5563 ∧
    Real.log 5563 < (8623892811 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5563) ?_ ?_
  · -- exp(8623892810/10^9) < 5563: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5563 < exp(8623892811/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5569) ∈ (8624970783/10⁹, 8624970784/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5569 :
    (8624970783 : ℝ) / 10^9 < Real.log 5569 ∧
    Real.log 5569 < (8624970784 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5569) ?_ ?_
  · -- exp(8624970783/10^9) < 5569: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5569 < exp(8624970784/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5573) ∈ (8625688787/10⁹, 8625688788/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5573 :
    (8625688787 : ℝ) / 10^9 < Real.log 5573 ∧
    Real.log 5573 < (8625688788 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5573) ?_ ?_
  · -- exp(8625688787/10^9) < 5573: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5573 < exp(8625688788/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5581) ∈ (8627123250/10⁹, 8627123251/10⁹). n_hi=33, n_lo=28 -/
theorem log_enc_5581 :
    (8627123250 : ℝ) / 10^9 < Real.log 5581 ∧
    Real.log 5581 < (8627123251 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5581) ?_ ?_
  · -- exp(8627123250/10^9) < 5581: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5581 < exp(8627123251/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5591) ∈ (8628913441/10⁹, 8628913442/10⁹). n_hi=32, n_lo=31 -/
theorem log_enc_5591 :
    (8628913441 : ℝ) / 10^9 < Real.log 5591 ∧
    Real.log 5591 < (8628913442 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5591) ?_ ?_
  · -- exp(8628913441/10^9) < 5591: use 31 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 31) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5591 < exp(8628913442/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5623) ∈ (8634620608/10⁹, 8634620609/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5623 :
    (8634620608 : ℝ) / 10^9 < Real.log 5623 ∧
    Real.log 5623 < (8634620609 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5623) ?_ ?_
  · -- exp(8634620608/10^9) < 5623: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5623 < exp(8634620609/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5639) ∈ (8637462023/10⁹, 8637462024/10⁹). n_hi=34, n_lo=28 -/
theorem log_enc_5639 :
    (8637462023 : ℝ) / 10^9 < Real.log 5639 ∧
    Real.log 5639 < (8637462024 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5639) ?_ ?_
  · -- exp(8637462023/10^9) < 5639: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5639 < exp(8637462024/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5641) ∈ (8637816633/10⁹, 8637816634/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5641 :
    (8637816633 : ℝ) / 10^9 < Real.log 5641 ∧
    Real.log 5641 < (8637816634 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5641) ?_ ?_
  · -- exp(8637816633/10^9) < 5641: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5641 < exp(8637816634/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5647) ∈ (8638879709/10⁹, 8638879710/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5647 :
    (8638879709 : ℝ) / 10^9 < Real.log 5647 ∧
    Real.log 5647 < (8638879710 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5647) ?_ ?_
  · -- exp(8638879709/10^9) < 5647: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5647 < exp(8638879710/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5651) ∈ (8639587799/10⁹, 8639587800/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5651 :
    (8639587799 : ℝ) / 10^9 < Real.log 5651 ∧
    Real.log 5651 < (8639587800 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5651) ?_ ?_
  · -- exp(8639587799/10^9) < 5651: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5651 < exp(8639587800/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5653) ∈ (8639941656/10⁹, 8639941657/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5653 :
    (8639941656 : ℝ) / 10^9 < Real.log 5653 ∧
    Real.log 5653 < (8639941657 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5653) ?_ ?_
  · -- exp(8639941656/10^9) < 5653: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5653 < exp(8639941657/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5657) ∈ (8640648995/10⁹, 8640648996/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5657 :
    (8640648995 : ℝ) / 10^9 < Real.log 5657 ∧
    Real.log 5657 < (8640648996 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5657) ?_ ?_
  · -- exp(8640648995/10^9) < 5657: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5657 < exp(8640648996/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5659) ∈ (8641002477/10⁹, 8641002478/10⁹). n_hi=32, n_lo=30 -/
theorem log_enc_5659 :
    (8641002477 : ℝ) / 10^9 < Real.log 5659 ∧
    Real.log 5659 < (8641002478 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5659) ?_ ?_
  · -- exp(8641002477/10^9) < 5659: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5659 < exp(8641002478/10^9): use 32 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 32) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5669) ∈ (8642768014/10⁹, 8642768015/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5669 :
    (8642768014 : ℝ) / 10^9 < Real.log 5669 ∧
    Real.log 5669 < (8642768015 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5669) ?_ ?_
  · -- exp(8642768014/10^9) < 5669: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5669 < exp(8642768015/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5683) ∈ (8645234541/10⁹, 8645234542/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5683 :
    (8645234541 : ℝ) / 10^9 < Real.log 5683 ∧
    Real.log 5683 < (8645234542 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5683) ?_ ?_
  · -- exp(8645234541/10^9) < 5683: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5683 < exp(8645234542/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5689) ∈ (8646289764/10⁹, 8646289765/10⁹). n_hi=33, n_lo=29 -/
theorem log_enc_5689 :
    (8646289764 : ℝ) / 10^9 < Real.log 5689 ∧
    Real.log 5689 < (8646289765 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5689) ?_ ?_
  · -- exp(8646289764/10^9) < 5689: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5689 < exp(8646289765/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(5693) ∈ (8646992628/10⁹, 8646992629/10⁹). n_hi=35, n_lo=28 -/
theorem log_enc_5693 :
    (8646992628 : ℝ) / 10^9 < Real.log 5693 ∧
    Real.log 5693 < (8646992629 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 5693) ?_ ?_
  · -- exp(8646992628/10^9) < 5693: use 28 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 28) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 5693 < exp(8646992629/10^9): use 35 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 35) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

end Goldbach
