/-
  Goldbach/PrimeLogEnclosures.lean
  1229 theorems proving log(p) enclosures for all primes p ≤ 9973.

  For each prime p, we prove:
    ⌊log(p)·10⁹⌋/10⁹ < log(p) < (⌊log(p)·10⁹⌋+1)/10⁹

  Strategy:
  - Hi-side (p < exp(hi)): via S_n(hi) ≤ exp(hi) [Mathlib: sum_le_exp_of_nonneg]
    then p < S_n(hi) [by norm_num after Finset.sum unfolding].
  - Lo-side (exp(lo) < p): via exp(lo) ≤ S_n(lo) + tail [ExpBounds]
    then S_n(lo) + tail < p [by norm_num].

  Sorry count: 0

  Generated by generate_prime_enclosures_v4.py
-/
import Goldbach.ExpBounds
import Goldbach.A2CertificateData
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Analysis.SpecialFunctions.Exp
import Mathlib.Data.Real.Basic
import Mathlib.Tactic

namespace Goldbach

open Finset Real BigOperators

/-! ## Individual prime log enclosures

Each theorem has the form:
  `lo/10^9 < log(p) < hi/10^9`
proved via the master combinator `log_enclosure_of_exp_bounds`.
-/

/-- log(9377) ∈ (9146015161/10⁹, 9146015162/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9377 :
    (9146015161 : ℝ) / 10^9 < Real.log 9377 ∧
    Real.log 9377 < (9146015162 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9377) ?_ ?_
  · -- exp(9146015161/10^9) < 9377: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9377 < exp(9146015162/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9391) ∈ (9147507062/10⁹, 9147507063/10⁹). n_hi=35, n_lo=29 -/
theorem log_enc_9391 :
    (9147507062 : ℝ) / 10^9 < Real.log 9391 ∧
    Real.log 9391 < (9147507063 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9391) ?_ ?_
  · -- exp(9147507062/10^9) < 9391: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9391 < exp(9147507063/10^9): use 35 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 35) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9397) ∈ (9148145768/10⁹, 9148145769/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9397 :
    (9148145768 : ℝ) / 10^9 < Real.log 9397 ∧
    Real.log 9397 < (9148145769 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9397) ?_ ?_
  · -- exp(9148145768/10^9) < 9397: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9397 < exp(9148145769/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9403) ∈ (9148784066/10⁹, 9148784067/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9403 :
    (9148784066 : ℝ) / 10^9 < Real.log 9403 ∧
    Real.log 9403 < (9148784067 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9403) ?_ ?_
  · -- exp(9148784066/10^9) < 9403: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9403 < exp(9148784067/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9413) ∈ (9149846991/10⁹, 9149846992/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9413 :
    (9149846991 : ℝ) / 10^9 < Real.log 9413 ∧
    Real.log 9413 < (9149846992 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9413) ?_ ?_
  · -- exp(9149846991/10^9) < 9413: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9413 < exp(9149846992/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9419) ∈ (9150484204/10⁹, 9150484205/10⁹). n_hi=35, n_lo=29 -/
theorem log_enc_9419 :
    (9150484204 : ℝ) / 10^9 < Real.log 9419 ∧
    Real.log 9419 < (9150484205 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9419) ?_ ?_
  · -- exp(9150484204/10^9) < 9419: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9419 < exp(9150484205/10^9): use 35 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 35) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9421) ∈ (9150696519/10⁹, 9150696520/10⁹). n_hi=33, n_lo=32 -/
theorem log_enc_9421 :
    (9150696519 : ℝ) / 10^9 < Real.log 9421 ∧
    Real.log 9421 < (9150696520 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9421) ?_ ?_
  · -- exp(9150696519/10^9) < 9421: use 32 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 32) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9421 < exp(9150696520/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9431) ∈ (9151757414/10⁹, 9151757415/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9431 :
    (9151757414 : ℝ) / 10^9 < Real.log 9431 ∧
    Real.log 9431 < (9151757415 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9431) ?_ ?_
  · -- exp(9151757414/10^9) < 9431: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9431 < exp(9151757415/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9433) ∈ (9151969458/10⁹, 9151969459/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9433 :
    (9151969458 : ℝ) / 10^9 < Real.log 9433 ∧
    Real.log 9433 < (9151969459 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9433) ?_ ?_
  · -- exp(9151969458/10^9) < 9433: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9433 < exp(9151969459/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9437) ∈ (9152393412/10⁹, 9152393413/10⁹). n_hi=33, n_lo=32 -/
theorem log_enc_9437 :
    (9152393412 : ℝ) / 10^9 < Real.log 9437 ∧
    Real.log 9437 < (9152393413 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9437) ?_ ?_
  · -- exp(9152393412/10^9) < 9437: use 32 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 32) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9437 < exp(9152393413/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9439) ∈ (9152605321/10⁹, 9152605322/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9439 :
    (9152605321 : ℝ) / 10^9 < Real.log 9439 ∧
    Real.log 9439 < (9152605322 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9439) ?_ ?_
  · -- exp(9152605321/10^9) < 9439: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9439 < exp(9152605322/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9461) ∈ (9154933364/10⁹, 9154933365/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9461 :
    (9154933364 : ℝ) / 10^9 < Real.log 9461 ∧
    Real.log 9461 < (9154933365 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9461) ?_ ?_
  · -- exp(9154933364/10^9) < 9461: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9461 < exp(9154933365/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9463) ∈ (9155144736/10⁹, 9155144737/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9463 :
    (9155144736 : ℝ) / 10^9 < Real.log 9463 ∧
    Real.log 9463 < (9155144737 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9463) ?_ ?_
  · -- exp(9155144736/10^9) < 9463: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9463 < exp(9155144737/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9467) ∈ (9155567346/10⁹, 9155567347/10⁹). n_hi=34, n_lo=31 -/
theorem log_enc_9467 :
    (9155567346 : ℝ) / 10^9 < Real.log 9467 ∧
    Real.log 9467 < (9155567347 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9467) ?_ ?_
  · -- exp(9155567346/10^9) < 9467: use 31 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 31) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9467 < exp(9155567347/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9473) ∈ (9156200925/10⁹, 9156200926/10⁹). n_hi=35, n_lo=29 -/
theorem log_enc_9473 :
    (9156200925 : ℝ) / 10^9 < Real.log 9473 ∧
    Real.log 9473 < (9156200926 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9473) ?_ ?_
  · -- exp(9156200925/10^9) < 9473: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9473 < exp(9156200926/10^9): use 35 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 35) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9479) ∈ (9156834104/10⁹, 9156834105/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9479 :
    (9156834104 : ℝ) / 10^9 < Real.log 9479 ∧
    Real.log 9479 < (9156834105 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9479) ?_ ?_
  · -- exp(9156834104/10^9) < 9479: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9479 < exp(9156834105/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9491) ∈ (9158099260/10⁹, 9158099261/10⁹). n_hi=34, n_lo=31 -/
theorem log_enc_9491 :
    (9158099260 : ℝ) / 10^9 < Real.log 9491 ∧
    Real.log 9491 < (9158099261 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9491) ?_ ?_
  · -- exp(9158099260/10^9) < 9491: use 31 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 31) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9491 < exp(9158099261/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9497) ∈ (9158731238/10⁹, 9158731239/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9497 :
    (9158731238 : ℝ) / 10^9 < Real.log 9497 ∧
    Real.log 9497 < (9158731239 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9497) ?_ ?_
  · -- exp(9158731238/10^9) < 9497: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9497 < exp(9158731239/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9511) ∈ (9160204302/10⁹, 9160204303/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9511 :
    (9160204302 : ℝ) / 10^9 < Real.log 9511 ∧
    Real.log 9511 < (9160204303 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9511) ?_ ?_
  · -- exp(9160204302/10^9) < 9511: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9511 < exp(9160204303/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9521) ∈ (9161255164/10⁹, 9161255165/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9521 :
    (9161255164 : ℝ) / 10^9 < Real.log 9521 ∧
    Real.log 9521 < (9161255165 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9521) ?_ ?_
  · -- exp(9161255164/10^9) < 9521: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9521 < exp(9161255165/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9533) ∈ (9162514742/10⁹, 9162514743/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9533 :
    (9162514742 : ℝ) / 10^9 < Real.log 9533 ∧
    Real.log 9533 < (9162514743 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9533) ?_ ?_
  · -- exp(9162514742/10^9) < 9533: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9533 < exp(9162514743/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9539) ∈ (9163143937/10⁹, 9163143938/10⁹). n_hi=34, n_lo=31 -/
theorem log_enc_9539 :
    (9163143937 : ℝ) / 10^9 < Real.log 9539 ∧
    Real.log 9539 < (9163143938 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9539) ?_ ?_
  · -- exp(9163143937/10^9) < 9539: use 31 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 31) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9539 < exp(9163143938/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9547) ∈ (9163982247/10⁹, 9163982248/10⁹). n_hi=38, n_lo=29 -/
theorem log_enc_9547 :
    (9163982247 : ℝ) / 10^9 < Real.log 9547 ∧
    Real.log 9547 < (9163982248 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9547) ?_ ?_
  · -- exp(9163982247/10^9) < 9547: use 29 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 29) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9547 < exp(9163982248/10^9): use 38 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 38) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9551) ∈ (9164401140/10⁹, 9164401141/10⁹). n_hi=33, n_lo=32 -/
theorem log_enc_9551 :
    (9164401140 : ℝ) / 10^9 < Real.log 9551 ∧
    Real.log 9551 < (9164401141 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9551) ?_ ?_
  · -- exp(9164401140/10^9) < 9551: use 32 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 32) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9551 < exp(9164401141/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9587) ∈ (9168163293/10⁹, 9168163294/10⁹). n_hi=34, n_lo=31 -/
theorem log_enc_9587 :
    (9168163293 : ℝ) / 10^9 < Real.log 9587 ∧
    Real.log 9587 < (9168163294 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9587) ?_ ?_
  · -- exp(9168163293/10^9) < 9587: use 31 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 31) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9587 < exp(9168163294/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9601) ∈ (9169622538/10⁹, 9169622539/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9601 :
    (9169622538 : ℝ) / 10^9 < Real.log 9601 ∧
    Real.log 9601 < (9169622539 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9601) ?_ ?_
  · -- exp(9169622538/10^9) < 9601: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9601 < exp(9169622539/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9613) ∈ (9170871628/10⁹, 9170871629/10⁹). n_hi=34, n_lo=31 -/
theorem log_enc_9613 :
    (9170871628 : ℝ) / 10^9 < Real.log 9613 ∧
    Real.log 9613 < (9170871629 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9613) ?_ ?_
  · -- exp(9170871628/10^9) < 9613: use 31 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 31) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9613 < exp(9170871629/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9619) ∈ (9171495588/10⁹, 9171495589/10⁹). n_hi=34, n_lo=31 -/
theorem log_enc_9619 :
    (9171495588 : ℝ) / 10^9 < Real.log 9619 ∧
    Real.log 9619 < (9171495589 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9619) ?_ ?_
  · -- exp(9171495588/10^9) < 9619: use 31 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 31) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9619 < exp(9171495589/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9623) ∈ (9171911345/10⁹, 9171911346/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9623 :
    (9171911345 : ℝ) / 10^9 < Real.log 9623 ∧
    Real.log 9623 < (9171911346 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9623) ?_ ?_
  · -- exp(9171911345/10^9) < 9623: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9623 < exp(9171911346/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9629) ∈ (9172534657/10⁹, 9172534658/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9629 :
    (9172534657 : ℝ) / 10^9 < Real.log 9629 ∧
    Real.log 9629 < (9172534658 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9629) ?_ ?_
  · -- exp(9172534657/10^9) < 9629: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9629 < exp(9172534658/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9631) ∈ (9172742341/10⁹, 9172742342/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9631 :
    (9172742341 : ℝ) / 10^9 < Real.log 9631 ∧
    Real.log 9631 < (9172742342 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9631) ?_ ?_
  · -- exp(9172742341/10^9) < 9631: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9631 < exp(9172742342/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9643) ∈ (9173987542/10⁹, 9173987543/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9643 :
    (9173987542 : ℝ) / 10^9 < Real.log 9643 ∧
    Real.log 9643 < (9173987543 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9643) ?_ ?_
  · -- exp(9173987542/10^9) < 9643: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9643 < exp(9173987543/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9649) ∈ (9174609562/10⁹, 9174609563/10⁹). n_hi=33, n_lo=32 -/
theorem log_enc_9649 :
    (9174609562 : ℝ) / 10^9 < Real.log 9649 ∧
    Real.log 9649 < (9174609563 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9649) ?_ ?_
  · -- exp(9174609562/10^9) < 9649: use 32 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 32) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9649 < exp(9174609563/10^9): use 33 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 33) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

/-- log(9661) ∈ (9175852441/10⁹, 9175852442/10⁹). n_hi=34, n_lo=30 -/
theorem log_enc_9661 :
    (9175852441 : ℝ) / 10^9 < Real.log 9661 ∧
    Real.log 9661 < (9175852442 : ℝ) / 10^9 := by
  refine log_enclosure_of_exp_bounds (by norm_num : 0 < 9661) ?_ ?_
  · -- exp(9175852441/10^9) < 9661: use 30 Taylor terms + tail
    exact exp_lt_of_partial_sum_tail_lt (n := 30) (by
      unfold expPartialSum expTailBound
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num) (by norm_num)
  · -- 9661 < exp(9175852442/10^9): use 34 Taylor terms
    exact lt_exp_of_lt_partial_sum (n := 34) (by
      unfold expPartialSum
      simp only [Finset.sum_range_succ, Finset.sum_range_zero]
      norm_num [Nat.factorial]) (by norm_num)

end Goldbach
