import Mathlib.Tactic
import TS.Goldbach.Strong.TS117.SelbergDiagonalCoefficientCalculationLedger

namespace TS118
namespace Goldbach

/-!
# TS118 - Selberg LCM Absorption Bridge

TS117 proves that a coefficient depending only on `gcd(m,n)` cannot directly
match the canonical dense `gcd/lcm` kernel. This sprint records the corrective
bridge: absorb the `1/m` and `1/n` factors into the weights, and replace the
pair-sensitive `gcd/lcm` kernel by the gcd-square kernel.

Concretely,

`w(m) w(n) * gcd(m,n)/lcm(m,n)`

is equal termwise to

`(w(m)/m) (w(n)/n) * gcd(m,n)^2`.

The equality is proved over the same finite support as TS108, including the
zero-index cases generated by `Finset.range (level + 1)` under Lean's totalized
division.
-/

/-- Weight after absorbing one factor of the lcm denominator. -/
def selbergLCMAbsorbedWeight
    (weight : Nat -> Rat)
    (m : Nat) :
    Rat :=
  weight m / (m : Rat)

/-- The gcd-square kernel after lcm absorption. -/
def selbergGcdSquareKernel
    (m n : Nat) :
    Rat :=
  (Nat.gcd m n : Rat) ^ (2 : Nat)

/-- One term of the lcm-absorbed gcd-square quadratic form. -/
def selbergGcdSquareFormTerm
    (weight : Nat -> Rat)
    (m n : Nat) :
    Rat :=
  weight m * weight n * selbergGcdSquareKernel m n

/--
The canonical `gcd/lcm` kernel equals `gcd^2/(m*n)`.

The zero cases are handled separately because division in Lean fields is
totalized.
-/
theorem canonicalSelbergQuadraticKernel_eq_gcdSquare_div_mul
    (m n : Nat) :
    TS107.Goldbach.canonicalSelbergQuadraticKernel m n =
      (Nat.gcd m n : Rat) ^ (2 : Nat) / ((m : Rat) * (n : Rat)) := by
  by_cases hm : m = 0
  case pos =>
    subst m
    simp
      [TS107.Goldbach.canonicalSelbergQuadraticKernel,
        TS106.Goldbach.canonicalGcdKernel,
        TS106.Goldbach.canonicalLcmKernel,
        selbergGcdSquareKernel]
  case neg =>
    by_cases hn : n = 0
    case pos =>
      subst n
      simp
        [TS107.Goldbach.canonicalSelbergQuadraticKernel,
          TS106.Goldbach.canonicalGcdKernel,
          TS106.Goldbach.canonicalLcmKernel,
          selbergGcdSquareKernel]
    case neg =>
      unfold TS107.Goldbach.canonicalSelbergQuadraticKernel
      unfold TS106.Goldbach.canonicalGcdKernel
      unfold TS106.Goldbach.canonicalLcmKernel
      have hmRat : Ne (m : Rat) 0 := by
        exact_mod_cast hm
      have hnRat : Ne (n : Rat) 0 := by
        exact_mod_cast hn
      have hlcmNat : Ne (Nat.lcm m n) 0 := by
        intro h
        have hzero : Or (m = 0) (n = 0) := by
          exact (lcm_eq_zero_iff m n).mp h
        cases hzero with
        | inl h0 => exact hm h0
        | inr h0 => exact hn h0
      have hlcmRat : Ne (Nat.lcm m n : Rat) 0 := by
        exact_mod_cast hlcmNat
      have hmul :
          (Nat.gcd m n : Rat) * (Nat.lcm m n : Rat) =
            (m : Rat) * (n : Rat) := by
        exact_mod_cast (Nat.gcd_mul_lcm m n)
      field_simp [hmRat, hnRat, hlcmRat, hmul]
      rw [hmul.symm]
      ring

/--
Termwise absorption of the lcm denominator into the two weights.
-/
theorem selbergQuadraticFormTerm_eq_gcdSquareAbsorbedTerm
    (weight : Nat -> Rat)
    (m n : Nat) :
    TS108.Goldbach.selbergQuadraticFormTerm weight m n =
      selbergGcdSquareFormTerm (selbergLCMAbsorbedWeight weight) m n := by
  unfold TS108.Goldbach.selbergQuadraticFormTerm
  unfold selbergGcdSquareFormTerm
  unfold selbergLCMAbsorbedWeight
  rw [canonicalSelbergQuadraticKernel_eq_gcdSquare_div_mul]
  unfold selbergGcdSquareKernel
  ring_nf

/-- Finite dense side after lcm absorption and the gcd-square kernel. -/
def selbergGcdSquareDenseSide
    (level : Nat)
    (weight : Nat -> Rat) :
    Rat :=
  Finset.sum (TS108.Goldbach.selbergQuadraticSupport level) fun m =>
    Finset.sum (TS108.Goldbach.selbergQuadraticSupport level) fun n =>
      selbergGcdSquareFormTerm weight m n

/--
The original TS110 dense side equals the lcm-absorbed gcd-square dense side.
-/
theorem selbergDenseSide_eq_gcdSquareDenseSide_absorbed
    (level : Nat)
    (weight : Nat -> Rat) :
    TS110.Goldbach.selbergDenseSide level weight =
      selbergGcdSquareDenseSide
        level
        (selbergLCMAbsorbedWeight weight) := by
  unfold TS110.Goldbach.selbergDenseSide
  unfold TS108.Goldbach.selbergQuadraticForm
  unfold selbergGcdSquareDenseSide
  apply Finset.sum_congr rfl
  intro m _hm
  apply Finset.sum_congr rfl
  intro n _hn
  exact selbergQuadraticFormTerm_eq_gcdSquareAbsorbedTerm weight m n

/--
Bridge package for lcm absorption.

This is the correction indicated by TS117: diagonalization should target the
absorbed gcd-square form, not a gcd-only coefficient matched directly against
the original pair-dependent `gcd/lcm` kernel.
-/
structure SelbergLCMAbsorptionBridge
    (level : Nat)
    (weight : Nat -> Rat) where
  absorbedWeight :
    Nat -> Rat

  absorbed_weight_eq :
    forall m : Nat,
      absorbedWeight m = selbergLCMAbsorbedWeight weight m

  gcdSquareKernel :
    Nat -> Nat -> Rat

  gcd_square_kernel_eq :
    forall m n : Nat,
      gcdSquareKernel m n = selbergGcdSquareKernel m n

  absorbedDenseSide :
    Rat

  absorbed_dense_side_eq :
    absorbedDenseSide =
      selbergGcdSquareDenseSide level absorbedWeight

  original_dense_eq_absorbed_dense :
    TS110.Goldbach.selbergDenseSide level weight =
      absorbedDenseSide

  ts117_obstruction_input :
    TS117.Goldbach.SelbergDiagonalCoefficientCalculationTarget

  lcm_absorption_ready :
    True

  corrected_diagonalization_target_ready :
    True

/-- Concrete TS118 lcm-absorption bridge for every finite level and weight. -/
def selbergLCMAbsorptionBridge
    (level : Nat)
    (weight : Nat -> Rat) :
    SelbergLCMAbsorptionBridge level weight where
  absorbedWeight := selbergLCMAbsorbedWeight weight
  absorbed_weight_eq := by
    intro m
    rfl
  gcdSquareKernel := selbergGcdSquareKernel
  gcd_square_kernel_eq := by
    intro m n
    rfl
  absorbedDenseSide :=
    selbergGcdSquareDenseSide level (selbergLCMAbsorbedWeight weight)
  absorbed_dense_side_eq := rfl
  original_dense_eq_absorbed_dense :=
    selbergDenseSide_eq_gcdSquareDenseSide_absorbed level weight
  ts117_obstruction_input :=
    TS117.Goldbach.selbergDiagonalCoefficientCalculationTarget
  lcm_absorption_ready := True.intro
  corrected_diagonalization_target_ready := True.intro

/-- Target proposition for the TS118 lcm-absorption bridge. -/
def SelbergLCMAbsorptionBridgeTarget : Prop :=
  forall level : Nat,
    forall weight : Nat -> Rat,
      Nonempty (SelbergLCMAbsorptionBridge level weight)

/-- The TS118 lcm-absorption bridge is populated for every finite weight. -/
theorem selbergLCMAbsorptionBridgeTarget :
    SelbergLCMAbsorptionBridgeTarget := by
  intro level weight
  exact Nonempty.intro (selbergLCMAbsorptionBridge level weight)

/-- TS118 keeps the TS117 diagnostic target available. -/
theorem selbergDiagonalCoefficientCalculationTarget :
    TS117.Goldbach.SelbergDiagonalCoefficientCalculationTarget :=
  TS117.Goldbach.selbergDiagonalCoefficientCalculationTarget

end Goldbach
end TS118
