import TS.Goldbach.Strong.TS251.ExplicitFormulaMainTermContractObstruction

/-!
# TS252 - Corrected Explicit Formula Contract Installation

TS251 proved that the TS206 universal main-term field is impossible for every
admissible constants package.  This sprint installs a corrected contract beside
TS206 without modifying the historical modules.

The corrected TS204 contract uses the same joint existential statement for its
identity and main-term slots.  Thus both slots refer to the same selected data
witness.  The zero and residual bounds retain their TS206 shapes.

The generic TS248 constructor then consumes corrected explicit-formula evidence
directly.  No bridge back to the obstructed TS206 contract is attempted.
-/

namespace TS252
namespace Goldbach

/--
Corrected TS204 explicit-formula contract generated by a TS206 constants
package.  Identity and main-term identification share one proposition.
-/
noncomputable def correctedExplicitFormulaEffectiveContract
    (K : TS206.Goldbach.TriangleSplineExplicitFormulaConstants) :
    TS204.Goldbach.TriangleSplineExplicitFormulaEffectiveInputContract where
  explicit_formula_identity_statement :=
    TS251.Goldbach.ExplicitFormulaIdentityWithMainTermStatement K
  main_term_identification_statement :=
    TS251.Goldbach.ExplicitFormulaIdentityWithMainTermStatement K
  zero_contribution_bound_statement :=
    (TS206.Goldbach.triangleSplineExplicitFormulaEffectiveContract K)
      |>.zero_contribution_bound_statement
  residual_bound_statement :=
    (TS206.Goldbach.triangleSplineExplicitFormulaEffectiveContract K)
      |>.residual_bound_statement
  effective_constants_statement :=
    TS206.Goldbach.triangleSplineExplicitFormulaConstantsAdmissible K
  compatibility_with_ts181_blueprint_statement :=
    TS206.Goldbach.TriangleSplineExplicitFormulaTS181CompatibilityStatement

/-- The two corrected TS204 slots are definitionally the same proposition. -/
theorem corrected_identity_eq_mainTerm_slot
    (K : TS206.Goldbach.TriangleSplineExplicitFormulaConstants) :
    (correctedExplicitFormulaEffectiveContract K).explicit_formula_identity_statement =
      (correctedExplicitFormulaEffectiveContract K).main_term_identification_statement :=
  rfl

/-- Evidence type for the corrected TS204 explicit-formula contract. -/
abbrev CorrectedExplicitFormulaEffectiveEvidence
    (K : TS206.Goldbach.TriangleSplineExplicitFormulaConstants) :=
  TS204.Goldbach.TriangleSplineExplicitFormulaEffectiveInputEvidence
    (correctedExplicitFormulaEffectiveContract K)

/--
Construct corrected TS204 evidence from the TS251 corrected core, admissible
constants, and the separate TS181 compatibility proposition.
-/
noncomputable def correctedExplicitFormulaEvidence_of_core
    (K : TS206.Goldbach.TriangleSplineExplicitFormulaConstants)
    (constantsAdmissible :
      TS206.Goldbach.triangleSplineExplicitFormulaConstantsAdmissible K)
    (core :
      TS251.Goldbach.CorrectedTriangleSplineExplicitFormulaCoreEvidence K)
    (compatibility :
      TS206.Goldbach.TriangleSplineExplicitFormulaTS181CompatibilityStatement) :
    CorrectedExplicitFormulaEffectiveEvidence K where
  explicit_formula_identity :=
    core.identity_with_main_term
  main_term_identification :=
    core.identity_with_main_term
  zero_contribution_bound :=
    core.zero_contribution_bound
  residual_bound :=
    core.residual_bound
  effective_constants :=
    constantsAdmissible
  compatibility_with_ts181_blueprint :=
    compatibility

/--
Specialized corrected evidence constructor using TS249 admissible constants and
the exact structural compatibility proposition discharged by TS250.
-/
noncomputable def correctedExplicitFormulaEvidence_of_analyticCore
    (mainTermModel : Nat -> Real)
    (zeroConstant residualConstant : NNReal)
    (zeroScalePower zeroLogPower residualScalePower residualLogPower : Nat)
    (lowerScaleOffset : Nat)
    (core :
      TS251.Goldbach.CorrectedTriangleSplineExplicitFormulaCoreEvidence
        (TS249.Goldbach.admissibleExplicitFormulaConstants
          mainTermModel
          zeroConstant
          residualConstant
          zeroScalePower
          zeroLogPower
          residualScalePower
          residualLogPower
          lowerScaleOffset)) :
    CorrectedExplicitFormulaEffectiveEvidence
      (TS249.Goldbach.admissibleExplicitFormulaConstants
        mainTermModel
        zeroConstant
        residualConstant
        zeroScalePower
        zeroLogPower
        residualScalePower
        residualLogPower
        lowerScaleOffset) :=
  correctedExplicitFormulaEvidence_of_core
    (TS249.Goldbach.admissibleExplicitFormulaConstants
      mainTermModel
      zeroConstant
      residualConstant
      zeroScalePower
      zeroLogPower
      residualScalePower
      residualLogPower
      lowerScaleOffset)
    (TS249.Goldbach.admissibleExplicitFormulaConstants_admissible
      mainTermModel
      zeroConstant
      residualConstant
      zeroScalePower
      zeroLogPower
      residualScalePower
      residualLogPower
      lowerScaleOffset)
    core
    TS250.Goldbach.structuralExplicitFormulaTS181Compatibility

/-- Final analytic contracts using the corrected explicit-formula contract. -/
noncomputable def correctedFinalAnalyticContracts
    (K : TS206.Goldbach.TriangleSplineExplicitFormulaConstants)
    (gallagher : TS204.Goldbach.TriangleSplineGallagherInputContract) :
    TS204.Goldbach.FinalTriangleSplineAnalyticInputContracts :=
  TS248.Goldbach.finalAnalyticContractsWithWallOne
    (correctedExplicitFormulaEffectiveContract K)
    gallagher

/--
Build final TS204 analytic evidence from corrected core evidence and Gallagher
evidence.  The concrete Wall 1 evidence is supplied by TS248.
-/
noncomputable def finalAnalyticEvidence_of_correctedCoreGallagher
    (K : TS206.Goldbach.TriangleSplineExplicitFormulaConstants)
    (constantsAdmissible :
      TS206.Goldbach.triangleSplineExplicitFormulaConstantsAdmissible K)
    (core :
      TS251.Goldbach.CorrectedTriangleSplineExplicitFormulaCoreEvidence K)
    (compatibility :
      TS206.Goldbach.TriangleSplineExplicitFormulaTS181CompatibilityStatement)
    (gallagher : TS204.Goldbach.TriangleSplineGallagherInputContract)
    (gallagherEvidence :
      TS204.Goldbach.TriangleSplineGallagherInputEvidence gallagher) :
    TS204.Goldbach.FinalTriangleSplineAnalyticInputEvidence
      (correctedFinalAnalyticContracts K gallagher) :=
  TS248.Goldbach.finalAnalyticEvidence_of_remainingInputs
    (correctedExplicitFormulaEffectiveContract K)
    gallagher
    (correctedExplicitFormulaEvidence_of_core
      K
      constantsAdmissible
      core
      compatibility)
    gallagherEvidence

/--
Specialized final evidence constructor with TS249 constants and TS250 structural
compatibility already populated.
-/
noncomputable def finalAnalyticEvidence_of_analyticCoreGallagher
    (mainTermModel : Nat -> Real)
    (zeroConstant residualConstant : NNReal)
    (zeroScalePower zeroLogPower residualScalePower residualLogPower : Nat)
    (lowerScaleOffset : Nat)
    (core :
      TS251.Goldbach.CorrectedTriangleSplineExplicitFormulaCoreEvidence
        (TS249.Goldbach.admissibleExplicitFormulaConstants
          mainTermModel
          zeroConstant
          residualConstant
          zeroScalePower
          zeroLogPower
          residualScalePower
          residualLogPower
          lowerScaleOffset))
    (gallagher : TS204.Goldbach.TriangleSplineGallagherInputContract)
    (gallagherEvidence :
      TS204.Goldbach.TriangleSplineGallagherInputEvidence gallagher) :
    TS204.Goldbach.FinalTriangleSplineAnalyticInputEvidence
      (correctedFinalAnalyticContracts
        (TS249.Goldbach.admissibleExplicitFormulaConstants
          mainTermModel
          zeroConstant
          residualConstant
          zeroScalePower
          zeroLogPower
          residualScalePower
          residualLogPower
          lowerScaleOffset)
        gallagher) :=
  finalAnalyticEvidence_of_correctedCoreGallagher
    (TS249.Goldbach.admissibleExplicitFormulaConstants
      mainTermModel
      zeroConstant
      residualConstant
      zeroScalePower
      zeroLogPower
      residualScalePower
      residualLogPower
      lowerScaleOffset)
    (TS249.Goldbach.admissibleExplicitFormulaConstants_admissible
      mainTermModel
      zeroConstant
      residualConstant
      zeroScalePower
      zeroLogPower
      residualScalePower
      residualLogPower
      lowerScaleOffset)
    core
    TS250.Goldbach.structuralExplicitFormulaTS181Compatibility
    gallagher
    gallagherEvidence

/-- Ledger recording the parallel corrected contract installation. -/
structure CorrectedExplicitFormulaContractInstallationLedger where
  ts251_obstruction :
    TS251.Goldbach.ExplicitFormulaMainTermContractObstructionLedger

  corrected_slots_joint :
    forall K : TS206.Goldbach.TriangleSplineExplicitFormulaConstants,
      (correctedExplicitFormulaEffectiveContract K).explicit_formula_identity_statement =
        (correctedExplicitFormulaEffectiveContract K).main_term_identification_statement

  corrected_contract_type_installed : True
  corrected_evidence_constructor_defined : True
  corrected_final_analytic_constructor_defined : True

  historical_ts206_contract_not_modified : True
  bridge_to_obstructed_ts206_not_claimed : True
  corrected_identity_with_main_term_not_proved : True
  zero_contribution_bound_not_proved : True
  residual_bound_not_proved : True
  effective_ts206_ts181_alignment_not_encoded : True
  actual_zeta_zero_family_not_constructed : True
  gallagher_evidence_not_proved : True
  final_analytic_to_otsa_bridge_not_proved : True
  otsa_conclusion_bridge_not_proved : True
  goldbach_not_claimed_unconditionally : True

/-- Concrete TS252 corrected-contract ledger. -/
noncomputable def correctedExplicitFormulaContractInstallationLedger :
    CorrectedExplicitFormulaContractInstallationLedger where
  ts251_obstruction :=
    TS251.Goldbach.explicitFormulaMainTermContractObstructionLedger
  corrected_slots_joint :=
    corrected_identity_eq_mainTerm_slot
  corrected_contract_type_installed := True.intro
  corrected_evidence_constructor_defined := True.intro
  corrected_final_analytic_constructor_defined := True.intro
  historical_ts206_contract_not_modified := True.intro
  bridge_to_obstructed_ts206_not_claimed := True.intro
  corrected_identity_with_main_term_not_proved := True.intro
  zero_contribution_bound_not_proved := True.intro
  residual_bound_not_proved := True.intro
  effective_ts206_ts181_alignment_not_encoded := True.intro
  actual_zeta_zero_family_not_constructed := True.intro
  gallagher_evidence_not_proved := True.intro
  final_analytic_to_otsa_bridge_not_proved := True.intro
  otsa_conclusion_bridge_not_proved := True.intro
  goldbach_not_claimed_unconditionally := True.intro

/-- Target proposition for TS252. -/
def CorrectedExplicitFormulaContractInstallationTarget : Prop :=
  Nonempty CorrectedExplicitFormulaContractInstallationLedger

/-- TS252 target: the corrected parallel contract is installed. -/
theorem correctedExplicitFormulaContractInstallationTarget :
    CorrectedExplicitFormulaContractInstallationTarget :=
  Nonempty.intro correctedExplicitFormulaContractInstallationLedger

end Goldbach
end TS252
