import TS.Goldbach.Strong.TS253.ExplicitFormulaBoundsContractObstruction

/-!
# TS254 - Fully Corrected Explicit Formula Contract Installation

TS253 proved that the universal zero and residual bound slots retained by
TS252 are impossible.  It defined a fully corrected analytic statement in
which identity, main-term identification, and both bounds belong to one
existential data witness at every admissible scale.

This sprint installs that statement as a parallel TS204 contract.  All four
analytic slots are definitionally the same proposition and remain genuine
proof obligations.  No historical contract is modified, no analytic evidence
is manufactured, and no hypothesis such as RH is introduced.
-/

namespace TS254
namespace Goldbach

/--
Fully corrected TS204 contract generated by a TS206 constants package.  All
four analytic slots require the same joint existential witness statement.
-/
noncomputable def fullyCorrectedExplicitFormulaEffectiveContract
    (K : TS206.Goldbach.TriangleSplineExplicitFormulaConstants) :
    TS204.Goldbach.TriangleSplineExplicitFormulaEffectiveInputContract where
  explicit_formula_identity_statement :=
    TS253.Goldbach.FullyCorrectedExplicitFormulaStatement K
  main_term_identification_statement :=
    TS253.Goldbach.FullyCorrectedExplicitFormulaStatement K
  zero_contribution_bound_statement :=
    TS253.Goldbach.FullyCorrectedExplicitFormulaStatement K
  residual_bound_statement :=
    TS253.Goldbach.FullyCorrectedExplicitFormulaStatement K
  effective_constants_statement :=
    TS206.Goldbach.triangleSplineExplicitFormulaConstantsAdmissible K
  compatibility_with_ts181_blueprint_statement :=
    TS206.Goldbach.TriangleSplineExplicitFormulaTS181CompatibilityStatement

/-- Identity and main-term slots are definitionally the same proposition. -/
theorem fullyCorrected_identity_eq_mainTerm_slot
    (K : TS206.Goldbach.TriangleSplineExplicitFormulaConstants) :
    (fullyCorrectedExplicitFormulaEffectiveContract K).explicit_formula_identity_statement =
      (fullyCorrectedExplicitFormulaEffectiveContract K).main_term_identification_statement :=
  rfl

/-- Identity and zero-bound slots are definitionally the same proposition. -/
theorem fullyCorrected_identity_eq_zeroBound_slot
    (K : TS206.Goldbach.TriangleSplineExplicitFormulaConstants) :
    (fullyCorrectedExplicitFormulaEffectiveContract K).explicit_formula_identity_statement =
      (fullyCorrectedExplicitFormulaEffectiveContract K).zero_contribution_bound_statement :=
  rfl

/-- Identity and residual-bound slots are definitionally the same proposition. -/
theorem fullyCorrected_identity_eq_residualBound_slot
    (K : TS206.Goldbach.TriangleSplineExplicitFormulaConstants) :
    (fullyCorrectedExplicitFormulaEffectiveContract K).explicit_formula_identity_statement =
      (fullyCorrectedExplicitFormulaEffectiveContract K).residual_bound_statement :=
  rfl

/-- Evidence type for the fully corrected TS204 explicit-formula contract. -/
abbrev FullyCorrectedExplicitFormulaEffectiveEvidence
    (K : TS206.Goldbach.TriangleSplineExplicitFormulaConstants) :=
  TS204.Goldbach.TriangleSplineExplicitFormulaEffectiveInputEvidence
    (fullyCorrectedExplicitFormulaEffectiveContract K)

/--
Construct fully corrected TS204 evidence from the joint TS253 core,
admissible constants, and the separate TS181 compatibility proposition.
-/
noncomputable def fullyCorrectedExplicitFormulaEvidence_of_core
    (K : TS206.Goldbach.TriangleSplineExplicitFormulaConstants)
    (constantsAdmissible :
      TS206.Goldbach.triangleSplineExplicitFormulaConstantsAdmissible K)
    (core :
      TS253.Goldbach.FullyCorrectedExplicitFormulaCoreEvidence K)
    (compatibility :
      TS206.Goldbach.TriangleSplineExplicitFormulaTS181CompatibilityStatement) :
    FullyCorrectedExplicitFormulaEffectiveEvidence K where
  explicit_formula_identity :=
    core.formula_with_main_term_and_bounds
  main_term_identification :=
    core.formula_with_main_term_and_bounds
  zero_contribution_bound :=
    core.formula_with_main_term_and_bounds
  residual_bound :=
    core.formula_with_main_term_and_bounds
  effective_constants :=
    constantsAdmissible
  compatibility_with_ts181_blueprint :=
    compatibility

/--
Specialized evidence constructor using TS249 admissible constants and the
structural TS181 compatibility proposition discharged by TS250.
-/
noncomputable def fullyCorrectedExplicitFormulaEvidence_of_analyticCore
    (mainTermModel : Nat -> Real)
    (zeroConstant residualConstant : NNReal)
    (zeroScalePower zeroLogPower residualScalePower residualLogPower : Nat)
    (lowerScaleOffset : Nat)
    (core :
      TS253.Goldbach.FullyCorrectedExplicitFormulaCoreEvidence
        (TS249.Goldbach.admissibleExplicitFormulaConstants
          mainTermModel
          zeroConstant
          residualConstant
          zeroScalePower
          zeroLogPower
          residualScalePower
          residualLogPower
          lowerScaleOffset)) :
    FullyCorrectedExplicitFormulaEffectiveEvidence
      (TS249.Goldbach.admissibleExplicitFormulaConstants
        mainTermModel
        zeroConstant
        residualConstant
        zeroScalePower
        zeroLogPower
        residualScalePower
        residualLogPower
        lowerScaleOffset) :=
  fullyCorrectedExplicitFormulaEvidence_of_core
    (TS249.Goldbach.admissibleExplicitFormulaConstants
      mainTermModel
      zeroConstant
      residualConstant
      zeroScalePower
      zeroLogPower
      residualScalePower
      residualLogPower
      lowerScaleOffset)
    (TS249.Goldbach.admissibleExplicitFormulaConstants_admissible
      mainTermModel
      zeroConstant
      residualConstant
      zeroScalePower
      zeroLogPower
      residualScalePower
      residualLogPower
      lowerScaleOffset)
    core
    TS250.Goldbach.structuralExplicitFormulaTS181Compatibility

/-- Final analytic contracts using the fully corrected explicit-formula slot. -/
noncomputable def fullyCorrectedFinalAnalyticContracts
    (K : TS206.Goldbach.TriangleSplineExplicitFormulaConstants)
    (gallagher : TS204.Goldbach.TriangleSplineGallagherInputContract) :
    TS204.Goldbach.FinalTriangleSplineAnalyticInputContracts :=
  TS248.Goldbach.finalAnalyticContractsWithWallOne
    (fullyCorrectedExplicitFormulaEffectiveContract K)
    gallagher

/--
Build final TS204 analytic evidence from a fully corrected core and Gallagher
evidence.  The concrete Wall 1 evidence is supplied by TS248.
-/
noncomputable def finalAnalyticEvidence_of_fullyCorrectedCoreGallagher
    (K : TS206.Goldbach.TriangleSplineExplicitFormulaConstants)
    (constantsAdmissible :
      TS206.Goldbach.triangleSplineExplicitFormulaConstantsAdmissible K)
    (core :
      TS253.Goldbach.FullyCorrectedExplicitFormulaCoreEvidence K)
    (compatibility :
      TS206.Goldbach.TriangleSplineExplicitFormulaTS181CompatibilityStatement)
    (gallagher : TS204.Goldbach.TriangleSplineGallagherInputContract)
    (gallagherEvidence :
      TS204.Goldbach.TriangleSplineGallagherInputEvidence gallagher) :
    TS204.Goldbach.FinalTriangleSplineAnalyticInputEvidence
      (fullyCorrectedFinalAnalyticContracts K gallagher) :=
  TS248.Goldbach.finalAnalyticEvidence_of_remainingInputs
    (fullyCorrectedExplicitFormulaEffectiveContract K)
    gallagher
    (fullyCorrectedExplicitFormulaEvidence_of_core
      K
      constantsAdmissible
      core
      compatibility)
    gallagherEvidence

/--
Specialized final evidence constructor with TS249 constants and TS250
structural compatibility already populated.
-/
noncomputable def finalAnalyticEvidence_of_analyticCoreGallagher
    (mainTermModel : Nat -> Real)
    (zeroConstant residualConstant : NNReal)
    (zeroScalePower zeroLogPower residualScalePower residualLogPower : Nat)
    (lowerScaleOffset : Nat)
    (core :
      TS253.Goldbach.FullyCorrectedExplicitFormulaCoreEvidence
        (TS249.Goldbach.admissibleExplicitFormulaConstants
          mainTermModel
          zeroConstant
          residualConstant
          zeroScalePower
          zeroLogPower
          residualScalePower
          residualLogPower
          lowerScaleOffset))
    (gallagher : TS204.Goldbach.TriangleSplineGallagherInputContract)
    (gallagherEvidence :
      TS204.Goldbach.TriangleSplineGallagherInputEvidence gallagher) :
    TS204.Goldbach.FinalTriangleSplineAnalyticInputEvidence
      (fullyCorrectedFinalAnalyticContracts
        (TS249.Goldbach.admissibleExplicitFormulaConstants
          mainTermModel
          zeroConstant
          residualConstant
          zeroScalePower
          zeroLogPower
          residualScalePower
          residualLogPower
          lowerScaleOffset)
        gallagher) :=
  finalAnalyticEvidence_of_fullyCorrectedCoreGallagher
    (TS249.Goldbach.admissibleExplicitFormulaConstants
      mainTermModel
      zeroConstant
      residualConstant
      zeroScalePower
      zeroLogPower
      residualScalePower
      residualLogPower
      lowerScaleOffset)
    (TS249.Goldbach.admissibleExplicitFormulaConstants_admissible
      mainTermModel
      zeroConstant
      residualConstant
      zeroScalePower
      zeroLogPower
      residualScalePower
      residualLogPower
      lowerScaleOffset)
    core
    TS250.Goldbach.structuralExplicitFormulaTS181Compatibility
    gallagher
    gallagherEvidence

/-- Ledger recording the fully corrected parallel contract installation. -/
structure FullyCorrectedExplicitFormulaContractInstallationLedger where
  ts253_bounds_obstruction :
    TS253.Goldbach.ExplicitFormulaBoundsContractObstructionLedger

  identity_eq_mainTerm_slot :
    forall K : TS206.Goldbach.TriangleSplineExplicitFormulaConstants,
      (fullyCorrectedExplicitFormulaEffectiveContract K).explicit_formula_identity_statement =
        (fullyCorrectedExplicitFormulaEffectiveContract K).main_term_identification_statement

  identity_eq_zeroBound_slot :
    forall K : TS206.Goldbach.TriangleSplineExplicitFormulaConstants,
      (fullyCorrectedExplicitFormulaEffectiveContract K).explicit_formula_identity_statement =
        (fullyCorrectedExplicitFormulaEffectiveContract K).zero_contribution_bound_statement

  identity_eq_residualBound_slot :
    forall K : TS206.Goldbach.TriangleSplineExplicitFormulaConstants,
      (fullyCorrectedExplicitFormulaEffectiveContract K).explicit_formula_identity_statement =
        (fullyCorrectedExplicitFormulaEffectiveContract K).residual_bound_statement

  fully_corrected_contract_type_installed : True
  fully_corrected_evidence_constructor_defined : True
  fully_corrected_final_analytic_constructor_defined : True

  historical_ts206_contract_not_modified : True
  historical_ts252_contract_not_modified : True
  bridge_to_obstructed_contracts_not_claimed : True
  fully_corrected_formula_not_proved : True
  effective_ts206_ts181_alignment_not_encoded : True
  actual_zeta_zero_family_not_constructed : True
  gallagher_evidence_not_proved : True
  final_analytic_to_otsa_bridge_not_proved : True
  otsa_conclusion_bridge_not_proved : True
  goldbach_not_claimed_unconditionally : True

/-- Concrete TS254 fully corrected contract ledger. -/
noncomputable def fullyCorrectedExplicitFormulaContractInstallationLedger :
    FullyCorrectedExplicitFormulaContractInstallationLedger where
  ts253_bounds_obstruction :=
    TS253.Goldbach.explicitFormulaBoundsContractObstructionLedger
  identity_eq_mainTerm_slot :=
    fullyCorrected_identity_eq_mainTerm_slot
  identity_eq_zeroBound_slot :=
    fullyCorrected_identity_eq_zeroBound_slot
  identity_eq_residualBound_slot :=
    fullyCorrected_identity_eq_residualBound_slot
  fully_corrected_contract_type_installed := True.intro
  fully_corrected_evidence_constructor_defined := True.intro
  fully_corrected_final_analytic_constructor_defined := True.intro
  historical_ts206_contract_not_modified := True.intro
  historical_ts252_contract_not_modified := True.intro
  bridge_to_obstructed_contracts_not_claimed := True.intro
  fully_corrected_formula_not_proved := True.intro
  effective_ts206_ts181_alignment_not_encoded := True.intro
  actual_zeta_zero_family_not_constructed := True.intro
  gallagher_evidence_not_proved := True.intro
  final_analytic_to_otsa_bridge_not_proved := True.intro
  otsa_conclusion_bridge_not_proved := True.intro
  goldbach_not_claimed_unconditionally := True.intro

/-- Target proposition for TS254. -/
def FullyCorrectedExplicitFormulaContractInstallationTarget : Prop :=
  Nonempty FullyCorrectedExplicitFormulaContractInstallationLedger

/-- TS254 target: the fully corrected parallel contract is installed. -/
theorem fullyCorrectedExplicitFormulaContractInstallationTarget :
    FullyCorrectedExplicitFormulaContractInstallationTarget :=
  Nonempty.intro fullyCorrectedExplicitFormulaContractInstallationLedger

end Goldbach
end TS254
