import ThreeAdicPrimePairing

#print axioms GoldbachRound10.ShortDivisorComplement.mu
#print axioms GoldbachRound10.ShortDivisorComplement.cappedDivisorKernel
#print axioms GoldbachRound10.ShortDivisorComplement.physicalDivisorKernel
#print axioms GoldbachRound10.ShortDivisorComplement.shortDivisorSum
#print axioms GoldbachRound10.ShortDivisorComplement.longDivisorSum
#print axioms GoldbachRound10.ShortDivisorComplement.mu_mul_of_coprime
#print axioms GoldbachRound10.ShortDivisorComplement.mu_square_of_squarefree
#print axioms GoldbachRound10.ShortDivisorComplement.mu_zero_of_not_squarefree
#print axioms GoldbachRound10.ShortDivisorComplement.quotient_coprime
#print axioms GoldbachRound10.ShortDivisorComplement.complementary_moebius
#print axioms GoldbachRound10.ShortDivisorComplement.logarithm_complement
#print axioms GoldbachRound10.ShortDivisorComplement.strict_front_iff
#print axioms GoldbachRound10.ShortDivisorComplement.active_divisor_below_cap
#print axioms GoldbachRound10.ShortDivisorComplement.whole_coefficient_eq_long_sum
#print axioms GoldbachRound10.ShortDivisorComplement.short_plus_long
#print axioms GoldbachRound10.ShortDivisorComplement.short_divisor_complement
#print axioms GoldbachRound10.ShortDivisorComplement.source_cap
#print axioms GoldbachRound10.ShortDivisorComplement.short_divisor_complement_source
#print axioms GoldbachRound10.ShortDivisorComplement.physical_divisor_units
#print axioms GoldbachRound10.ShortDivisorComplement.physical_kernel_eq
#print axioms GoldbachRound10.ShortDivisorComplement.physical_short_divisor_complement_source
#print axioms GoldbachRound10.ShortDivisorComplement.at_one
#print axioms GoldbachRound11.harmonicKernel
#print axioms GoldbachRound11.primeIncidence
#print axioms GoldbachRound11.theta
#print axioms GoldbachRound11.sourceBracket
#print axioms GoldbachRound11.short_filter_prime_pair
#print axioms GoldbachRound11.complete_short_prime_pair
#print axioms GoldbachRound11.prime_pair_arithmetic
#print axioms GoldbachRound11.actual_source_bracket_j2
#print axioms GoldbachRound11.mu_three_mul
#print axioms GoldbachRound11.actual_three_adic_pair
#print axioms GoldbachRound11.coreGrid
#print axioms GoldbachRound11.pairedBases
#print axioms GoldbachRound11.geometricFaces
#print axioms GoldbachRound11.three_mul_mem_grid
#print axioms GoldbachRound11.core_grid_partition
#print axioms GoldbachRound11.paired_disjoint_image
#print axioms GoldbachRound11.paired_union_disjoint_face
#print axioms GoldbachRound11.sum_core_grid
#print axioms GoldbachRound11.bulkCap
#print axioms GoldbachRound11.three_coprime_mask
#print axioms GoldbachRound11.literal_bulk_front
#print axioms GoldbachRound11.bulk_cap_le_front
#print axioms GoldbachRound11.actual_bracket_partition
#print axioms GoldbachRound11.pairedSourceExpression
#print axioms GoldbachRound11.actual_p1_partition
#print axioms GoldbachRound11.twinConstant
#print axioms GoldbachRound11.singularSeries
#print axioms GoldbachRound11.principalTerm
#print axioms GoldbachRound11.entropyTerm
#print axioms GoldbachRound11.commonTerm
#print axioms GoldbachRound11.singletonTerm
#print axioms GoldbachRound11.principal_pair_split
#print axioms GoldbachRound11.principal_face_split
#print axioms GoldbachRound11.actual_principal_partition
